// Generated by npm run sync:tpg. Do not edit manually.
module.exports = [
  {
    "id": "POLYU-TPG-013",
    "courseGroups": [
      {
        "id": "compulsory-subjects",
        "name": "Compulsory Subjects",
        "type": "core",
        "creditsRequired": 22,
        "coursesRequired": 7,
        "ruleText": "Complete all seven Compulsory Subjects for 22 credits.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12060-mft-mpt",
        "courses": [
          {
            "code": "ABCT5031",
            "name": "Ecological Approaches for Carbon Management",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12060-mft-mpt"
          },
          {
            "code": "ABCT5032",
            "name": "Materials Science for Carbon Neutrality Applications",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12060-mft-mpt"
          },
          {
            "code": "ABCT5033",
            "name": "Renewable Energies and Technologies I: Hydrogen and Biofuels",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12060-mft-mpt"
          },
          {
            "code": "ABCT5042",
            "name": "Quantitation and Reporting of Greenhouse Gases and Carbon Footprint and Climate Action Methodologies",
            "credits": 6,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12060-mft-mpt"
          },
          {
            "code": "ABCT5T01",
            "name": "Academic Integrity and Ethics in Science",
            "credits": 1,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12060-mft-mpt"
          },
          {
            "code": "AF5130",
            "name": "Sustainable Finance",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12060-mft-mpt"
          },
          {
            "code": "AP5021",
            "name": "Renewable Energies and Technologies II: Energy Conversion and Storage",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12060-mft-mpt"
          }
        ]
      },
      {
        "id": "project-options",
        "name": "Project or Research Project Option",
        "type": "project",
        "coursesRequired": 1,
        "ruleText": "Choose either ABCT5039 Project (3 credits) with at least 6 credits from the Elective Subject pool, or ABCT5040 Research Project (6 credits) with at least 3 credits from the Elective Subject pool.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12060-mft-mpt",
        "courses": [
          {
            "code": "ABCT5039",
            "name": "Project",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12060-mft-mpt",
            "courseKind": "project",
            "conditionalRequirement": true
          },
          {
            "code": "ABCT5040",
            "name": "Research Project",
            "credits": 6,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12060-mft-mpt",
            "courseKind": "research_project",
            "conditionalRequirement": true
          }
        ]
      },
      {
        "id": "elective-subjects",
        "name": "Elective Subjects",
        "type": "elective",
        "ruleText": "Complete at least 6 elective credits with ABCT5039, or at least 3 elective credits with ABCT5040. This conditional requirement must be checked together with the selected project path.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12060-mft-mpt",
        "courses": [
          {
            "code": "ABCT5037",
            "name": "Green Chemistry for Sustainable Products Development",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12060-mft-mpt"
          },
          {
            "code": "ABCT5038",
            "name": "Expert Seminars: Special Topics in Sustainable Science and Technology",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12060-mft-mpt"
          },
          {
            "code": "ABCT5041",
            "name": "Sustainable Chemistry for Circular Economy",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12060-mft-mpt"
          },
          {
            "code": "AMA569",
            "name": "Stochastic Models for Carbon Pricing and Trading",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12060-mft-mpt"
          },
          {
            "code": "AP5022",
            "name": "Energy Efficient Lighting and Control",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12060-mft-mpt"
          },
          {
            "code": "BSE542",
            "name": "Energy Efficient Buildings",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12060-mft-mpt"
          },
          {
            "code": "EE546",
            "name": "Electric Energy Storage and New Energy Sources for Electric Vehicles",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12060-mft-mpt"
          }
        ]
      }
    ]
  },
  {
    "id": "POLYU-TPG-014",
    "courseGroups": [
      {
        "id": "core-subjects",
        "name": "Core Subjects",
        "type": "core",
        "creditsRequired": 21,
        "coursesRequired": 7,
        "ruleText": "Complete all seven 3-credit Core Subjects.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12062-mft-mpt",
        "courses": [
          {
            "code": "ABCT5101",
            "name": "Modern Approaches in Biopharmaceutical Development",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12062-mft-mpt"
          },
          {
            "code": "ABCT5102",
            "name": "Pharmacology and Toxicology in Biotherapeutics",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12062-mft-mpt"
          },
          {
            "code": "ABCT5103",
            "name": "Intellectual Property Strategy for Biotech Entrepreneurship",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12062-mft-mpt"
          },
          {
            "code": "ABCT5104",
            "name": "Regulatory Science for Biotech Products",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12062-mft-mpt"
          },
          {
            "code": "ABCT5105",
            "name": "Ethics and Management in Life Sciences",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12062-mft-mpt"
          },
          {
            "code": "ABCT5106",
            "name": "Technology Platforms in Drug Discovery",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12062-mft-mpt"
          },
          {
            "code": "ABCT5107",
            "name": "Advanced Therapeutic Products",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12062-mft-mpt"
          }
        ]
      },
      {
        "id": "financing-or-entrepreneurship",
        "name": "Financing or Entrepreneurship Pool",
        "type": "elective",
        "creditsRequired": 3,
        "coursesRequired": 1,
        "ruleText": "Choose either ABCT5108 or ABCT5109.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12062-mft-mpt",
        "courses": [
          {
            "code": "ABCT5108",
            "name": "Investment Financing and Risk Management in Biobusiness",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12062-mft-mpt",
            "conditionalRequirement": true
          },
          {
            "code": "ABCT5109",
            "name": "Entrepreneurship- From Lab to Launch",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12062-mft-mpt",
            "conditionalRequirement": true
          }
        ]
      },
      {
        "id": "attachment-or-research-project",
        "name": "Industrial Attachment or Research Project Pool",
        "type": "project",
        "creditsRequired": 6,
        "coursesRequired": 1,
        "ruleText": "Choose either ABCT5110 Industrial Attachment or ABCT5113 Research Project.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12062-mft-mpt",
        "courses": [
          {
            "code": "ABCT5110",
            "name": "Industrial Attachment",
            "credits": 6,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12062-mft-mpt",
            "courseKind": "internship",
            "conditionalRequirement": true
          },
          {
            "code": "ABCT5113",
            "name": "Research Project",
            "credits": 6,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12062-mft-mpt",
            "courseKind": "research_project",
            "conditionalRequirement": true
          }
        ]
      },
      {
        "id": "academic-integrity",
        "name": "Academic Integrity and Ethics",
        "type": "academic_integrity",
        "creditsRequired": 1,
        "coursesRequired": 1,
        "ruleText": "Complete ABCT5T01 Academic Integrity and Ethics in Science. The standard page names the subject without its code; the code and credit are published on the official GBA variant page.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12062-mft-mpt",
        "courses": [
          {
            "code": "ABCT5T01",
            "name": "Academic Integrity and Ethics in Science",
            "credits": 1,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12063"
          }
        ]
      }
    ]
  },
  {
    "id": "POLYU-TPG-015",
    "courseGroups": [
      {
        "id": "hong-kong-core-subjects",
        "name": "Hong Kong Campus Core Subjects",
        "type": "core",
        "creditsRequired": 18,
        "coursesRequired": 6,
        "ruleText": "Complete the six listed 3-credit Core Subjects at the PolyU Hong Kong campus.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12063",
        "courses": [
          {
            "code": "ABCT5101",
            "name": "Modern Approaches in Biopharmaceutical Development",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12063"
          },
          {
            "code": "ABCT5103",
            "name": "Intellectual Property Strategy for Biotech Entrepreneurship",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12063"
          },
          {
            "code": "ABCT5104",
            "name": "Regulatory Science for Biotech Products",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12063"
          },
          {
            "code": "ABCT5105",
            "name": "Ethics and Management in Life Sciences",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12063"
          },
          {
            "code": "ABCT5106",
            "name": "Technology Platforms in Drug Discovery",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12063"
          },
          {
            "code": "ABCT5107",
            "name": "Advanced Therapeutic Products",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12063"
          }
        ]
      },
      {
        "id": "financing-or-entrepreneurship",
        "name": "Financing or Entrepreneurship Pool",
        "type": "elective",
        "creditsRequired": 3,
        "coursesRequired": 1,
        "ruleText": "Choose either ABCT5108 or ABCT5109 at the PolyU Hong Kong campus.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12063",
        "courses": [
          {
            "code": "ABCT5108",
            "name": "Investment Financing and Risk Management in Biobusiness",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12063",
            "conditionalRequirement": true
          },
          {
            "code": "ABCT5109",
            "name": "Entrepreneurship- From Lab to Launch",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12063",
            "conditionalRequirement": true
          }
        ]
      },
      {
        "id": "academic-integrity",
        "name": "Academic Integrity and Ethics",
        "type": "academic_integrity",
        "creditsRequired": 1,
        "coursesRequired": 1,
        "ruleText": "Complete ABCT5T01 Academic Integrity and Ethics in Science.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12063",
        "courses": [
          {
            "code": "ABCT5T01",
            "name": "Academic Integrity and Ethics in Science",
            "credits": 1,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12063"
          }
        ]
      },
      {
        "id": "polyu-zsri-subjects",
        "name": "PolyU-ZSRI Subjects",
        "type": "core",
        "creditsRequired": 9,
        "coursesRequired": 2,
        "ruleText": "Complete ABCT5115P and ABCT5102P at PolyU-ZSRI; the official page states that these subjects are taught in Putonghua.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12063",
        "courses": [
          {
            "code": "ABCT5115P",
            "name": "Industrial Attachment (GBA)",
            "credits": 6,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12063",
            "courseKind": "internship"
          },
          {
            "code": "ABCT5102P",
            "name": "Pharmacology and Toxicology in Biotherapeutics",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/12063"
          }
        ]
      }
    ]
  },
  {
    "id": "POLYU-TPG-090",
    "courseGroups": [
      {
        "id": "core",
        "name": "Core Subjects",
        "type": "core",
        "creditsRequired": 18,
        "ruleText": "Choose any six of the eight Core Subjects.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msc-bt/curriculum/",
        "courses": [
          {
            "code": "COMP5521",
            "name": "Distributed Ledger Technology, Cryptocurrency and E-Payment",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msc-bt/curriculum/"
          },
          {
            "code": "COMP5563",
            "name": "Applied Cryptography for Financial Applications",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msc-bt/curriculum/"
          },
          {
            "code": "COMP5564",
            "name": "Machine Learning and Applications in Finance",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msc-bt/curriculum/"
          },
          {
            "code": "COMP5565",
            "name": "Decentralized Apps Fundamentals and Development",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msc-bt/curriculum/"
          },
          {
            "code": "COMP5566",
            "name": "Blockchain and Smart Contract Security",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msc-bt/curriculum/"
          },
          {
            "code": "COMP5567",
            "name": "Distributed Algorithms and Protocols for Blockchains",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msc-bt/curriculum/"
          },
          {
            "code": "COMP5568",
            "name": "Decentralized Finance",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msc-bt/curriculum/"
          },
          {
            "code": "COMP5569",
            "name": "Fintech Regulation and Compliance",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msc-bt/curriculum/"
          }
        ]
      },
      {
        "id": "elective-options",
        "name": "Elective / Project / Dissertation Options",
        "type": "elective",
        "creditsRequired": 12,
        "ruleText": "Complete the dissertation, project, or taught-subject path stated in the official award requirements.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msc-bt/curriculum/",
        "courses": [
          {
            "code": "AF5115",
            "name": "Accounting for Business Analysis",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msc-bt/curriculum/"
          },
          {
            "code": "AF5312",
            "name": "Principles of Corporate Finance",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msc-bt/curriculum/"
          },
          {
            "code": "AF5344",
            "name": "Investments",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msc-bt/curriculum/"
          },
          {
            "code": "AF5341",
            "name": "Economics for Financial Analysis",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msc-bt/curriculum/"
          },
          {
            "code": "AF5343",
            "name": "Quantitative Methods for Finance",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msc-bt/curriculum/"
          },
          {
            "code": "AF5347",
            "name": "Financial Analysis and Valuation",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msc-bt/curriculum/"
          },
          {
            "code": "AF5351",
            "name": "Derivatives Securities",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msc-bt/curriculum/"
          },
          {
            "code": "COMP5112",
            "name": "Data Structures and Database Systems",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msc-bt/curriculum/"
          },
          {
            "code": "COMP5152",
            "name": "Advanced Data Analytics",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msc-bt/curriculum/"
          },
          {
            "code": "COMP5221",
            "name": "Software Project Management",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msc-bt/curriculum/"
          },
          {
            "code": "COMP5241",
            "name": "Software Engineering and Development",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msc-bt/curriculum/"
          },
          {
            "code": "COMP5311",
            "name": "Internet Infrastructure and Protocols",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msc-bt/curriculum/"
          },
          {
            "code": "COMP5355",
            "name": "Cyber and Internet Security",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msc-bt/curriculum/"
          },
          {
            "code": "COMP5423",
            "name": "Natural Language Processing",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msc-bt/curriculum/"
          },
          {
            "code": "COMP5434",
            "name": "Big Data Computing",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msc-bt/curriculum/"
          },
          {
            "code": "COMP5511",
            "name": "Artificial Intelligence Concepts",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msc-bt/curriculum/"
          },
          {
            "code": "COMP5523",
            "name": "Computer Vision and Image Processing",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msc-bt/curriculum/"
          },
          {
            "code": "COMP5541",
            "name": "Machine Learning and Data Analytics",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msc-bt/curriculum/"
          },
          {
            "code": "COMP5542",
            "name": "Optimization and Applications",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msc-bt/curriculum/"
          },
          {
            "code": "COMP5574",
            "name": "Computational Economics and Algorithms",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msc-bt/curriculum/"
          },
          {
            "code": "COMP5576",
            "name": "Modern Cryptography",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msc-bt/curriculum/"
          },
          {
            "code": "COMP5577",
            "name": "AI Security",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msc-bt/curriculum/"
          },
          {
            "code": "COMP5579",
            "name": "IoT Security: Principles, Protocols, and Practice",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msc-bt/curriculum/"
          },
          {
            "code": "COMP5583",
            "name": "Agentic Computing, Systems, and Applications",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msc-bt/curriculum/"
          },
          {
            "code": "COMP5584",
            "name": "Large Language Models for Agents",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msc-bt/curriculum/"
          },
          {
            "code": "COMP5933",
            "name": "Project",
            "credits": 6,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msc-bt/curriculum/"
          },
          {
            "code": "COMP5940",
            "name": "Dissertation",
            "credits": 9,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msc-bt/curriculum/"
          }
        ]
      },
      {
        "id": "academic-integrity",
        "name": "Academic Integrity and Ethics",
        "type": "academic_integrity",
        "creditsRequired": 1,
        "ruleText": "Complete the compulsory AIE subject.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msc-bt/curriculum/",
        "courses": [
          {
            "code": "DSAI5T09",
            "name": "Academic Integrity and Ethics in Computer and Mathematical Sciences",
            "credits": 1,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msc-bt/curriculum/"
          }
        ]
      }
    ]
  },
  {
    "id": "POLYU-TPG-092",
    "courseGroups": [
      {
        "id": "core",
        "name": "Core Subjects",
        "type": "core",
        "creditsRequired": 12,
        "coursesRequired": 4,
        "ruleText": "Complete four Core Subjects.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msccys/curriculum/?sc_lang=en",
        "courses": [
          {
            "code": "COMP5576",
            "name": "Modern Cryptography",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msccys/curriculum/?sc_lang=en"
          },
          {
            "code": "COMP5577",
            "name": "AI Security",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msccys/curriculum/?sc_lang=en"
          },
          {
            "code": "COMP5578",
            "name": "Cybersecurity Risk Management",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msccys/curriculum/?sc_lang=en"
          },
          {
            "code": "EEE541",
            "name": "Privacy Technologies and Management",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msccys/curriculum/?sc_lang=en"
          }
        ]
      },
      {
        "id": "disciplinary-elective",
        "name": "Disciplinary-specific Electives",
        "type": "disciplinary_elective",
        "creditsRequired": 9,
        "coursesRequired": 3,
        "ruleText": "Complete three Disciplinary-specific Electives.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msccys/curriculum/?sc_lang=en",
        "courses": [
          {
            "code": "COMP5355",
            "name": "Cyber and Internet Security",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msccys/curriculum/?sc_lang=en"
          },
          {
            "code": "COMP5579",
            "name": "IoT Security: Principles, Protocols, and Practice",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msccys/curriculum/?sc_lang=en"
          },
          {
            "code": "COMP5580",
            "name": "Mobile and Wireless Security",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msccys/curriculum/?sc_lang=en"
          },
          {
            "code": "EEE542",
            "name": "Digital Forensics",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msccys/curriculum/?sc_lang=en"
          },
          {
            "code": "EEE543",
            "name": "Cybersecurity Testing and Intrusion Prevention",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msccys/curriculum/?sc_lang=en"
          }
        ]
      },
      {
        "id": "elective-options",
        "name": "Elective / Project / Dissertation Options",
        "type": "elective",
        "creditsRequired": 9,
        "ruleText": "Complete the dissertation, project, or taught-subject path stated in the official award requirements.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msccys/curriculum/?sc_lang=en",
        "courses": [
          {
            "code": "COMP5112",
            "name": "Data Structures and Database Systems",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msccys/curriculum/?sc_lang=en"
          },
          {
            "code": "COMP5113",
            "name": "AIBD Programming",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msccys/curriculum/?sc_lang=en"
          },
          {
            "code": "COMP5140",
            "name": "Metaverse Fundamentals",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msccys/curriculum/?sc_lang=en"
          },
          {
            "code": "COMP5241",
            "name": "Software Engineering and Development",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msccys/curriculum/?sc_lang=en"
          },
          {
            "code": "COMP5311",
            "name": "Internet Infrastructure and Protocols",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msccys/curriculum/?sc_lang=en"
          },
          {
            "code": "COMP5327",
            "name": "Wireless Networking and Mobile Computing",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msccys/curriculum/?sc_lang=en"
          },
          {
            "code": "COMP5521",
            "name": "Distributed Ledger Technology, Cryptocurrency and E-Payment",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msccys/curriculum/?sc_lang=en"
          },
          {
            "code": "COMP5523",
            "name": "Computer Vision and Image Processing",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msccys/curriculum/?sc_lang=en"
          },
          {
            "code": "COMP5554",
            "name": "Advanced Artificial Intelligence",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msccys/curriculum/?sc_lang=en"
          },
          {
            "code": "COMP5563",
            "name": "Applied Cryptography for Financial Applications",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msccys/curriculum/?sc_lang=en"
          },
          {
            "code": "COMP5565",
            "name": "Decentralized Apps Fundamentals and Development",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msccys/curriculum/?sc_lang=en"
          },
          {
            "code": "COMP5566",
            "name": "Blockchain and Smart Contract Security",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msccys/curriculum/?sc_lang=en"
          },
          {
            "code": "COMP5569",
            "name": "Fintech Regulation and Compliance",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msccys/curriculum/?sc_lang=en"
          },
          {
            "code": "DSAI5101",
            "name": "Statistical Data Mining",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msccys/curriculum/?sc_lang=en"
          },
          {
            "code": "DSAI5201",
            "name": "Artificial Intelligence and Big Data Computing in Practice",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msccys/curriculum/?sc_lang=en"
          },
          {
            "code": "EEE513",
            "name": "Introduction to Quantum Computing",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msccys/curriculum/?sc_lang=en"
          },
          {
            "code": "EEE531",
            "name": "Spoken Language Processing",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msccys/curriculum/?sc_lang=en"
          },
          {
            "code": "EIE522",
            "name": "Pattern Recognition: Theory & Applications",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msccys/curriculum/?sc_lang=en"
          },
          {
            "code": "EIE546",
            "name": "Video Technology",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msccys/curriculum/?sc_lang=en"
          },
          {
            "code": "EIE553",
            "name": "Security in Data Communication",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msccys/curriculum/?sc_lang=en"
          },
          {
            "code": "EIE557",
            "name": "Computational Intelligence and its Applications",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msccys/curriculum/?sc_lang=en"
          },
          {
            "code": "EIE558",
            "name": "Speech Processing and Recognition",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msccys/curriculum/?sc_lang=en"
          },
          {
            "code": "EIE568",
            "name": "IoT - Tools and Applications",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msccys/curriculum/?sc_lang=en"
          },
          {
            "code": "EIE569",
            "name": "Sensor Networks",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msccys/curriculum/?sc_lang=en"
          },
          {
            "code": "EIE573",
            "name": "Mobile Edge Computing",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msccys/curriculum/?sc_lang=en"
          },
          {
            "code": "COMP5933",
            "name": "Project",
            "credits": 6,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msccys/curriculum/?sc_lang=en"
          },
          {
            "code": "COMP5940",
            "name": "Dissertation",
            "credits": 9,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msccys/curriculum/?sc_lang=en"
          },
          {
            "code": "DSAI5901",
            "name": "Dissertation",
            "credits": 9,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msccys/curriculum/?sc_lang=en"
          },
          {
            "code": "EIE590",
            "name": "MSc Dissertation",
            "credits": 9,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msccys/curriculum/?sc_lang=en"
          }
        ]
      },
      {
        "id": "academic-integrity",
        "name": "Academic Integrity and Ethics",
        "type": "academic_integrity",
        "creditsRequired": 1,
        "coursesRequired": 1,
        "ruleText": "Complete the compulsory AIE subject.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msccys/curriculum/?sc_lang=en",
        "courses": [
          {
            "code": "DSAI5T09",
            "name": "Academic Integrity and Ethics in Computer and Mathematical Sciences",
            "credits": 1,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/msccys/curriculum/?sc_lang=en"
          }
        ]
      }
    ]
  },
  {
    "id": "POLYU-TPG-093",
    "courseGroups": [
      {
        "id": "core",
        "name": "Core Subjects",
        "type": "core",
        "creditsRequired": 9,
        "ruleText": "Choose three Core Subjects.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/mscas/curriculum/?sc_lang=en",
        "courses": [
          {
            "code": "COMP5582",
            "name": "Artificial Intelligence of Things",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/mscas/curriculum/?sc_lang=en"
          },
          {
            "code": "COMP5583",
            "name": "Agentic Computing, Systems, and Applications",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/mscas/curriculum/?sc_lang=en"
          },
          {
            "code": "COMP5584",
            "name": "Large Language Models for Agents",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/mscas/curriculum/?sc_lang=en"
          },
          {
            "code": "DSAI5205",
            "name": "Introduction to Artificial Intelligence",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/mscas/curriculum/?sc_lang=en"
          },
          {
            "code": "DSAI5208",
            "name": "Trustworthy AI Systems and Technologies",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/mscas/curriculum/?sc_lang=en"
          }
        ]
      },
      {
        "id": "disciplinary-elective",
        "name": "Disciplinary-specific Electives",
        "type": "disciplinary_elective",
        "creditsRequired": 9,
        "ruleText": "Choose three Disciplinary-specific Electives.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/mscas/curriculum/?sc_lang=en",
        "courses": [
          {
            "code": "COMP5434",
            "name": "Big Data Computing",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/mscas/curriculum/?sc_lang=en"
          },
          {
            "code": "COMP5517",
            "name": "Human Computer Interaction",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/mscas/curriculum/?sc_lang=en"
          },
          {
            "code": "COMP5523",
            "name": "Computer Vision and Image Processing",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/mscas/curriculum/?sc_lang=en"
          },
          {
            "code": "COMP5554",
            "name": "Advanced Artificial Intelligence",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/mscas/curriculum/?sc_lang=en"
          },
          {
            "code": "COMP5585",
            "name": "Cloud Computing and Hyperscale AI Infrastructure",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/mscas/curriculum/?sc_lang=en"
          },
          {
            "code": "COMP5586",
            "name": "Embedded Systems",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/mscas/curriculum/?sc_lang=en"
          },
          {
            "code": "AMA577",
            "name": "Theoretical Aspects of Reinforcement Learning",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/mscas/curriculum/?sc_lang=en"
          },
          {
            "code": "DSAI5201",
            "name": "Artificial Intelligence and Big Data Computing in Practice",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/mscas/curriculum/?sc_lang=en"
          },
          {
            "code": "DSAI5203",
            "name": "Brain-inspired Computing",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/mscas/curriculum/?sc_lang=en"
          },
          {
            "code": "DSAI5204",
            "name": "Efficient Data Processing",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/mscas/curriculum/?sc_lang=en"
          },
          {
            "code": "DSAI5207",
            "name": "Modern Deep Learning",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/mscas/curriculum/?sc_lang=en"
          },
          {
            "code": "ME5301",
            "name": "Embodied Robot Intelligence",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/mscas/curriculum/?sc_lang=en"
          }
        ]
      },
      {
        "id": "elective-options",
        "name": "Elective / Project / Dissertation Options",
        "type": "elective",
        "creditsRequired": 12,
        "ruleText": "Complete the dissertation, project, or taught-subject path stated in the official award requirements.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/mscas/curriculum/?sc_lang=en",
        "courses": [
          {
            "code": "COMP5423",
            "name": "Natural Language Processing",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/mscas/curriculum/?sc_lang=en"
          },
          {
            "code": "COMP5542",
            "name": "Optimization and Applications",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/mscas/curriculum/?sc_lang=en"
          },
          {
            "code": "COMP5577",
            "name": "AI Security",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/mscas/curriculum/?sc_lang=en"
          },
          {
            "code": "AMA528",
            "name": "Probability and Stochastic Models",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/mscas/curriculum/?sc_lang=en"
          },
          {
            "code": "AMA529",
            "name": "Statistical Inference",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/mscas/curriculum/?sc_lang=en"
          },
          {
            "code": "DSAI5101",
            "name": "Statistical Data Mining",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/mscas/curriculum/?sc_lang=en"
          },
          {
            "code": "DSAI5105",
            "name": "Hands-on AI for Science and Technology",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/mscas/curriculum/?sc_lang=en"
          },
          {
            "code": "DSAI5202",
            "name": "Emerging Topics in Artificial Intelligence and Big Data Computing",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/mscas/curriculum/?sc_lang=en"
          },
          {
            "code": "EIE568",
            "name": "IoT Tools and Applications",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/mscas/curriculum/?sc_lang=en"
          },
          {
            "code": "ISE5312",
            "name": "Industrial Human-Robot Systems and Automation",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/mscas/curriculum/?sc_lang=en"
          },
          {
            "code": "SD5132",
            "name": "Lab Studies in Human Cyber-Physical Systems",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/mscas/curriculum/?sc_lang=en"
          },
          {
            "code": "COMP5934",
            "name": "Agentic AI Systems Project",
            "credits": 6,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/mscas/curriculum/?sc_lang=en"
          },
          {
            "code": "COMP5940",
            "name": "Dissertation",
            "credits": 9,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/mscas/curriculum/?sc_lang=en"
          },
          {
            "code": "DSAI5901",
            "name": "Dissertation",
            "credits": 9,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/mscas/curriculum/?sc_lang=en"
          }
        ]
      },
      {
        "id": "academic-integrity",
        "name": "Academic Integrity and Ethics",
        "type": "academic_integrity",
        "creditsRequired": 1,
        "ruleText": "Complete the compulsory AIE subject.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/mscas/curriculum/?sc_lang=en",
        "courses": [
          {
            "code": "DSAI5T09",
            "name": "Academic Integrity and Ethics in Computer and Mathematical Sciences",
            "credits": 1,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/comp/study/taught-postgraduate-programme/mscas/curriculum/?sc_lang=en"
          }
        ]
      }
    ]
  },
  {
    "id": "POLYU-TPG-102",
    "courseGroups": [
      {
        "id": "workshop-and-academic-integrity",
        "name": "Workshop and Academic Integrity",
        "type": "core",
        "creditsRequired": 2,
        "coursesRequired": 2,
        "ruleText": "All six MSc award paths complete HTM5002 and HTM5T02 for 2 credits in total.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
        "courses": [
          {
            "code": "HTM5002",
            "name": "Introductory Workshop",
            "credits": 1,
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
            "appliesToTrackIds": []
          },
          {
            "code": "HTM5T02",
            "name": "Academic Integrity and Ethics (AIE) in Business Studies and Research",
            "credits": 1,
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
            "appliesToTrackIds": []
          }
        ]
      },
      {
        "id": "compulsory-subjects",
        "name": "Compulsory Subjects",
        "type": "core",
        "creditsRequiredByTrackIds": {
          "POLYU-TPG-102-AIH": 12,
          "POLYU-TPG-102-IEH": 12,
          "POLYU-TPG-102-IHM": 12,
          "POLYU-TPG-102-ITEM": 12,
          "POLYU-TPG-102-LEM": 12,
          "POLYU-TPG-102-IWM": 9
        },
        "coursesRequiredByTrackIds": {
          "POLYU-TPG-102-AIH": 4,
          "POLYU-TPG-102-IEH": 4,
          "POLYU-TPG-102-IHM": 4,
          "POLYU-TPG-102-ITEM": 4,
          "POLYU-TPG-102-LEM": 4,
          "POLYU-TPG-102-IWM": 3
        },
        "ruleText": "AIH, IEH, IHM, ITEM and LEM complete HTM533, HTM534, HTM535 and HTM582 (12 credits). IWM completes HTM534, HTM535 and HTM582 (9 credits).",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
        "courses": [
          {
            "code": "HTM533",
            "name": "Managing Human Resources in the Hospitality & Tourism Industry",
            "credits": 3,
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
            "appliesToTrackIds": [
              "POLYU-TPG-102-AIH",
              "POLYU-TPG-102-IEH",
              "POLYU-TPG-102-IHM",
              "POLYU-TPG-102-ITEM",
              "POLYU-TPG-102-LEM"
            ]
          },
          {
            "code": "HTM534",
            "name": "Managing Marketing in the Hospitality & Tourism Industry",
            "credits": 3,
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
            "appliesToTrackIds": []
          },
          {
            "code": "HTM535",
            "name": "Hospitality & Tourism Financial Management",
            "credits": 3,
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
            "appliesToTrackIds": []
          },
          {
            "code": "HTM582",
            "name": "Research Methods",
            "credits": 3,
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
            "appliesToTrackIds": []
          }
        ]
      },
      {
        "id": "award-path-specialisation",
        "name": "Award Path Specialisation Subjects",
        "type": "track_core",
        "creditsRequiredByTrackIds": {
          "POLYU-TPG-102-AIH": 12,
          "POLYU-TPG-102-IEH": 12,
          "POLYU-TPG-102-IHM": 12,
          "POLYU-TPG-102-IWM": 9
        },
        "coursesRequiredByTrackIds": {
          "POLYU-TPG-102-AIH": 4,
          "POLYU-TPG-102-IEH": 4,
          "POLYU-TPG-102-IHM": 4,
          "POLYU-TPG-102-IWM": 3
        },
        "ruleText": "AIH, IEH and IHM each complete their four listed specialisation subjects. ITEM completes HTM520, HTM544, HTM545 and HTM561. LEM completes HTM541 and HTM574-HTM576. IWM completes HTM554-HTM556. The three cross-listed subjects are stored separately to avoid duplicate course codes.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
        "courses": [
          {
            "code": "HTM592",
            "name": "AI for Hospitality: Foundations, Applications, and Ethics",
            "credits": 3,
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
            "appliesToTrackIds": [
              "POLYU-TPG-102-AIH"
            ],
            "countsTowardTrackIds": [
              "POLYU-TPG-102-AIH"
            ],
            "subjectGroups": [
              "specialisation"
            ]
          },
          {
            "code": "HTM593",
            "name": "Machine Learning and Emerging Technologies in Hospitality",
            "credits": 3,
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
            "appliesToTrackIds": [
              "POLYU-TPG-102-AIH"
            ],
            "countsTowardTrackIds": [
              "POLYU-TPG-102-AIH"
            ],
            "subjectGroups": [
              "specialisation"
            ]
          },
          {
            "code": "HTM594",
            "name": "Big Data Analytics and Intelligence in Hospitality",
            "credits": 3,
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
            "appliesToTrackIds": [
              "POLYU-TPG-102-AIH"
            ],
            "countsTowardTrackIds": [
              "POLYU-TPG-102-AIH"
            ],
            "subjectGroups": [
              "specialisation"
            ]
          },
          {
            "code": "HTM595",
            "name": "AI-Powered Service Design for Hospitality",
            "credits": 3,
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
            "appliesToTrackIds": [
              "POLYU-TPG-102-AIH"
            ],
            "countsTowardTrackIds": [
              "POLYU-TPG-102-AIH"
            ],
            "subjectGroups": [
              "specialisation"
            ]
          },
          {
            "code": "HTM569",
            "name": "Innovation and Entrepreneurship in Hospitality Industry",
            "credits": 3,
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
            "appliesToTrackIds": [
              "POLYU-TPG-102-IEH"
            ],
            "countsTowardTrackIds": [
              "POLYU-TPG-102-IEH"
            ],
            "subjectGroups": [
              "specialisation"
            ]
          },
          {
            "code": "HTM570",
            "name": "Innovative Experience Design",
            "credits": 3,
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
            "appliesToTrackIds": [
              "POLYU-TPG-102-IEH"
            ],
            "countsTowardTrackIds": [
              "POLYU-TPG-102-IEH"
            ],
            "subjectGroups": [
              "specialisation"
            ]
          },
          {
            "code": "HTM571",
            "name": "Business Models in Hospitality Entrepreneurship",
            "credits": 3,
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
            "appliesToTrackIds": [
              "POLYU-TPG-102-IEH"
            ],
            "countsTowardTrackIds": [
              "POLYU-TPG-102-IEH"
            ],
            "subjectGroups": [
              "specialisation"
            ]
          },
          {
            "code": "HTM572",
            "name": "Innovation in Hospitality in the Digital Age",
            "credits": 3,
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
            "appliesToTrackIds": [
              "POLYU-TPG-102-IEH"
            ],
            "countsTowardTrackIds": [
              "POLYU-TPG-102-IEH"
            ],
            "subjectGroups": [
              "specialisation"
            ]
          },
          {
            "code": "HTM536",
            "name": "Strategic Management for Hospitality Businesses",
            "credits": 3,
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
            "appliesToTrackIds": [
              "POLYU-TPG-102-IHM"
            ],
            "countsTowardTrackIds": [
              "POLYU-TPG-102-IHM"
            ],
            "subjectGroups": [
              "specialisation"
            ]
          },
          {
            "code": "HTM537",
            "name": "Design for Hospitality",
            "credits": 3,
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
            "appliesToTrackIds": [
              "POLYU-TPG-102-IHM"
            ],
            "countsTowardTrackIds": [
              "POLYU-TPG-102-IHM"
            ],
            "subjectGroups": [
              "specialisation"
            ]
          },
          {
            "code": "HTM538",
            "name": "Multi-Unit Hospitality Management",
            "credits": 3,
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
            "appliesToTrackIds": [
              "POLYU-TPG-102-IHM"
            ],
            "countsTowardTrackIds": [
              "POLYU-TPG-102-IHM"
            ],
            "subjectGroups": [
              "specialisation"
            ]
          },
          {
            "code": "HTM539",
            "name": "Hospitality Revenue Management",
            "credits": 3,
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
            "appliesToTrackIds": [
              "POLYU-TPG-102-IHM"
            ],
            "countsTowardTrackIds": [
              "POLYU-TPG-102-IHM"
            ],
            "subjectGroups": [
              "specialisation"
            ]
          },
          {
            "code": "HTM544",
            "name": "Strategic Management for Travel and Tourism Businesses",
            "credits": 3,
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
            "appliesToTrackIds": [
              "POLYU-TPG-102-ITEM"
            ],
            "countsTowardTrackIds": [
              "POLYU-TPG-102-ITEM"
            ],
            "subjectGroups": [
              "specialisation"
            ]
          },
          {
            "code": "HTM545",
            "name": "Tourism Policy and Development",
            "credits": 3,
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
            "appliesToTrackIds": [
              "POLYU-TPG-102-ITEM"
            ],
            "countsTowardTrackIds": [
              "POLYU-TPG-102-ITEM"
            ],
            "subjectGroups": [
              "specialisation"
            ]
          },
          {
            "code": "HTM574",
            "name": "Luxury Consumption Experience and Communication",
            "credits": 3,
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
            "appliesToTrackIds": [
              "POLYU-TPG-102-LEM"
            ],
            "countsTowardTrackIds": [
              "POLYU-TPG-102-LEM"
            ],
            "subjectGroups": [
              "specialisation"
            ]
          },
          {
            "code": "HTM575",
            "name": "Sustainable Luxury and Design",
            "credits": 3,
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
            "appliesToTrackIds": [
              "POLYU-TPG-102-LEM"
            ],
            "countsTowardTrackIds": [
              "POLYU-TPG-102-LEM"
            ],
            "subjectGroups": [
              "specialisation"
            ]
          },
          {
            "code": "HTM576",
            "name": "Luxury Service Management in Asia",
            "credits": 3,
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
            "appliesToTrackIds": [
              "POLYU-TPG-102-LEM"
            ],
            "countsTowardTrackIds": [
              "POLYU-TPG-102-LEM"
            ],
            "subjectGroups": [
              "specialisation"
            ]
          },
          {
            "code": "HTM554",
            "name": "Viticulture and Oenology",
            "credits": 3,
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
            "appliesToTrackIds": [
              "POLYU-TPG-102-IWM"
            ],
            "countsTowardTrackIds": [
              "POLYU-TPG-102-IWM"
            ],
            "subjectGroups": [
              "specialisation"
            ]
          },
          {
            "code": "HTM555",
            "name": "Wine Business Environment",
            "credits": 3,
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
            "appliesToTrackIds": [
              "POLYU-TPG-102-IWM"
            ],
            "countsTowardTrackIds": [
              "POLYU-TPG-102-IWM"
            ],
            "subjectGroups": [
              "specialisation"
            ]
          },
          {
            "code": "HTM556",
            "name": "Wines of the World",
            "credits": 3,
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
            "appliesToTrackIds": [
              "POLYU-TPG-102-IWM"
            ],
            "countsTowardTrackIds": [
              "POLYU-TPG-102-IWM"
            ],
            "subjectGroups": [
              "specialisation"
            ]
          }
        ]
      },
      {
        "id": "cross-listed-specialisation-electives",
        "name": "Cross-listed Specialisation and Elective Subjects",
        "type": "elective",
        "ruleText": "HTM520 and HTM561 are ITEM specialisation subjects and IWM electives. HTM541 is a LEM specialisation subject and an elective for the other award paths. These roles must be checked by award path and must not be double counted.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
        "courses": [
          {
            "code": "HTM520",
            "name": "Meetings and Exhibition Management",
            "credits": 3,
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
            "appliesToTrackIds": [
              "POLYU-TPG-102-ITEM",
              "POLYU-TPG-102-IWM"
            ],
            "countsTowardTrackIds": [
              "POLYU-TPG-102-ITEM"
            ],
            "subjectGroups": [
              "specialisation",
              "elective"
            ]
          },
          {
            "code": "HTM561",
            "name": "Business Events: Concepts, Issues and Trends",
            "credits": 3,
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
            "appliesToTrackIds": [
              "POLYU-TPG-102-ITEM",
              "POLYU-TPG-102-IWM"
            ],
            "countsTowardTrackIds": [
              "POLYU-TPG-102-ITEM"
            ],
            "subjectGroups": [
              "specialisation",
              "elective"
            ]
          },
          {
            "code": "HTM541",
            "name": "Luxury Management",
            "credits": 3,
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
            "appliesToTrackIds": [
              "POLYU-TPG-102-AIH",
              "POLYU-TPG-102-IEH",
              "POLYU-TPG-102-IHM",
              "POLYU-TPG-102-ITEM",
              "POLYU-TPG-102-LEM",
              "POLYU-TPG-102-IWM"
            ],
            "countsTowardTrackIds": [
              "POLYU-TPG-102-LEM"
            ],
            "subjectGroups": [
              "specialisation",
              "elective"
            ]
          }
        ]
      },
      {
        "id": "project-options",
        "name": "Research or Consultancy Project Option",
        "type": "project",
        "coursesRequired": 1,
        "ruleText": "Choose HTM599 Research Project (6 credits) for the Research Component, or HTM598 Consultancy Project (3 credits) for the Non-Research Component. The paired elective requirement differs by award path and component and requires manual audit review.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
        "courses": [
          {
            "code": "HTM598",
            "name": "Consultancy Project",
            "credits": 3,
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
            "appliesToTrackIds": [],
            "courseKind": "project",
            "conditionalRequirement": true
          },
          {
            "code": "HTM599",
            "name": "Research Project",
            "credits": 6,
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
            "appliesToTrackIds": [],
            "courseKind": "research_project",
            "conditionalRequirement": true
          }
        ]
      },
      {
        "id": "elective-pool",
        "name": "Elective Subject Pool",
        "type": "elective",
        "ruleText": "For AIH, IEH, IHM, ITEM and LEM, the Non-Research Component pairs HTM598 with one 3-credit elective; the Research Component uses HTM599 without an elective. For IWM, the Research Component requires two electives and HTM599, while the Non-Research Component requires three electives and HTM598. Cross-listed HTM520, HTM541 and HTM561 are stored in the separate cross-listed group.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
        "courses": [
          {
            "code": "HTM507",
            "name": "Cultural Tourism",
            "credits": 3,
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
            "appliesToTrackIds": [
              "POLYU-TPG-102-AIH",
              "POLYU-TPG-102-IEH",
              "POLYU-TPG-102-IHM",
              "POLYU-TPG-102-ITEM",
              "POLYU-TPG-102-LEM"
            ]
          },
          {
            "code": "HTM513",
            "name": "China Hotel and Tourism Business Studies",
            "credits": 3,
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
            "appliesToTrackIds": [
              "POLYU-TPG-102-AIH",
              "POLYU-TPG-102-IEH",
              "POLYU-TPG-102-IHM",
              "POLYU-TPG-102-ITEM",
              "POLYU-TPG-102-LEM"
            ]
          },
          {
            "code": "HTM528",
            "name": "Trends and Issues in Global Tourism",
            "credits": 3,
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
            "appliesToTrackIds": [
              "POLYU-TPG-102-AIH",
              "POLYU-TPG-102-IEH",
              "POLYU-TPG-102-IHM",
              "POLYU-TPG-102-ITEM",
              "POLYU-TPG-102-LEM"
            ]
          },
          {
            "code": "HTM568",
            "name": "Smart Tourism and Big Data Analytics",
            "credits": 3,
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
            "appliesToTrackIds": [
              "POLYU-TPG-102-AIH",
              "POLYU-TPG-102-IEH",
              "POLYU-TPG-102-IHM",
              "POLYU-TPG-102-ITEM",
              "POLYU-TPG-102-LEM"
            ]
          },
          {
            "code": "HTM573",
            "name": "Business Development and Branding",
            "credits": 3,
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
            "appliesToTrackIds": [
              "POLYU-TPG-102-AIH",
              "POLYU-TPG-102-IEH",
              "POLYU-TPG-102-IHM",
              "POLYU-TPG-102-ITEM",
              "POLYU-TPG-102-LEM"
            ]
          },
          {
            "code": "HTM577",
            "name": "Luxury Service Management in Practice (including residential workshop)",
            "credits": 3,
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
            "appliesToTrackIds": [
              "POLYU-TPG-102-AIH",
              "POLYU-TPG-102-IEH",
              "POLYU-TPG-102-IHM",
              "POLYU-TPG-102-ITEM",
              "POLYU-TPG-102-LEM"
            ]
          },
          {
            "code": "HTM540",
            "name": "Hospitality and Tourism Technology and Innovation",
            "credits": 3,
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
            "appliesToTrackIds": [
              "POLYU-TPG-102-AIH",
              "POLYU-TPG-102-IEH",
              "POLYU-TPG-102-IHM",
              "POLYU-TPG-102-ITEM",
              "POLYU-TPG-102-LEM",
              "POLYU-TPG-102-IWM"
            ]
          },
          {
            "code": "HTM557",
            "name": "Residential Study Trip",
            "credits": 3,
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
            "appliesToTrackIds": [
              "POLYU-TPG-102-AIH",
              "POLYU-TPG-102-IEH",
              "POLYU-TPG-102-IHM",
              "POLYU-TPG-102-ITEM",
              "POLYU-TPG-102-LEM",
              "POLYU-TPG-102-IWM"
            ]
          },
          {
            "code": "HTM558",
            "name": "Brand Management and Communication in Wine Business",
            "credits": 3,
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
            "appliesToTrackIds": [
              "POLYU-TPG-102-IWM"
            ]
          },
          {
            "code": "HTM560",
            "name": "Wine Economics",
            "credits": 3,
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
            "appliesToTrackIds": [
              "POLYU-TPG-102-IWM"
            ]
          }
        ]
      },
      {
        "id": "optional-non-credit",
        "name": "Optional Non-credit Subject",
        "type": "optional",
        "ruleText": "HTM5003 Management Practice is an optional, non-credit-bearing internship and is not part of the 32-credit graduation total.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
        "courses": [
          {
            "code": "HTM5003",
            "name": "Management Practice",
            "credits": 0,
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/24045-maf-paf-map-pap-mhf-phf-mhp-php-mvf-pvf-mvp-pvp-mwf-pwf-mwp-pwp-mlf-plf-mlp-plp",
            "appliesToTrackIds": []
          }
        ]
      }
    ]
  },
  {
    "id": "POLYU-TPG-105",
    "courseGroups": [
      {
        "id": "compulsory",
        "name": "Compulsory Subjects",
        "type": "core",
        "creditsRequired": 15,
        "coursesRequired": 5,
        "ruleText": "Complete all five Compulsory Subjects.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/52049-ftm-ptm",
        "courses": [
          {
            "code": "SO5001",
            "name": "Digital Health: Transforming Healthcare through Technology",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/52049-ftm-ptm"
          },
          {
            "code": "SO5002",
            "name": "Adaptive Technology in Vision Science",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/52049-ftm-ptm"
          },
          {
            "code": "SO5003",
            "name": "Entrepreneurship in Ophthalmic Industry",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/52049-ftm-ptm"
          },
          {
            "code": "SO5004",
            "name": "Principle and Practice of Ophthalmic Health Care",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/52049-ftm-ptm"
          },
          {
            "code": "SO5005",
            "name": "Quantitative and Qualitative Research Methods",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/52049-ftm-ptm"
          }
        ]
      },
      {
        "id": "elective",
        "name": "Elective Subjects",
        "type": "elective",
        "creditsRequired": 9,
        "coursesRequired": 3,
        "ruleText": "Choose three Elective Subjects according to the student's background.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/52049-ftm-ptm",
        "courses": [
          {
            "code": "SO5006",
            "name": "Advanced Vision Science",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/52049-ftm-ptm"
          },
          {
            "code": "SO5008",
            "name": "Cutting-edge Investigations in Eye and Biomedical Research",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/52049-ftm-ptm"
          },
          {
            "code": "SO6006",
            "name": "Visual Neuroscience",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/52049-ftm-ptm"
          },
          {
            "code": "SO5009",
            "name": "Contemporary Myopia Control and Management",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/52049-ftm-ptm"
          },
          {
            "code": "BME5150",
            "name": "Medical Artificial Intelligence and Data Analytics",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/52049-ftm-ptm"
          },
          {
            "code": "COMP5511",
            "name": "Artificial Intelligence Concept",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/52049-ftm-ptm"
          },
          {
            "code": "COMP5517",
            "name": "Human Computer Interface",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/52049-ftm-ptm"
          },
          {
            "code": "COMP5523",
            "name": "Computer Vision and Image Processing",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/52049-ftm-ptm"
          },
          {
            "code": "COMP5554",
            "name": "Advanced Artificial Intelligence",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/52049-ftm-ptm"
          },
          {
            "code": "HTI5052",
            "name": "Bioinformatics in Health Sciences",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/52049-ftm-ptm"
          },
          {
            "code": "SD5116",
            "name": "Design for Transformation",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/52049-ftm-ptm"
          },
          {
            "code": "SD5132",
            "name": "Lab Studies in Human Cyber-Physical Systems",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/52049-ftm-ptm"
          },
          {
            "code": "SD5414",
            "name": "Systemic Innovation and Designing Future Services",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/52049-ftm-ptm"
          }
        ]
      },
      {
        "id": "research-project",
        "name": "Research Project",
        "type": "project",
        "creditsRequired": 6,
        "coursesRequired": 1,
        "ruleText": "Complete the Research Project.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/52049-ftm-ptm",
        "courses": [
          {
            "code": "SO5100",
            "name": "Research Project",
            "credits": 6,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/52049-ftm-ptm"
          }
        ]
      },
      {
        "id": "academic-integrity",
        "name": "Academic Integrity and Ethics",
        "type": "academic_integrity",
        "creditsRequired": 1,
        "coursesRequired": 1,
        "ruleText": "Complete the compulsory AIE subject.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/52049-ftm-ptm",
        "courses": [
          {
            "code": "HTI5T04",
            "name": "Academic Integrity and Ethics (Health and Social Sciences)",
            "credits": 1,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.polyu.edu.hk/study/pg/tpg/2027/52049-ftm-ptm"
          }
        ]
      }
    ]
  }
];
