// Generated by npm run sync:tpg. Do not edit manually.
module.exports = [
  {
    "id": "LINGNAN-TPG-DIR-16-000936-L6",
    "courseGroups": [
      {
        "id": "required-courses",
        "name": "Required Courses",
        "type": "core",
        "creditsRequired": 15,
        "coursesRequired": 5,
        "ruleText": "Complete all five Required Courses (15 credits).",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.ln.edu.hk/psy/mwop/programme-overview/programme-structure",
        "courses": [
          {
            "code": "PSY511",
            "name": "Psychology & Work Today: An Introduction to Work Psychology",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/psy/mwop/programme-overview/course-descriptions"
          },
          {
            "code": "PSY512",
            "name": "Personnel Psychology",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/psy/mwop/programme-overview/course-descriptions"
          },
          {
            "code": "PSY513",
            "name": "Organisational Psychology",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/psy/mwop/programme-overview/course-descriptions"
          },
          {
            "code": "PSY514",
            "name": "Occupational Health Psychology",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/psy/mwop/programme-overview/course-descriptions"
          },
          {
            "code": "PSY515",
            "name": "Research Methods in Work Psychology",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/psy/mwop/programme-overview/course-descriptions"
          }
        ]
      },
      {
        "id": "elective-courses",
        "name": "Elective Courses",
        "type": "elective",
        "creditsRequired": 15,
        "coursesRequired": 5,
        "ruleText": "Choose any five Elective Courses (15 credits). PSY609 applies to students admitted from 2024-25 onward, and PSY613 applies to students admitted from 2025-26 onward. Elective offerings are subject to sufficient demand and faculty availability.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.ln.edu.hk/psy/mwop/programme-overview/programme-structure",
        "courses": [
          {
            "code": "PSY601",
            "name": "The Psychology of IT at Work",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/psy/mwop/programme-overview/course-descriptions"
          },
          {
            "code": "PSY602",
            "name": "Human Relationship and Interpersonal Skills in Organisations",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/psy/mwop/programme-overview/course-descriptions"
          },
          {
            "code": "PSY603",
            "name": "Seminar on Selected Issues in Work and Organisational Psychology",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/psy/mwop/programme-overview/course-descriptions"
          },
          {
            "code": "PSY604",
            "name": "Consumer Psychology",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/psy/mwop/programme-overview/course-descriptions"
          },
          {
            "code": "PSY605",
            "name": "Coaching and Counselling in the Workplace",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/psy/mwop/programme-overview/course-descriptions"
          },
          {
            "code": "PSY606",
            "name": "Applied Positive Psychology at Work",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/psy/mwop/programme-overview/course-descriptions"
          },
          {
            "code": "PSY607",
            "name": "Social Problem Solving and Decision Making in the Modern World",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/psy/mwop/programme-overview/course-descriptions"
          },
          {
            "code": "PSY608",
            "name": "Guided Research",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/psy/mwop/programme-overview/course-descriptions"
          },
          {
            "code": "PSY609",
            "name": "Workplace Diversity and Inclusion",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/psy/mwop/programme-overview/course-descriptions"
          },
          {
            "code": "PSY613",
            "name": "Principles of Psychological Assessment",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/psy/mwop/programme-overview/course-descriptions"
          }
        ]
      }
    ]
  },
  {
    "id": "LINGNAN-TPG-DIR-17-000204-L6",
    "courseGroups": [
      {
        "id": "core-courses",
        "name": "Core Courses",
        "type": "core",
        "creditsRequired": 15,
        "coursesRequired": 5,
        "ruleText": "Complete all five Core Courses (15 credits) under the mother Programme and both Concentrations.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.ln.edu.hk/socsp/imcsp/programme-overview/programme-structure",
        "courses": [
          {
            "code": "SOC501",
            "name": "Social Policy Analysis: Comparative Perspectives",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/socsp/imcsp/programme-overview/programme-structure"
          },
          {
            "code": "SOC504",
            "name": "Comparative Social Policy in Greater China and East Asia",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/socsp/imcsp/programme-overview/programme-structure"
          },
          {
            "code": "SOC505",
            "name": "Globalisation, Policy and Society",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/socsp/imcsp/programme-overview/programme-structure"
          },
          {
            "code": "SOC506",
            "name": "Policy Research and Evaluation Design",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/socsp/imcsp/programme-overview/programme-structure"
          },
          {
            "code": "SOC604",
            "name": "Comparative Social Policy Symposium",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/socsp/imcsp/programme-overview/programme-structure"
          }
        ]
      },
      {
        "id": "parent-required-course",
        "name": "Mother Programme Required Course",
        "type": "core",
        "creditsRequired": 3,
        "coursesRequired": 1,
        "ruleText": "Students who do not declare a Concentration complete SOC601 (3 credits). This course is not part of either Concentration path.",
        "appliesToTrackIds": [],
        "excludesTrackIds": [
          "LINGNAN-TPG-DIR-17-000204-L6-25-000017-L6",
          "LINGNAN-TPG-DIR-17-000204-L6-25-000023-L6"
        ],
        "sourceUrl": "https://www.ln.edu.hk/socsp/imcsp/programme-overview/programme-structure",
        "courses": [
          {
            "code": "SOC601",
            "name": "Governance, Management and Delivery",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/socsp/imcsp/programme-overview/programme-structure"
          }
        ]
      },
      {
        "id": "pathway-courses",
        "name": "Elective and Concentration Courses",
        "type": "elective",
        "creditsRequired": 6,
        "coursesRequired": 2,
        "creditsRequiredByTrackIds": {
          "LINGNAN-TPG-DIR-17-000204-L6-25-000017-L6": 9,
          "LINGNAN-TPG-DIR-17-000204-L6-25-000023-L6": 9
        },
        "coursesRequiredByTrackIds": {
          "LINGNAN-TPG-DIR-17-000204-L6-25-000017-L6": 3,
          "LINGNAN-TPG-DIR-17-000204-L6-25-000023-L6": 3
        },
        "ruleText": "The mother Programme selects any two courses from the six-course pool (6 credits). The Social Research Concentration completes SOC606, SOC607 and SOC608 (9 credits). The Social Innovation Concentration completes SOC609, SOC610 and SOC602 (9 credits).",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.ln.edu.hk/socsp/imcsp/programme-overview/programme-structure",
        "courses": [
          {
            "code": "SOC606",
            "name": "Comparative Social Indicators and Research Methods",
            "credits": 3,
            "appliesToTrackIds": [],
            "excludesTrackIds": [
              "LINGNAN-TPG-DIR-17-000204-L6-25-000017-L6"
            ],
            "countsTowardTrackIds": [
              "LINGNAN-TPG-DIR-17-000204-L6-25-000023-L6"
            ],
            "sourceUrl": "https://www.ln.edu.hk/socsp/imcsp/programme-overview/programme-structure"
          },
          {
            "code": "SOC607",
            "name": "Applied Survey Methodology",
            "credits": 3,
            "appliesToTrackIds": [],
            "excludesTrackIds": [
              "LINGNAN-TPG-DIR-17-000204-L6-25-000017-L6"
            ],
            "countsTowardTrackIds": [
              "LINGNAN-TPG-DIR-17-000204-L6-25-000023-L6"
            ],
            "sourceUrl": "https://www.ln.edu.hk/socsp/imcsp/programme-overview/programme-structure"
          },
          {
            "code": "SOC608",
            "name": "Qualitative Methods for Policy Analysis",
            "credits": 3,
            "appliesToTrackIds": [],
            "excludesTrackIds": [
              "LINGNAN-TPG-DIR-17-000204-L6-25-000017-L6"
            ],
            "countsTowardTrackIds": [
              "LINGNAN-TPG-DIR-17-000204-L6-25-000023-L6"
            ],
            "sourceUrl": "https://www.ln.edu.hk/socsp/imcsp/programme-overview/programme-structure"
          },
          {
            "code": "SOC609",
            "name": "Social Entrepreneurship & Social Impact",
            "credits": 3,
            "appliesToTrackIds": [],
            "excludesTrackIds": [
              "LINGNAN-TPG-DIR-17-000204-L6-25-000023-L6"
            ],
            "countsTowardTrackIds": [
              "LINGNAN-TPG-DIR-17-000204-L6-25-000017-L6"
            ],
            "sourceUrl": "https://www.ln.edu.hk/socsp/imcsp/programme-overview/programme-structure"
          },
          {
            "code": "SOC610",
            "name": "Non-Profit Organisations & the Voluntary Sector",
            "credits": 3,
            "appliesToTrackIds": [],
            "excludesTrackIds": [
              "LINGNAN-TPG-DIR-17-000204-L6-25-000023-L6"
            ],
            "countsTowardTrackIds": [
              "LINGNAN-TPG-DIR-17-000204-L6-25-000017-L6"
            ],
            "sourceUrl": "https://www.ln.edu.hk/socsp/imcsp/programme-overview/programme-structure"
          },
          {
            "code": "SOC602",
            "name": "Dialogue with Policy Practitioners: Theory and Practice",
            "credits": 3,
            "appliesToTrackIds": [],
            "excludesTrackIds": [
              "LINGNAN-TPG-DIR-17-000204-L6-25-000023-L6"
            ],
            "countsTowardTrackIds": [
              "LINGNAN-TPG-DIR-17-000204-L6-25-000017-L6"
            ],
            "sourceUrl": "https://www.ln.edu.hk/socsp/imcsp/programme-overview/programme-structure"
          }
        ]
      },
      {
        "id": "capstone-project",
        "name": "Capstone Project",
        "type": "project",
        "creditsRequired": 6,
        "coursesRequired": 1,
        "ruleText": "Complete SOC605 Comparative Social Policy Research Project (6 credits) under the mother Programme and both Concentrations.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.ln.edu.hk/socsp/imcsp/programme-overview/programme-structure",
        "courses": [
          {
            "code": "SOC605",
            "name": "Comparative Social Policy Research Project",
            "credits": 6,
            "courseKind": "project",
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/socsp/imcsp/programme-overview/programme-structure"
          }
        ]
      }
    ]
  },
  {
    "id": "LINGNAN-TPG-DIR-17-000487-L6",
    "courseGroups": [
      {
        "id": "core-courses",
        "name": "Core Courses",
        "type": "core",
        "creditsRequired": 18,
        "coursesRequired": 6,
        "ruleText": "Complete all six Core Courses (18 credits) under both the mother Programme and the EdTech Concentration.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.ln.edu.hk/sgs/ihem/programme-overview/programme-structure",
        "courses": [
          {
            "code": "MIH501",
            "name": "Globalisation, Policy and Society",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sgs/ihem/programme-overview/programme-structure"
          },
          {
            "code": "MIH502",
            "name": "Comparative Social Policy Research Methods",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sgs/ihem/programme-overview/programme-structure"
          },
          {
            "code": "MIH504",
            "name": "Internationalisation and Quality Management in Higher Education",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sgs/ihem/programme-overview/programme-structure"
          },
          {
            "code": "MIH601",
            "name": "Internationalising Education: Institutional Strategy and Development",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sgs/ihem/programme-overview/programme-structure"
          },
          {
            "code": "MIH602",
            "name": "Postgraduate Studies Seminar Series",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sgs/ihem/programme-overview/programme-structure"
          },
          {
            "code": "MIH605",
            "name": "Managing Talents and Finance in Education Institutions",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sgs/ihem/programme-overview/programme-structure"
          }
        ]
      },
      {
        "id": "elective-courses",
        "name": "Elective Courses",
        "type": "elective",
        "creditsRequired": 6,
        "coursesRequired": 2,
        "creditsRequiredByTrackIds": {
          "LINGNAN-TPG-DIR-17-000487-L6-24-000294-L6": 3
        },
        "coursesRequiredByTrackIds": {
          "LINGNAN-TPG-DIR-17-000487-L6-24-000294-L6": 1
        },
        "ruleText": "The mother Programme selects two Elective Courses (6 credits). The EdTech Concentration selects one course from the same pool (3 credits). Elective offerings are subject to student demand and faculty availability.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.ln.edu.hk/sgs/ihem/programme-overview/programme-structure",
        "courses": [
          {
            "code": "MIH506",
            "name": "Branding and Marketing of Education",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sgs/ihem/programme-overview/programme-structure"
          },
          {
            "code": "MIH509",
            "name": "Global Study on Education Management in Greater China and Beyond",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sgs/ihem/programme-overview/programme-structure"
          },
          {
            "code": "MIH603",
            "name": "Cases and Workshop for Management Issues in Education",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sgs/ihem/programme-overview/programme-structure"
          },
          {
            "code": "MIH611",
            "name": "Generative AI in Education: Applications and Challenges",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sgs/ihem/programme-overview/programme-structure"
          },
          {
            "code": "MOP606",
            "name": "Fostering Interculturality through Intercultural Education",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sgs/ihem/programme-overview/programme-structure"
          },
          {
            "code": "CRS512",
            "name": "Evolution of Early Childhood Education in China and the World",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sgs/ihem/programme-overview/programme-structure"
          },
          {
            "code": "PSY619",
            "name": "Educational Psychology: Theory and Practice",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sgs/ihem/programme-overview/programme-structure"
          }
        ]
      },
      {
        "id": "edtech-concentration-courses",
        "name": "EdTech Concentration Courses",
        "type": "concentration",
        "creditsRequired": 9,
        "coursesRequired": 3,
        "ruleText": "Students in the EdTech Concentration complete all three Concentration Courses (9 credits).",
        "appliesToTrackIds": [
          "LINGNAN-TPG-DIR-17-000487-L6-24-000294-L6"
        ],
        "sourceUrl": "https://www.ln.edu.hk/sgs/ihem/programme-overview/programme-structure",
        "courses": [
          {
            "code": "MIH620",
            "name": "Education Technology Policy Analysis and Management at Macro Level",
            "credits": 3,
            "appliesToTrackIds": [
              "LINGNAN-TPG-DIR-17-000487-L6-24-000294-L6"
            ],
            "sourceUrl": "https://www.ln.edu.hk/sgs/ihem/programme-overview/programme-structure"
          },
          {
            "code": "MIH621",
            "name": "Leading and Implementing EdTech Policy at the School Level",
            "credits": 3,
            "appliesToTrackIds": [
              "LINGNAN-TPG-DIR-17-000487-L6-24-000294-L6"
            ],
            "sourceUrl": "https://www.ln.edu.hk/sgs/ihem/programme-overview/programme-structure"
          },
          {
            "code": "MIH622",
            "name": "Innovative EdTech Practices for Classroom Teaching and Learning",
            "credits": 3,
            "appliesToTrackIds": [
              "LINGNAN-TPG-DIR-17-000487-L6-24-000294-L6"
            ],
            "sourceUrl": "https://www.ln.edu.hk/sgs/ihem/programme-overview/programme-structure"
          }
        ]
      },
      {
        "id": "capstone-course",
        "name": "Capstone Course",
        "type": "project",
        "creditsRequired": 6,
        "coursesRequired": 1,
        "ruleText": "Students in the mother Programme complete MIH606 (6 credits). This Capstone Course is not part of the EdTech Concentration path.",
        "appliesToTrackIds": [],
        "excludesTrackIds": [
          "LINGNAN-TPG-DIR-17-000487-L6-24-000294-L6"
        ],
        "sourceUrl": "https://www.ln.edu.hk/sgs/ihem/programme-overview/programme-structure",
        "courses": [
          {
            "code": "MIH606",
            "name": "Capstone Project in International Higher Education and Management",
            "credits": 6,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sgs/ihem/programme-overview/programme-structure"
          }
        ]
      }
    ]
  },
  {
    "id": "LINGNAN-TPG-DIR-19-000062-L6",
    "courseGroups": [
      {
        "id": "required-courses",
        "name": "Required Courses",
        "type": "core",
        "creditsRequired": 12,
        "coursesRequired": 4,
        "ruleText": "Complete all four Required Courses (12 credits).",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.ln.edu.hk/psy/opem/programme-overview/programme-structure",
        "courses": [
          {
            "code": "PSY513",
            "name": "Organisational Psychology",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/psy/opem/programme-overview/course-description"
          },
          {
            "code": "PSY515",
            "name": "Research Methods in Work Psychology",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/psy/opem/programme-overview/course-description"
          },
          {
            "code": "PSY619",
            "name": "Educational Psychology: Theory and Practice",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/psy/opem/programme-overview/course-description"
          },
          {
            "code": "MOP608",
            "name": "Leadership in Educational Management",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/psy/opem/programme-overview/course-description"
          }
        ]
      },
      {
        "id": "elective-courses",
        "name": "Elective Courses (Psychology and Education Management Clusters)",
        "type": "elective",
        "creditsRequired": 18,
        "coursesRequired": null,
        "ruleText": "Complete 18 elective credits across the two official clusters, including at least 6 credits from the Psychology Cluster and at least 9 credits from the Education Management Cluster. The remaining 3 credits may come from either cluster. MOP602 carries 6 credits while the other electives carry 3 credits, so the final course count and cross-cluster combination require manual audit review. Elective courses are offered subject to sufficient demand and faculty availability.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.ln.edu.hk/psy/opem/programme-overview/programme-structure",
        "courses": [
          {
            "code": "PSY605",
            "name": "Coaching and Counselling in the Workplace",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/psy/opem/programme-overview/course-description"
          },
          {
            "code": "PSY613",
            "name": "Principles of Psychological Assessment",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/psy/opem/programme-overview/course-description"
          },
          {
            "code": "PSY618",
            "name": "Personal Growth",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/psy/opem/programme-overview/course-description"
          },
          {
            "code": "PSY514",
            "name": "Occupational Health Psychology",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/psy/opem/programme-overview/course-description"
          },
          {
            "code": "MOP607",
            "name": "Youth Mental Health: Developmental Risk and Resilience",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/psy/opem/programme-overview/course-description"
          },
          {
            "code": "MOP601",
            "name": "Regional Study on Education Management in Greater China and East Asia",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/psy/opem/programme-overview/course-description"
          },
          {
            "code": "MOP602",
            "name": "Applied Education Management Project (Term 1 & Term 2)",
            "credits": 6,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/psy/opem/programme-overview/course-description"
          },
          {
            "code": "MOP605",
            "name": "Guided Study in Education Management",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/psy/opem/programme-overview/course-description"
          },
          {
            "code": "MOP606",
            "name": "Fostering Interculturality through Intercultural Education",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/psy/opem/programme-overview/course-description"
          },
          {
            "code": "MOP609",
            "name": "Innovative Pedagogy: Frameworks & Application",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/psy/opem/programme-overview/course-description"
          },
          {
            "code": "MIH601",
            "name": "Internationalising Education: Institutional Strategy and Development",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/psy/opem/programme-overview/course-description"
          },
          {
            "code": "MIH611",
            "name": "Generative AI in Education: Applications and Challenges",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/psy/opem/programme-overview/course-description"
          },
          {
            "code": "CRS512",
            "name": "Evolution of Early Childhood Education in China and the World",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/psy/opem/programme-overview/course-description"
          }
        ]
      }
    ]
  },
  {
    "id": "LINGNAN-TPG-DIR-20-000658-L6",
    "courseGroups": [
      {
        "id": "core-courses",
        "name": "Core Courses (2026-27 intake)",
        "type": "core",
        "creditsRequired": 21,
        "coursesRequired": 7,
        "ruleText": "Effective from the 2026-27 intake, complete all seven Core Courses (21 credits). The official transition note moves CDS529 Project for Artificial Intelligence and Business Analytics from the displayed Elective table into the required course set.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscaiba/programme-overview/curriculum",
        "courses": [
          {
            "code": "CDS521",
            "name": "Foundation of Artificial Intelligence",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscaiba/programme-overview/curriculum"
          },
          {
            "code": "CDS522",
            "name": "Business Data Management",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscaiba/programme-overview/curriculum"
          },
          {
            "code": "CDS523",
            "name": "Principle of Data Analytics and Programming",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscaiba/programme-overview/curriculum"
          },
          {
            "code": "CDS524",
            "name": "Machine Learning for Business",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscaiba/programme-overview/curriculum"
          },
          {
            "code": "CDS525",
            "name": "Practical Application of Deep Learning",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscaiba/programme-overview/curriculum"
          },
          {
            "code": "CDS527",
            "name": "Big Data Analytics",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscaiba/programme-overview/curriculum"
          },
          {
            "code": "CDS529",
            "name": "Project for Artificial Intelligence and Business Analytics",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscaiba/programme-overview/curriculum"
          }
        ]
      },
      {
        "id": "elective-courses",
        "name": "Elective Courses",
        "type": "elective",
        "creditsRequired": 9,
        "coursesRequired": 3,
        "ruleText": "Choose three Elective Courses (9 credits) for the 2026-27 intake. CDS529 is excluded from this pool because the official transition note makes it required. Elective offering is subject to sufficient demand and faculty availability.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscaiba/programme-overview/curriculum",
        "courses": [
          {
            "code": "ORM505",
            "name": "Mobile Technology and Applications in eBusiness",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscaiba/programme-overview/curriculum"
          },
          {
            "code": "ORM510",
            "name": "Social Media for eBusiness",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscaiba/programme-overview/curriculum"
          },
          {
            "code": "ORM511",
            "name": "Project Management with Software",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscaiba/programme-overview/curriculum"
          },
          {
            "code": "ORM515",
            "name": "Business Decision Making with Software",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscaiba/programme-overview/curriculum"
          },
          {
            "code": "CDS526",
            "name": "Artificial Intelligence Based Optimization",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscaiba/programme-overview/curriculum"
          },
          {
            "code": "CDS528",
            "name": "Blockchain",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscaiba/programme-overview/curriculum"
          },
          {
            "code": "CDS530",
            "name": "Healthcare Analytics",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscaiba/programme-overview/curriculum"
          },
          {
            "code": "CDS531",
            "name": "Marketing Analytics and Intelligence",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscaiba/programme-overview/curriculum"
          },
          {
            "code": "CDS538",
            "name": "Cloud Computing",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscaiba/programme-overview/curriculum"
          },
          {
            "code": "CDS539",
            "name": "Natural Language Processing",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscaiba/programme-overview/curriculum"
          },
          {
            "code": "CDS540",
            "name": "Computer Vision",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscaiba/programme-overview/curriculum"
          },
          {
            "code": "CDS542",
            "name": "Data Visualization",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscaiba/programme-overview/curriculum"
          },
          {
            "code": "CDS547",
            "name": "Introduction to Large Language Models",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscaiba/programme-overview/curriculum"
          },
          {
            "code": "CDS550",
            "name": "Programming with Generative Artificial Intelligence",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscaiba/programme-overview/curriculum"
          },
          {
            "code": "CDS555",
            "name": "Agentic AI",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscaiba/programme-overview/curriculum"
          },
          {
            "code": "SCI501",
            "name": "Geospatial Intelligence for Sustainable Development",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscaiba/programme-overview/curriculum"
          }
        ]
      }
    ]
  },
  {
    "id": "LINGNAN-TPG-DIR-22-000158-L6",
    "courseGroups": [
      {
        "id": "required-courses",
        "name": "Required Courses",
        "type": "core",
        "creditsRequired": 15,
        "coursesRequired": 5,
        "ruleText": "Complete all five Required Courses (15 credits).",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.ln.edu.hk/psy/mssap/programme-overview/programme-structure",
        "courses": [
          {
            "code": "PSY501",
            "name": "Research Methods in Psychology",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/psy/mssap/programme-overview/course-descriptions"
          },
          {
            "code": "PSY502",
            "name": "Cognitive Psychology",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/psy/mssap/programme-overview/course-descriptions"
          },
          {
            "code": "PSY503",
            "name": "Lifespan Developmental Psychology",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/psy/mssap/programme-overview/course-descriptions"
          },
          {
            "code": "PSY504",
            "name": "Personality Psychology",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/psy/mssap/programme-overview/course-descriptions"
          },
          {
            "code": "PSY505",
            "name": "Social Psychology",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/psy/mssap/programme-overview/course-descriptions"
          }
        ]
      },
      {
        "id": "elective-courses",
        "name": "Elective Courses",
        "type": "elective",
        "creditsRequired": 15,
        "coursesRequired": 5,
        "ruleText": "Choose any five Elective Courses (15 credits). To declare the Counselling Psychology Concentration at graduation, all four marked counselling courses PSY611, PSY612, PSY613 and PSY614 must be included among the five electives. The concentration declaration requires manual audit review.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.ln.edu.hk/psy/mssap/programme-overview/programme-structure",
        "courses": [
          {
            "code": "PSY611",
            "name": "Theories and Models in Counselling Psychology",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "LINGNAN-TPG-DIR-22-000158-L6-23-000260-L6"
            ],
            "sourceUrl": "https://www.ln.edu.hk/psy/mssap/programme-overview/course-descriptions"
          },
          {
            "code": "PSY612",
            "name": "Psychopathology",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "LINGNAN-TPG-DIR-22-000158-L6-23-000260-L6"
            ],
            "sourceUrl": "https://www.ln.edu.hk/psy/mssap/programme-overview/course-descriptions"
          },
          {
            "code": "PSY613",
            "name": "Principles of Psychological Assessment",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "LINGNAN-TPG-DIR-22-000158-L6-23-000260-L6"
            ],
            "sourceUrl": "https://www.ln.edu.hk/psy/mssap/programme-overview/course-descriptions"
          },
          {
            "code": "PSY614",
            "name": "Interventions and Professional Ethics in Counselling",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "LINGNAN-TPG-DIR-22-000158-L6-23-000260-L6"
            ],
            "sourceUrl": "https://www.ln.edu.hk/psy/mssap/programme-overview/course-descriptions"
          },
          {
            "code": "PSY617",
            "name": "Guided Study in Psychology",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/psy/mssap/programme-overview/course-descriptions"
          },
          {
            "code": "PSY618",
            "name": "Personal Growth",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/psy/mssap/programme-overview/course-descriptions"
          },
          {
            "code": "PSY619",
            "name": "Educational Psychology: Theory and Practice",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/psy/mssap/programme-overview/course-descriptions"
          },
          {
            "code": "PSY602",
            "name": "Human Relationship and Interpersonal Skills in Organisations",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/psy/mssap/programme-overview/course-descriptions"
          },
          {
            "code": "PSY604",
            "name": "Consumer Psychology",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/psy/mssap/programme-overview/course-descriptions"
          },
          {
            "code": "PSY606",
            "name": "Applied Positive Psychology at Work",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/psy/mssap/programme-overview/course-descriptions"
          },
          {
            "code": "HAM508",
            "name": "Applied Health Psychology in Social Service Settings",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/psy/mssap/programme-overview/course-descriptions"
          },
          {
            "code": "HAM509",
            "name": "Sleep, Health, and Everyday Life",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/psy/mssap/programme-overview/course-descriptions"
          },
          {
            "code": "SAG501",
            "name": "Positive Gerontology",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/psy/mssap/programme-overview/course-descriptions"
          }
        ]
      }
    ]
  },
  {
    "id": "LINGNAN-TPG-DIR-23-000472-L6",
    "courseGroups": [
      {
        "id": "core-courses",
        "name": "Core Courses",
        "type": "core",
        "creditsRequired": 21,
        "coursesRequired": 7,
        "ruleText": "Complete all seven Core Courses (21 credits).",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.ln.edu.hk/sgs/mhpm/programme-overview/programme-structure",
        "courses": [
          {
            "code": "HPM501",
            "name": "Housing Economics and Finance",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sgs/mhpm/programme-overview/programme-structure"
          },
          {
            "code": "HPM502",
            "name": "Contemporary Issues in Housing Management",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sgs/mhpm/programme-overview/programme-structure"
          },
          {
            "code": "HPM503",
            "name": "Building Studies for Housing Management",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sgs/mhpm/programme-overview/programme-structure"
          },
          {
            "code": "HPM504",
            "name": "Facility and Asset Management",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sgs/mhpm/programme-overview/programme-structure"
          },
          {
            "code": "HPM601",
            "name": "Legal Studies for Housing Management",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sgs/mhpm/programme-overview/programme-structure"
          },
          {
            "code": "HPM602",
            "name": "Advanced Practices of Housing Management",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sgs/mhpm/programme-overview/programme-structure"
          },
          {
            "code": "MCG511",
            "name": "Housing Policy and Development",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sgs/mhpm/programme-overview/programme-structure"
          }
        ]
      },
      {
        "id": "elective-courses",
        "name": "Elective Courses",
        "type": "elective",
        "creditsRequired": 3,
        "coursesRequired": 1,
        "ruleText": "Choose one Elective Course (3 credits). CDS527 and CDS556 are added to the pool effective from the 2026-27 intake. Elective offerings are subject to University approval before the start of the academic year.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.ln.edu.hk/sgs/mhpm/programme-overview/programme-structure",
        "courses": [
          {
            "code": "MCG501",
            "name": "Cities and Social Change",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sgs/mhpm/programme-overview/programme-structure"
          },
          {
            "code": "MCG505",
            "name": "Smart and Sustainable Cities",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sgs/mhpm/programme-overview/programme-structure"
          },
          {
            "code": "CDS527",
            "name": "Big Data Analytics",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sgs/mhpm/programme-overview/programme-structure"
          },
          {
            "code": "CDS556",
            "name": "Urban Computing and Spatio-Temporal Analytics",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sgs/mhpm/programme-overview/programme-structure"
          }
        ]
      },
      {
        "id": "capstone-project",
        "name": "Capstone Project",
        "type": "project",
        "creditsRequired": 6,
        "coursesRequired": 1,
        "ruleText": "Complete HPM603 Research Methods and Capstone Project (6 credits).",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.ln.edu.hk/sgs/mhpm/programme-overview/programme-structure",
        "courses": [
          {
            "code": "HPM603",
            "name": "Research Methods and Capstone Project",
            "credits": 6,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sgs/mhpm/programme-overview/programme-structure"
          }
        ]
      }
    ]
  },
  {
    "id": "LINGNAN-TPG-DIR-24-000101-L6",
    "courseGroups": [
      {
        "id": "required-courses",
        "name": "Required Courses",
        "type": "core",
        "creditsRequired": 21,
        "coursesRequired": 7,
        "ruleText": "Complete all seven Required Courses (21 credits), including the required CDS536 Data Science Project.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscds/programme-overview/curriculum",
        "courses": [
          {
            "code": "CDS532",
            "name": "Programming for Data Science",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscds/programme-overview/curriculum"
          },
          {
            "code": "CDS533",
            "name": "Statistics for Data Science",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscds/programme-overview/curriculum"
          },
          {
            "code": "CDS534",
            "name": "Database Management",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscds/programme-overview/curriculum"
          },
          {
            "code": "CDS535",
            "name": "Data Mining",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscds/programme-overview/curriculum"
          },
          {
            "code": "CDS536",
            "name": "Data Science Project",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscds/programme-overview/curriculum"
          },
          {
            "code": "CDS521",
            "name": "Foundation of Artificial Intelligence",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscds/programme-overview/curriculum"
          },
          {
            "code": "CDS524",
            "name": "Machine Learning for Business",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscds/programme-overview/curriculum"
          }
        ]
      },
      {
        "id": "elective-courses",
        "name": "Elective Courses",
        "type": "elective",
        "creditsRequired": 9,
        "coursesRequired": 3,
        "ruleText": "Choose three Elective Courses (9 credits). Elective offering is subject to sufficient demand and division availability.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscds/programme-overview/curriculum",
        "courses": [
          {
            "code": "CDS537",
            "name": "Introduction to Cyber Security",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscds/programme-overview/curriculum"
          },
          {
            "code": "CDS538",
            "name": "Cloud Computing",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscds/programme-overview/curriculum"
          },
          {
            "code": "CDS539",
            "name": "Natural Language Processing",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscds/programme-overview/curriculum"
          },
          {
            "code": "CDS540",
            "name": "Computer Vision",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscds/programme-overview/curriculum"
          },
          {
            "code": "CDS541",
            "name": "Operations Management",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscds/programme-overview/curriculum"
          },
          {
            "code": "CDS542",
            "name": "Data Visualization",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscds/programme-overview/curriculum"
          },
          {
            "code": "CDS543",
            "name": "Social Computing",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscds/programme-overview/curriculum"
          },
          {
            "code": "CDS544",
            "name": "Mobile Edge Computing",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscds/programme-overview/curriculum"
          },
          {
            "code": "CDS515",
            "name": "Business Decision Making with Software",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscds/programme-overview/curriculum"
          },
          {
            "code": "CDS525",
            "name": "Practical Application of Deep Learning",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscds/programme-overview/curriculum"
          },
          {
            "code": "CDS527",
            "name": "Big Data Analytics",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscds/programme-overview/curriculum"
          },
          {
            "code": "CDS528",
            "name": "Blockchain",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscds/programme-overview/curriculum"
          },
          {
            "code": "CDS530",
            "name": "Healthcare Analytics",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscds/programme-overview/curriculum"
          },
          {
            "code": "SCI501",
            "name": "Geospatial Intelligence for Sustainable Development",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/sds/dai/mscds/programme-overview/curriculum"
          }
        ]
      }
    ]
  },
  {
    "id": "LINGNAN-TPG-DIR-24-000108-L6",
    "courseGroups": [
      {
        "id": "required-courses",
        "name": "Required Courses",
        "type": "core",
        "creditsRequired": 9,
        "coursesRequired": 3,
        "ruleText": "Complete all three Required Courses (9 credits).",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.ln.edu.hk/history/programmes/dhga",
        "courses": [
          {
            "code": "DHG501",
            "name": "Introduction to Digital History in Global Asia",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/history/programmes/dhga"
          },
          {
            "code": "DHG502",
            "name": "Digital Approaches in Historical Research",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/history/programmes/dhga"
          },
          {
            "code": "DHG508",
            "name": "Critical Digital History",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/history/programmes/dhga"
          }
        ]
      },
      {
        "id": "elective-courses",
        "name": "Elective Courses",
        "type": "elective",
        "creditsRequired": 15,
        "coursesRequired": 5,
        "ruleText": "Choose any five Elective Courses (15 credits).",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.ln.edu.hk/history/programmes/dhga",
        "courses": [
          {
            "code": "DHG503",
            "name": "Digital Data Management in Asian Studies",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/history/programmes/dhga"
          },
          {
            "code": "DHG504",
            "name": "Visualisation and Digital Mapping of Asian Cities",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/history/programmes/dhga"
          },
          {
            "code": "DHG505",
            "name": "Digital Public History",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/history/programmes/dhga"
          },
          {
            "code": "DHG506",
            "name": "3D Remodelling of Asian Heritage",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/history/programmes/dhga"
          },
          {
            "code": "DHG507",
            "name": "Rethinking the Historical Archive",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/history/programmes/dhga"
          },
          {
            "code": "DHG509",
            "name": "Global History of Modern East Asia",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/history/programmes/dhga"
          },
          {
            "code": "DHG510",
            "name": "Hong Kong and Global Asia",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/history/programmes/dhga"
          },
          {
            "code": "DHG511",
            "name": "Southeast Asia in the World",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/history/programmes/dhga"
          },
          {
            "code": "DHG512",
            "name": "Special Topics in History",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/history/programmes/dhga"
          }
        ]
      },
      {
        "id": "capstone-project",
        "name": "Capstone Project",
        "type": "project",
        "creditsRequired": 6,
        "coursesRequired": 1,
        "ruleText": "Complete the required DHG601 Capstone Project (6 credits).",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.ln.edu.hk/history/programmes/dhga",
        "courses": [
          {
            "code": "DHG601",
            "name": "Capstone Project",
            "credits": 6,
            "courseKind": "project",
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/history/programmes/dhga"
          }
        ]
      }
    ]
  },
  {
    "id": "LINGNAN-TPG-DIR-24-000463-L6",
    "courseGroups": [
      {
        "id": "required-courses",
        "name": "Required Courses",
        "type": "core",
        "creditsRequired": 24,
        "coursesRequired": 8,
        "ruleText": "Complete all eight Required Courses (24 credits).",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.ln.edu.hk/dos/sea/prog-overview/prog-structure",
        "courses": [
          {
            "code": "SCI501",
            "name": "Geospatial Intelligence for Sustainable Development",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/dos/sea/prog-overview/prog-structure"
          },
          {
            "code": "SCI502",
            "name": "Climate Change Literacy and Science",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/dos/sea/prog-overview/prog-structure"
          },
          {
            "code": "SCI503",
            "name": "Sustainability and Environmental Communication",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/dos/sea/prog-overview/prog-structure"
          },
          {
            "code": "SCI504",
            "name": "Urban Ecology and Sustainable Planning",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/dos/sea/prog-overview/prog-structure"
          },
          {
            "code": "SCI505",
            "name": "Introduction to Environmental, Social and Governance (ESG) Planning",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/dos/sea/prog-overview/prog-structure"
          },
          {
            "code": "SCI507",
            "name": "Data Analysis and Modelling in the R Statistical Environment for Environmental Issues",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/dos/sea/prog-overview/prog-structure"
          },
          {
            "code": "SCI508",
            "name": "Practical and Research Training: Topics in Environment, Society, and Sustainable Future",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/dos/sea/prog-overview/prog-structure"
          },
          {
            "code": "SCI509",
            "name": "Green Energy and Sustainability",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/dos/sea/prog-overview/prog-structure"
          }
        ]
      },
      {
        "id": "sustainable-city-society-elective",
        "name": "Sustainable City and Society Elective",
        "type": "elective",
        "creditsRequired": 3,
        "coursesRequired": 1,
        "ruleText": "Choose one course (3 credits) from the Sustainable City and Society Cluster.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.ln.edu.hk/dos/sea/prog-overview/prog-structure",
        "courses": [
          {
            "code": "HTI503",
            "name": "Rural Food-Energy-Water Systems (FEWS)",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/dos/sea/prog-overview/prog-structure"
          },
          {
            "code": "MCG503",
            "name": "History, Heritage and Regional Perspectives",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/dos/sea/prog-overview/prog-structure"
          },
          {
            "code": "CDS548",
            "name": "Introduction to Smart Cities",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/dos/sea/prog-overview/prog-structure"
          },
          {
            "code": "MHM504",
            "name": "Modern Technology in Health and Social Services",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/dos/sea/prog-overview/prog-structure"
          }
        ]
      },
      {
        "id": "data-analytics-elective",
        "name": "Data Analytics Elective",
        "type": "elective",
        "creditsRequired": 3,
        "coursesRequired": 1,
        "ruleText": "Choose one course (3 credits) from the Data Analytics Cluster.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.ln.edu.hk/dos/sea/prog-overview/prog-structure",
        "courses": [
          {
            "code": "CDS521",
            "name": "Foundation of Artificial Intelligence",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/dos/sea/prog-overview/prog-structure"
          },
          {
            "code": "ESG516",
            "name": "ESG and Big Data",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/dos/sea/prog-overview/prog-structure"
          },
          {
            "code": "CDS525",
            "name": "Practical Application of Deep Learning",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/dos/sea/prog-overview/prog-structure"
          },
          {
            "code": "CDS527",
            "name": "Big Data Analytics",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/dos/sea/prog-overview/prog-structure"
          },
          {
            "code": "MIB607",
            "name": "Big Data Marketing",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/dos/sea/prog-overview/prog-structure"
          }
        ]
      }
    ]
  },
  {
    "id": "LINGNAN-TPG-DIR-26-000201-L6",
    "courseGroups": [
      {
        "id": "compulsory-courses",
        "name": "Compulsory Courses",
        "type": "core",
        "creditsRequired": 24,
        "coursesRequired": 8,
        "ruleText": "Complete all eight Compulsory Courses (24 credits): five courses in Term 1 and three courses in Term 2, including the required SOC619 research project.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.ln.edu.hk/socsp/msoda/programme-overview/programme-structure",
        "courses": [
          {
            "code": "SOC611",
            "name": "Sociology in Action: Issues and Applications",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/socsp/msoda/programme-overview/programme-structure"
          },
          {
            "code": "SOC612",
            "name": "Data Analytics for Social Research",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/socsp/msoda/programme-overview/programme-structure"
          },
          {
            "code": "SOC613",
            "name": "Applied Analytical Statistics for Social Scientists",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/socsp/msoda/programme-overview/programme-structure"
          },
          {
            "code": "SOC615",
            "name": "Topical Seminars",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/socsp/msoda/programme-overview/programme-structure"
          },
          {
            "code": "SOC616",
            "name": "Social Theory in the Digital Era",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/socsp/msoda/programme-overview/programme-structure"
          },
          {
            "code": "SOC617",
            "name": "Social Networks Analysis",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/socsp/msoda/programme-overview/programme-structure"
          },
          {
            "code": "SOC618",
            "name": "Machine Learning with Social Data",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/socsp/msoda/programme-overview/programme-structure"
          },
          {
            "code": "SOC619",
            "name": "Sociology & Data Analytics Research Project",
            "credits": 3,
            "courseKind": "project",
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/socsp/msoda/programme-overview/programme-structure"
          }
        ]
      },
      {
        "id": "elective-courses",
        "name": "Elective Courses",
        "type": "elective",
        "creditsRequired": 6,
        "coursesRequired": 2,
        "ruleText": "Choose two Elective Courses (6 credits). SOC607 and SOC608 are offered by IMCSP; CDS539 and CDS542 are offered by Data Science. All electives are subject to course offering.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.ln.edu.hk/socsp/msoda/programme-overview/programme-structure",
        "courses": [
          {
            "code": "SOC607",
            "name": "Applied Survey Methodology",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/socsp/msoda/programme-overview/programme-structure"
          },
          {
            "code": "SOC608",
            "name": "Qualitative Methods for Policy Analysis",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/socsp/msoda/programme-overview/programme-structure"
          },
          {
            "code": "CDS539",
            "name": "Natural Language Processing",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/socsp/msoda/programme-overview/programme-structure"
          },
          {
            "code": "CDS542",
            "name": "Data Visualization",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.ln.edu.hk/socsp/msoda/programme-overview/programme-structure"
          }
        ]
      }
    ]
  }
];
