// Generated by npm run sync:tpg. Do not edit manually.
module.exports = [
  {
    "id": "CUHK-TPG-001",
    "courseGroups": [
      {
        "id": "required-courses",
        "name": "Required Courses",
        "type": "core",
        "creditsRequired": 6,
        "coursesRequired": 2,
        "ruleText": "Complete CHLL5600 in Term 1 of the first year and CHLL5013 in the second year (6 units in total).",
        "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/",
        "courses": [
          {
            "code": "CHLL5600",
            "name": "研究方法與論文寫作",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5013",
            "name": "講論會",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          }
        ]
      },
      {
        "id": "elective-courses",
        "name": "Elective Courses",
        "type": "elective",
        "creditsRequired": 18,
        "coursesRequired": 6,
        "ruleText": "Complete at least 18 units from the official elective pool. Individual courses may not be offered every academic year.",
        "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/",
        "courses": [
          {
            "code": "CHLL5911",
            "name": "語文學專題",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5912",
            "name": "語言學專題",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5913",
            "name": "《廣雅》與《廣雅疏證》",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5914",
            "name": "《說文解字》與現代語文學",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5915",
            "name": "粵語普通話比較研究",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5916",
            "name": "粵語語法研究",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5917",
            "name": "漢語修辭與文體研究",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5918",
            "name": "漢英比較語法專題",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5919",
            "name": "漢語構詞與句法研究",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5921",
            "name": "古代文獻專題",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5922",
            "name": "古代文獻專書",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5923",
            "name": "雜家文獻選讀：《呂氏春秋》與《淮南子》",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5924",
            "name": "《莊》、《荀》異同",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5925",
            "name": "出土文獻分類選讀",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5926",
            "name": "互見文獻與古籍研究",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5927",
            "name": "《論語》 《孟子》研究",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5928",
            "name": "資治通鑒研究",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5931",
            "name": "古典文學專題：韻文或散文",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5932",
            "name": "古典文學專題：小說或戲劇",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5933",
            "name": "古典文學專題：文學批評",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5934",
            "name": "湯顯祖與《牡丹亭》",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5935",
            "name": "古典詩歌鑒賞與批評",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5936",
            "name": "中國詩學",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5937",
            "name": "「三言」研究",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5938",
            "name": "先秦神話",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5939",
            "name": "《詩經》",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5941",
            "name": "現代文學專題",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5942",
            "name": "現代作家專題",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5943",
            "name": "現代文學批評專題",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5944",
            "name": "余光中研究",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5945",
            "name": "「創造社」研究",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5946",
            "name": "比較文學專題",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5947",
            "name": "中國新時期小說及文藝思潮",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5948",
            "name": "現代華文小說",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5949",
            "name": "中國女性文學研究",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5950",
            "name": "張愛玲研究",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5951",
            "name": "中國文化專題",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5961",
            "name": "粵語音韻與詩詞格律",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5962",
            "name": "漢語方言的比較研究",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5963",
            "name": "漢語語義與語用研究",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5981",
            "name": "宋詞",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5982",
            "name": "盛唐世界、人生、藝術——杜甫、李白、王維三家詩面面觀",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5983",
            "name": "國變與文學、文化創新：明清之際詩人詩歌研究",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5984",
            "name": "明清小說與視覺文化",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5985",
            "name": "清中期小說與文人文化",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5986",
            "name": "漢魏六朝詩選",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5987",
            "name": "陶淵明：詩歌美學與人生哲學",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5991",
            "name": "香港文學研究",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5992",
            "name": "中國三十年代小說與文藝雜誌研究",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5993",
            "name": "文藝思潮與港台電影",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          },
          {
            "code": "CHLL5994",
            "name": "中國現代文學、藝術與美育",
            "credits": 3,
            "sourceUrl": "https://www.chi.cuhk.edu.hk/study/ma-in-chinese-language-and-literature/study-scheme-and-courses/"
          }
        ]
      }
    ]
  },
  {
    "id": "CUHK-TPG-002",
    "courseGroups": [
      {
        "id": "required-course",
        "name": "Required Course",
        "type": "core",
        "creditsRequired": 3,
        "coursesRequired": 1,
        "ruleText": "Complete ENGE5010 Theoretical Linguistics (3 units).",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.eng.cuhk.edu.hk/programmes/taught-postgraduate/ma-in-english-linguistics-programme/study-scheme/",
        "courses": [
          {
            "code": "ENGE5010",
            "name": "Theoretical Linguistics",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.eng.cuhk.edu.hk/programmes/taught-postgraduate/ma-in-english-linguistics-programme/course-lists/course-list-and-descriptions/"
          }
        ]
      },
      {
        "id": "elective-courses",
        "name": "Elective Courses",
        "type": "elective_with_optional_project",
        "creditsRequired": 21,
        "ruleText": "Complete 21 units from the official elective pool. Most electives carry 3 units; ENGE5640 Research Project in Applied English Linguistics carries 6 units, requires departmental approval, a cumulative GPA of at least 3.3 and ENGE5540 in the same academic year, and may not be offered every year. Therefore the number of courses needed varies and requires manual audit review. The Research Project is optional and must not be treated as a compulsory Project.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.eng.cuhk.edu.hk/programmes/taught-postgraduate/ma-in-english-linguistics-programme/study-scheme/",
        "courses": [
          {
            "code": "ENGE5410",
            "name": "Psycholinguistics",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.eng.cuhk.edu.hk/programmes/taught-postgraduate/ma-in-english-linguistics-programme/course-lists/course-list-and-descriptions/"
          },
          {
            "code": "ENGE5420",
            "name": "Sociolinguistics",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.eng.cuhk.edu.hk/programmes/taught-postgraduate/ma-in-english-linguistics-programme/course-lists/course-list-and-descriptions/"
          },
          {
            "code": "ENGE5430",
            "name": "Second Language Acquisition",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.eng.cuhk.edu.hk/programmes/taught-postgraduate/ma-in-english-linguistics-programme/course-lists/course-list-and-descriptions/"
          },
          {
            "code": "ENGE5440",
            "name": "Language and Intercultural Communication",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.eng.cuhk.edu.hk/programmes/taught-postgraduate/ma-in-english-linguistics-programme/course-lists/course-list-and-descriptions/"
          },
          {
            "code": "ENGE5450",
            "name": "Corpus Linguistics",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.eng.cuhk.edu.hk/programmes/taught-postgraduate/ma-in-english-linguistics-programme/course-lists/course-list-and-descriptions/"
          },
          {
            "code": "ENGE5460",
            "name": "Natural Language Processing for Applied Linguistics and Education",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.eng.cuhk.edu.hk/programmes/taught-postgraduate/ma-in-english-linguistics-programme/course-lists/course-list-and-descriptions/"
          },
          {
            "code": "ENGE5520",
            "name": "Evaluation and Testing",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.eng.cuhk.edu.hk/programmes/taught-postgraduate/ma-in-english-linguistics-programme/course-lists/course-list-and-descriptions/"
          },
          {
            "code": "ENGE5540",
            "name": "Research Methods in Applied Linguistics",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.eng.cuhk.edu.hk/programmes/taught-postgraduate/ma-in-english-linguistics-programme/course-lists/course-list-and-descriptions/"
          },
          {
            "code": "ENGE5550",
            "name": "English for Specific Purposes",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.eng.cuhk.edu.hk/programmes/taught-postgraduate/ma-in-english-linguistics-programme/course-lists/course-list-and-descriptions/"
          },
          {
            "code": "ENGE5560",
            "name": "Second Language Teaching",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.eng.cuhk.edu.hk/programmes/taught-postgraduate/ma-in-english-linguistics-programme/course-lists/course-list-and-descriptions/"
          },
          {
            "code": "ENGE5570",
            "name": "Discourse and Pragmatics",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.eng.cuhk.edu.hk/programmes/taught-postgraduate/ma-in-english-linguistics-programme/course-lists/course-list-and-descriptions/"
          },
          {
            "code": "ENGE5580",
            "name": "Second Language Writing",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.eng.cuhk.edu.hk/programmes/taught-postgraduate/ma-in-english-linguistics-programme/course-lists/course-list-and-descriptions/"
          },
          {
            "code": "ENGE5590",
            "name": "Computer Applications in Second Language Teaching",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.eng.cuhk.edu.hk/programmes/taught-postgraduate/ma-in-english-linguistics-programme/course-lists/course-list-and-descriptions/"
          },
          {
            "code": "ENGE5600",
            "name": "Special Topics in Applied English Linguistics",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.eng.cuhk.edu.hk/programmes/taught-postgraduate/ma-in-english-linguistics-programme/course-lists/course-list-and-descriptions/"
          },
          {
            "code": "ENGE5610",
            "name": "Issues in Contemporary Applied English Linguistics",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.eng.cuhk.edu.hk/programmes/taught-postgraduate/ma-in-english-linguistics-programme/course-lists/course-list-and-descriptions/"
          },
          {
            "code": "ENGE5620",
            "name": "The Acquisition and Teaching of L2 Pronunciation",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.eng.cuhk.edu.hk/programmes/taught-postgraduate/ma-in-english-linguistics-programme/course-lists/course-list-and-descriptions/"
          },
          {
            "code": "ENGE5630",
            "name": "Cognitive Linguistics and Its Applications in Language Teaching",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.eng.cuhk.edu.hk/programmes/taught-postgraduate/ma-in-english-linguistics-programme/course-lists/course-list-and-descriptions/"
          },
          {
            "code": "ENGE5640",
            "name": "Research Project in Applied English Linguistics",
            "credits": 6,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.eng.cuhk.edu.hk/programmes/taught-postgraduate/ma-in-english-linguistics-programme/course-lists/course-list-and-descriptions/"
          },
          {
            "code": "ENGE5660",
            "name": "Digital Literacies: Theory, Research, and Practice",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.eng.cuhk.edu.hk/programmes/taught-postgraduate/ma-in-english-linguistics-programme/course-lists/course-list-and-descriptions/"
          },
          {
            "code": "ENGE5670",
            "name": "Language Policy and Planning (LPP)",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.eng.cuhk.edu.hk/programmes/taught-postgraduate/ma-in-english-linguistics-programme/course-lists/course-list-and-descriptions/"
          },
          {
            "code": "ENGE5680",
            "name": "Social Dimensions of Second Language Acquisition",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.eng.cuhk.edu.hk/programmes/taught-postgraduate/ma-in-english-linguistics-programme/course-lists/course-list-and-descriptions/"
          },
          {
            "code": "ENGE5690",
            "name": "Second Language Reading Research and Teaching",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.eng.cuhk.edu.hk/programmes/taught-postgraduate/ma-in-english-linguistics-programme/course-lists/course-list-and-descriptions/"
          }
        ]
      }
    ]
  },
  {
    "id": "CUHK-TPG-003",
    "courseGroups": [
      {
        "id": "required-course",
        "name": "Required Course",
        "type": "core",
        "creditsRequired": 3,
        "coursesRequired": 1,
        "ruleText": "Complete TRAN6001 Advanced Translation Studies (3 units). This course is common to the general 24-unit path and all three optional Streams.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://traserver.tra.cuhk.edu.hk/en/pro_student.php?cid=2&id=31",
        "courses": [
          {
            "code": "TRAN6001",
            "name": "Advanced Translation Studies",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-003-WRITTEN-TRANSLATION",
              "CUHK-TPG-003-INTERPRETING",
              "CUHK-TPG-003-COMPUTER-AUGMENTED-TRANSLATION"
            ],
            "sourceUrl": "https://traserver.tra.cuhk.edu.hk/en/pro_student.php?cid=2&id=31"
          }
        ]
      },
      {
        "id": "elective-course-pool",
        "name": "Elective Course Pool",
        "type": "elective_with_optional_streams",
        "creditsRequired": 21,
        "coursesRequired": 7,
        "ruleText": "Without a Stream, choose any seven courses (21 units) from the official elective pool. Written Translation Stream requires TRAN6002, TRAN6003 and TRAN6117, one of TRAN6110 or TRAN6114, and three further Stream electives. Interpreting Stream requires one course from each of the four Cantonese/English or Putonghua/English interpreting pairs (TRAN6205/6305, 6206/6306, 6207/6307 and 6208/6308) plus three further electives. Computer-augmented Translation Stream requires TRAN6601, TRAN6824 and TRAN6825, one of TRAN6821 or TRAN6823, and three further Stream electives. Students may take both courses in a stated either/or pair, but only one fulfils that pair and the other counts as an elective. Stream availability, course quotas, prerequisites and mutually exclusive language versions require manual audit review; not all electives are offered every year.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://traserver.tra.cuhk.edu.hk/en/pro_student.php?cid=2&id=31",
        "courses": [
          {
            "code": "TRAN6002",
            "name": "E-C Translation Workshop",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-003-WRITTEN-TRANSLATION",
              "CUHK-TPG-003-COMPUTER-AUGMENTED-TRANSLATION"
            ],
            "sourceUrl": "https://traserver.tra.cuhk.edu.hk/en/pro_student.php?cid=2&id=31"
          },
          {
            "code": "TRAN6003",
            "name": "C-E Translation Workshop",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-003-WRITTEN-TRANSLATION",
              "CUHK-TPG-003-COMPUTER-AUGMENTED-TRANSLATION"
            ],
            "sourceUrl": "https://traserver.tra.cuhk.edu.hk/en/pro_student.php?cid=2&id=31"
          },
          {
            "code": "TRAN6101",
            "name": "Advanced Business Translation",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-003-WRITTEN-TRANSLATION",
              "CUHK-TPG-003-INTERPRETING",
              "CUHK-TPG-003-COMPUTER-AUGMENTED-TRANSLATION"
            ],
            "sourceUrl": "https://traserver.tra.cuhk.edu.hk/en/pro_student.php?cid=2&id=31"
          },
          {
            "code": "TRAN6102",
            "name": "Financial Translation",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-003-WRITTEN-TRANSLATION",
              "CUHK-TPG-003-INTERPRETING",
              "CUHK-TPG-003-COMPUTER-AUGMENTED-TRANSLATION"
            ],
            "sourceUrl": "https://traserver.tra.cuhk.edu.hk/en/pro_student.php?cid=2&id=31"
          },
          {
            "code": "TRAN6103",
            "name": "Introduction to Legal Translation",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-003-WRITTEN-TRANSLATION",
              "CUHK-TPG-003-INTERPRETING",
              "CUHK-TPG-003-COMPUTER-AUGMENTED-TRANSLATION"
            ],
            "sourceUrl": "https://traserver.tra.cuhk.edu.hk/en/pro_student.php?cid=2&id=31"
          },
          {
            "code": "TRAN6104",
            "name": "Government & Public Affairs Translation",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-003-WRITTEN-TRANSLATION",
              "CUHK-TPG-003-INTERPRETING",
              "CUHK-TPG-003-COMPUTER-AUGMENTED-TRANSLATION"
            ],
            "sourceUrl": "https://traserver.tra.cuhk.edu.hk/en/pro_student.php?cid=2&id=31"
          },
          {
            "code": "TRAN6106",
            "name": "Translation of Public Relations Writings",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-003-WRITTEN-TRANSLATION",
              "CUHK-TPG-003-INTERPRETING",
              "CUHK-TPG-003-COMPUTER-AUGMENTED-TRANSLATION"
            ],
            "sourceUrl": "https://traserver.tra.cuhk.edu.hk/en/pro_student.php?cid=2&id=31"
          },
          {
            "code": "TRAN6107",
            "name": "Mass Media Translation",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-003-WRITTEN-TRANSLATION",
              "CUHK-TPG-003-INTERPRETING",
              "CUHK-TPG-003-COMPUTER-AUGMENTED-TRANSLATION"
            ],
            "sourceUrl": "https://traserver.tra.cuhk.edu.hk/en/pro_student.php?cid=2&id=31"
          },
          {
            "code": "TRAN6108",
            "name": "Audiovisual Translation",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-003-WRITTEN-TRANSLATION",
              "CUHK-TPG-003-INTERPRETING",
              "CUHK-TPG-003-COMPUTER-AUGMENTED-TRANSLATION"
            ],
            "sourceUrl": "https://traserver.tra.cuhk.edu.hk/en/pro_student.php?cid=2&id=31"
          },
          {
            "code": "TRAN6109",
            "name": "Science and Technology Translation",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-003-WRITTEN-TRANSLATION",
              "CUHK-TPG-003-INTERPRETING",
              "CUHK-TPG-003-COMPUTER-AUGMENTED-TRANSLATION"
            ],
            "sourceUrl": "https://traserver.tra.cuhk.edu.hk/en/pro_student.php?cid=2&id=31"
          },
          {
            "code": "TRAN6110",
            "name": "Literary Translation",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-003-WRITTEN-TRANSLATION",
              "CUHK-TPG-003-INTERPRETING",
              "CUHK-TPG-003-COMPUTER-AUGMENTED-TRANSLATION"
            ],
            "sourceUrl": "https://traserver.tra.cuhk.edu.hk/en/pro_student.php?cid=2&id=31"
          },
          {
            "code": "TRAN6111",
            "name": "Arts Translation",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-003-WRITTEN-TRANSLATION",
              "CUHK-TPG-003-INTERPRETING",
              "CUHK-TPG-003-COMPUTER-AUGMENTED-TRANSLATION"
            ],
            "sourceUrl": "https://traserver.tra.cuhk.edu.hk/en/pro_student.php?cid=2&id=31"
          },
          {
            "code": "TRAN6112",
            "name": "Readings in Translated Works",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-003-WRITTEN-TRANSLATION",
              "CUHK-TPG-003-INTERPRETING",
              "CUHK-TPG-003-COMPUTER-AUGMENTED-TRANSLATION"
            ],
            "sourceUrl": "https://traserver.tra.cuhk.edu.hk/en/pro_student.php?cid=2&id=31"
          },
          {
            "code": "TRAN6113",
            "name": "History of Translation",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-003-WRITTEN-TRANSLATION",
              "CUHK-TPG-003-INTERPRETING",
              "CUHK-TPG-003-COMPUTER-AUGMENTED-TRANSLATION"
            ],
            "sourceUrl": "https://traserver.tra.cuhk.edu.hk/en/pro_student.php?cid=2&id=31"
          },
          {
            "code": "TRAN6114",
            "name": "Translation Criticism",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-003-WRITTEN-TRANSLATION",
              "CUHK-TPG-003-INTERPRETING",
              "CUHK-TPG-003-COMPUTER-AUGMENTED-TRANSLATION"
            ],
            "sourceUrl": "https://traserver.tra.cuhk.edu.hk/en/pro_student.php?cid=2&id=31"
          },
          {
            "code": "TRAN6115",
            "name": "Translation Process and Methodology",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-003-WRITTEN-TRANSLATION",
              "CUHK-TPG-003-INTERPRETING",
              "CUHK-TPG-003-COMPUTER-AUGMENTED-TRANSLATION"
            ],
            "sourceUrl": "https://traserver.tra.cuhk.edu.hk/en/pro_student.php?cid=2&id=31"
          },
          {
            "code": "TRAN6116",
            "name": "Comparative Language Studies",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-003-WRITTEN-TRANSLATION",
              "CUHK-TPG-003-INTERPRETING",
              "CUHK-TPG-003-COMPUTER-AUGMENTED-TRANSLATION"
            ],
            "sourceUrl": "https://traserver.tra.cuhk.edu.hk/en/pro_student.php?cid=2&id=31"
          },
          {
            "code": "TRAN6117",
            "name": "Bilingual Editing Skills",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-003-WRITTEN-TRANSLATION",
              "CUHK-TPG-003-INTERPRETING",
              "CUHK-TPG-003-COMPUTER-AUGMENTED-TRANSLATION"
            ],
            "sourceUrl": "https://traserver.tra.cuhk.edu.hk/en/pro_student.php?cid=2&id=31"
          },
          {
            "code": "TRAN6119",
            "name": "Special Topics",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-003-WRITTEN-TRANSLATION",
              "CUHK-TPG-003-INTERPRETING",
              "CUHK-TPG-003-COMPUTER-AUGMENTED-TRANSLATION"
            ],
            "sourceUrl": "https://traserver.tra.cuhk.edu.hk/en/pro_student.php?cid=2&id=31"
          },
          {
            "code": "TRAN6120",
            "name": "Advanced Legal Translation",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-003-WRITTEN-TRANSLATION",
              "CUHK-TPG-003-INTERPRETING",
              "CUHK-TPG-003-COMPUTER-AUGMENTED-TRANSLATION"
            ],
            "sourceUrl": "https://traserver.tra.cuhk.edu.hk/en/pro_student.php?cid=2&id=31"
          },
          {
            "code": "TRAN6205",
            "name": "Consecutive Interpreting I: C/E",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-003-WRITTEN-TRANSLATION",
              "CUHK-TPG-003-INTERPRETING"
            ],
            "sourceUrl": "https://traserver.tra.cuhk.edu.hk/en/pro_student.php?cid=2&id=31"
          },
          {
            "code": "TRAN6206",
            "name": "Consecutive Interpreting II: C/E",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-003-WRITTEN-TRANSLATION",
              "CUHK-TPG-003-INTERPRETING"
            ],
            "sourceUrl": "https://traserver.tra.cuhk.edu.hk/en/pro_student.php?cid=2&id=31"
          },
          {
            "code": "TRAN6207",
            "name": "Simultaneous Interpreting I: C/E",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-003-WRITTEN-TRANSLATION",
              "CUHK-TPG-003-INTERPRETING"
            ],
            "sourceUrl": "https://traserver.tra.cuhk.edu.hk/en/pro_student.php?cid=2&id=31"
          },
          {
            "code": "TRAN6208",
            "name": "Simultaneous Interpreting II: C/E",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-003-WRITTEN-TRANSLATION",
              "CUHK-TPG-003-INTERPRETING"
            ],
            "sourceUrl": "https://traserver.tra.cuhk.edu.hk/en/pro_student.php?cid=2&id=31"
          },
          {
            "code": "TRAN6305",
            "name": "Consecutive Interpreting I: P/E",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-003-WRITTEN-TRANSLATION",
              "CUHK-TPG-003-INTERPRETING"
            ],
            "sourceUrl": "https://traserver.tra.cuhk.edu.hk/en/pro_student.php?cid=2&id=31"
          },
          {
            "code": "TRAN6306",
            "name": "Consecutive Interpreting II: P/E",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-003-WRITTEN-TRANSLATION",
              "CUHK-TPG-003-INTERPRETING"
            ],
            "sourceUrl": "https://traserver.tra.cuhk.edu.hk/en/pro_student.php?cid=2&id=31"
          },
          {
            "code": "TRAN6307",
            "name": "Simultaneous Interpreting I: P/E",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-003-WRITTEN-TRANSLATION",
              "CUHK-TPG-003-INTERPRETING"
            ],
            "sourceUrl": "https://traserver.tra.cuhk.edu.hk/en/pro_student.php?cid=2&id=31"
          },
          {
            "code": "TRAN6308",
            "name": "Simultaneous Interpreting II: P/E",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-003-WRITTEN-TRANSLATION",
              "CUHK-TPG-003-INTERPRETING"
            ],
            "sourceUrl": "https://traserver.tra.cuhk.edu.hk/en/pro_student.php?cid=2&id=31"
          },
          {
            "code": "TRAN6601",
            "name": "Introduction to Computer-aided Translation",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-003-WRITTEN-TRANSLATION",
              "CUHK-TPG-003-COMPUTER-AUGMENTED-TRANSLATION"
            ],
            "sourceUrl": "https://traserver.tra.cuhk.edu.hk/en/pro_student.php?cid=2&id=31"
          },
          {
            "code": "TRAN6811",
            "name": "Bilingual Lexicography",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-003-WRITTEN-TRANSLATION",
              "CUHK-TPG-003-INTERPRETING",
              "CUHK-TPG-003-COMPUTER-AUGMENTED-TRANSLATION"
            ],
            "sourceUrl": "https://traserver.tra.cuhk.edu.hk/en/pro_student.php?cid=2&id=31"
          },
          {
            "code": "TRAN6821",
            "name": "Translation Technologies in the Age of AI",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-003-WRITTEN-TRANSLATION",
              "CUHK-TPG-003-INTERPRETING",
              "CUHK-TPG-003-COMPUTER-AUGMENTED-TRANSLATION"
            ],
            "sourceUrl": "https://traserver.tra.cuhk.edu.hk/en/pro_student.php?cid=2&id=31"
          },
          {
            "code": "TRAN6823",
            "name": "Terminology Management",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-003-WRITTEN-TRANSLATION",
              "CUHK-TPG-003-INTERPRETING",
              "CUHK-TPG-003-COMPUTER-AUGMENTED-TRANSLATION"
            ],
            "sourceUrl": "https://traserver.tra.cuhk.edu.hk/en/pro_student.php?cid=2&id=31"
          },
          {
            "code": "TRAN6824",
            "name": "Post-editing for Machine Translation",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-003-WRITTEN-TRANSLATION",
              "CUHK-TPG-003-INTERPRETING",
              "CUHK-TPG-003-COMPUTER-AUGMENTED-TRANSLATION"
            ],
            "sourceUrl": "https://traserver.tra.cuhk.edu.hk/en/pro_student.php?cid=2&id=31"
          },
          {
            "code": "TRAN6825",
            "name": "Project Management for Computer-aided Translation",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-003-WRITTEN-TRANSLATION",
              "CUHK-TPG-003-INTERPRETING",
              "CUHK-TPG-003-COMPUTER-AUGMENTED-TRANSLATION"
            ],
            "sourceUrl": "https://traserver.tra.cuhk.edu.hk/en/pro_student.php?cid=2&id=31"
          },
          {
            "code": "TRAN6826",
            "name": "Game Localization",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-003-WRITTEN-TRANSLATION",
              "CUHK-TPG-003-INTERPRETING",
              "CUHK-TPG-003-COMPUTER-AUGMENTED-TRANSLATION"
            ],
            "sourceUrl": "https://traserver.tra.cuhk.edu.hk/en/pro_student.php?cid=2&id=31"
          },
          {
            "code": "TRAN6827",
            "name": "Translation as Data: Methods, Tools, and Insights",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-003-WRITTEN-TRANSLATION",
              "CUHK-TPG-003-INTERPRETING",
              "CUHK-TPG-003-COMPUTER-AUGMENTED-TRANSLATION"
            ],
            "sourceUrl": "https://traserver.tra.cuhk.edu.hk/en/pro_student.php?cid=2&id=31"
          },
          {
            "code": "TRAN6910",
            "name": "Research Seminar in Translation I",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-003-WRITTEN-TRANSLATION",
              "CUHK-TPG-003-INTERPRETING",
              "CUHK-TPG-003-COMPUTER-AUGMENTED-TRANSLATION"
            ],
            "sourceUrl": "https://traserver.tra.cuhk.edu.hk/en/pro_student.php?cid=2&id=31"
          }
        ]
      }
    ]
  },
  {
    "id": "CUHK-TPG-005",
    "courseGroups": [
      {
        "id": "required-course-options",
        "name": "Required Course Options",
        "type": "required_choice",
        "creditsRequired": 6,
        "coursesRequired": 2,
        "ruleText": "Complete any two of BUDS5013, BUDS5005 and BUDS5014 (6 units). The official course list additionally states that BUDS5014 is required for students who need to fulfil the English admission requirement, so that conditional rule requires manual review.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.arts.cuhk.edu.hk/cshb/en/buddhist-studies/mabs/%E5%AD%B8%E5%88%86%E8%A6%81%E6%B1%82/",
        "courses": [
          {
            "code": "BUDS5013",
            "name": "Theory and Method in Buddhist Studies",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.arts.cuhk.edu.hk/cshb/en/buddhist-studies/mabs/4-2/"
          },
          {
            "code": "BUDS5005",
            "name": "The Thoughts and History of Humanistic Buddhism",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.arts.cuhk.edu.hk/cshb/en/buddhist-studies/mabs/4-2/"
          },
          {
            "code": "BUDS5014",
            "name": "Buddhist Studies in the West",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.arts.cuhk.edu.hk/cshb/en/buddhist-studies/mabs/4-2/"
          }
        ]
      },
      {
        "id": "elective-courses",
        "name": "Elective Courses",
        "type": "elective",
        "creditsRequired": 15,
        "coursesRequired": 5,
        "ruleText": "Choose five elective courses (15 units) from the four official areas. The published list is a course pool and does not guarantee that every course is offered in every academic year.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.arts.cuhk.edu.hk/cshb/en/buddhist-studies/mabs/4-2/",
        "courses": [
          {
            "code": "BUDS5001",
            "name": "Pure Land Buddhism",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.arts.cuhk.edu.hk/cshb/en/buddhist-studies/mabs/4-2/"
          },
          {
            "code": "BUDS5002",
            "name": "Chan Buddhism",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.arts.cuhk.edu.hk/cshb/en/buddhist-studies/mabs/4-2/"
          },
          {
            "code": "BUDS5003",
            "name": "Tiantai Buddhism",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.arts.cuhk.edu.hk/cshb/en/buddhist-studies/mabs/4-2/"
          },
          {
            "code": "BUDS5004",
            "name": "Special Topics in Chinese Buddhist Studies",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.arts.cuhk.edu.hk/cshb/en/buddhist-studies/mabs/4-2/"
          },
          {
            "code": "PHIL5531",
            "name": "Topics in Buddhist Philosophy",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.arts.cuhk.edu.hk/cshb/en/buddhist-studies/mabs/4-2/"
          },
          {
            "code": "RELS5118",
            "name": "Studies on Chinese Buddhism",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.arts.cuhk.edu.hk/cshb/en/buddhist-studies/mabs/4-2/"
          },
          {
            "code": "BUDS5006",
            "name": "Dunhuang Buddhist Iconography",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.arts.cuhk.edu.hk/cshb/en/buddhist-studies/mabs/4-2/"
          },
          {
            "code": "BUDS5007",
            "name": "Chinese Buddhist Art",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.arts.cuhk.edu.hk/cshb/en/buddhist-studies/mabs/4-2/"
          },
          {
            "code": "BUDS5015",
            "name": "Buddhism and Religious Culture in China",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.arts.cuhk.edu.hk/cshb/en/buddhist-studies/mabs/4-2/"
          },
          {
            "code": "CHES6001",
            "name": "A Critical Cultural History of China: Early China",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.arts.cuhk.edu.hk/cshb/en/buddhist-studies/mabs/4-2/"
          },
          {
            "code": "CHES6002",
            "name": "A Critical Cultural History of China: Modern China",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.arts.cuhk.edu.hk/cshb/en/buddhist-studies/mabs/4-2/"
          },
          {
            "code": "RELS5314",
            "name": "Buddhism and Culture",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.arts.cuhk.edu.hk/cshb/en/buddhist-studies/mabs/4-2/"
          },
          {
            "code": "BUDS5008",
            "name": "Buddhism and Contemporary Society",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.arts.cuhk.edu.hk/cshb/en/buddhist-studies/mabs/4-2/"
          },
          {
            "code": "BUDS5009",
            "name": "Special Topics in Buddhism and Society",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.arts.cuhk.edu.hk/cshb/en/buddhist-studies/mabs/4-2/"
          },
          {
            "code": "BUDS5016",
            "name": "Buddhist Meditations",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.arts.cuhk.edu.hk/cshb/en/buddhist-studies/mabs/4-2/"
          },
          {
            "code": "BUDS5010",
            "name": "Basic Pāli",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.arts.cuhk.edu.hk/cshb/en/buddhist-studies/mabs/4-2/"
          },
          {
            "code": "BUDS5011",
            "name": "Basic Sanskrit",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.arts.cuhk.edu.hk/cshb/en/buddhist-studies/mabs/4-2/"
          }
        ]
      },
      {
        "id": "graduation-paper",
        "name": "Project (Graduation Paper)",
        "type": "project",
        "creditsRequired": 3,
        "coursesRequired": 1,
        "ruleText": "Complete BUDS5012 Graduation Paper (3 units).",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.arts.cuhk.edu.hk/cshb/en/buddhist-studies/mabs/%E5%AD%B8%E5%88%86%E8%A6%81%E6%B1%82/",
        "courses": [
          {
            "code": "BUDS5012",
            "name": "Graduation Paper",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.arts.cuhk.edu.hk/cshb/en/buddhist-studies/mabs/%E5%AD%B8%E5%88%86%E8%A6%81%E6%B1%82/"
          }
        ]
      }
    ]
  },
  {
    "id": "CUHK-TPG-012",
    "courseGroups": [
      {
        "id": "required-courses",
        "name": "Required Courses",
        "type": "core",
        "creditsRequired": 9,
        "coursesRequired": 3,
        "ruleText": "Complete all three required courses. An approved exemption must be replaced by an approved elective course.",
        "sourceUrl": "https://msc-seem.se.cuhk.edu.hk/programme/course-structure/",
        "courses": [
          {
            "code": "SEEM5710",
            "name": "Principles of Operations Management",
            "credits": 3,
            "sourceUrl": "https://msc-seem.se.cuhk.edu.hk/programme/course-structure/"
          },
          {
            "code": "SEEM5730",
            "name": "Information Technology Management",
            "credits": 3,
            "sourceUrl": "https://msc-seem.se.cuhk.edu.hk/programme/course-structure/"
          },
          {
            "code": "SEEM5820",
            "name": "Introduction to Financial Engineering",
            "credits": 3,
            "sourceUrl": "https://msc-seem.se.cuhk.edu.hk/programme/course-structure/"
          }
        ]
      },
      {
        "id": "elective-courses",
        "name": "Elective Courses",
        "type": "elective_with_area_requirement",
        "creditsRequired": 15,
        "coursesRequired": 5,
        "ruleText": "Complete five elective courses, including at least one course from each of Area I, Area II and Area III. SEEM5910 and SEEM5920 may count in any area, but at most one of those two courses may count toward the minimum graduation requirement. Other Faculty of Engineering MSc courses require Division Head approval. The area constraint and approved external electives require manual audit review.",
        "sourceUrl": "https://msc-seem.se.cuhk.edu.hk/programme/course-structure/",
        "courses": [
          {
            "code": "SEEM5910",
            "name": "Project in SEEM",
            "credits": 3,
            "sourceUrl": "https://msc-seem.se.cuhk.edu.hk/programme/course-structure/"
          },
          {
            "code": "SEEM5920",
            "name": "SEEM Internship",
            "credits": 3,
            "sourceUrl": "https://msc-seem.se.cuhk.edu.hk/programme/course-structure/"
          },
          {
            "code": "SEEM5740",
            "name": "Engineering Economics",
            "credits": 3,
            "area": "Area I: Operations Management",
            "sourceUrl": "https://msc-seem.se.cuhk.edu.hk/programme/course-structure/"
          },
          {
            "code": "SEEM5790",
            "name": "Project and Technology Management",
            "credits": 3,
            "area": "Area I: Operations Management",
            "sourceUrl": "https://msc-seem.se.cuhk.edu.hk/programme/course-structure/"
          },
          {
            "code": "SEEM5800",
            "name": "Logistics Management",
            "credits": 3,
            "area": "Area I: Operations Management",
            "sourceUrl": "https://msc-seem.se.cuhk.edu.hk/programme/course-structure/"
          },
          {
            "code": "SEEM5810",
            "name": "Machine Intelligence and Systems Engineering",
            "credits": 3,
            "area": "Area I / Area II",
            "sourceUrl": "https://msc-seem.se.cuhk.edu.hk/programme/course-structure/"
          },
          {
            "code": "SEEM5880",
            "name": "Supply Chain Management",
            "credits": 3,
            "area": "Area I: Operations Management",
            "sourceUrl": "https://msc-seem.se.cuhk.edu.hk/programme/course-structure/"
          },
          {
            "code": "SEEM5750",
            "name": "Expert Systems and Decision Support",
            "credits": 3,
            "area": "Area II: Information Systems",
            "sourceUrl": "https://msc-seem.se.cuhk.edu.hk/programme/course-structure/"
          },
          {
            "code": "SEEM5760",
            "name": "Client/Server Information Systems",
            "credits": 3,
            "area": "Area II: Information Systems",
            "sourceUrl": "https://msc-seem.se.cuhk.edu.hk/programme/course-structure/"
          },
          {
            "code": "SEEM5770",
            "name": "Open Systems and Electronic Commerce",
            "credits": 3,
            "area": "Area II: Information Systems",
            "sourceUrl": "https://msc-seem.se.cuhk.edu.hk/programme/course-structure/"
          },
          {
            "code": "SEEM5830",
            "name": "Stochastic Investment Models",
            "credits": 3,
            "area": "Area III: Financial Engineering",
            "sourceUrl": "https://msc-seem.se.cuhk.edu.hk/programme/course-structure/"
          },
          {
            "code": "SEEM5840",
            "name": "Quantitative Risk Management",
            "credits": 3,
            "area": "Area III: Financial Engineering",
            "sourceUrl": "https://msc-seem.se.cuhk.edu.hk/programme/course-structure/"
          },
          {
            "code": "SEEM5870",
            "name": "Computational Finance",
            "credits": 3,
            "area": "Area III: Financial Engineering",
            "sourceUrl": "https://msc-seem.se.cuhk.edu.hk/programme/course-structure/"
          }
        ]
      }
    ]
  },
  {
    "id": "CUHK-TPG-013",
    "courseGroups": [
      {
        "id": "required-courses",
        "name": "Required Courses",
        "type": "core",
        "creditsRequired": 9,
        "coursesRequired": 3,
        "ruleText": "Complete all three required courses (9 units). A student admitted with a finance-related background may be exempted from FINA6122, but must replace it with an additional elective to preserve the 24-unit total.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://fintech.erg.cuhk.edu.hk/programme-information/master-science/master-science",
        "courses": [
          {
            "code": "FINA6122",
            "name": "Financial Markets and Instruments",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://fintech.erg.cuhk.edu.hk/programme-information/master-science/master-science"
          },
          {
            "code": "FTEC5510",
            "name": "Advanced Financial Infrastructure",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://fintech.erg.cuhk.edu.hk/programme-information/master-science/master-science"
          },
          {
            "code": "FTEC5520",
            "name": "Applied Blockchain and Cryptocurrencies",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://fintech.erg.cuhk.edu.hk/programme-information/master-science/master-science"
          }
        ]
      },
      {
        "id": "technology-electives",
        "name": "Technology-Oriented Electives",
        "type": "elective",
        "ruleText": "Together with the Business / Application-Oriented Electives, complete five courses for the Course Track, four for the Practicum Track, or three for the Industrial Project Track. The Track-dependent course count requires manual audit review.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://fintech.erg.cuhk.edu.hk/programme-information/master-science/master-science",
        "courses": [
          {
            "code": "AIMS5730",
            "name": "Natural Language Processing",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://fintech.erg.cuhk.edu.hk/programme-information/master-science/master-science"
          },
          {
            "code": "CMSC5743",
            "name": "Efficient Computing of Deep Neural Networks",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://fintech.erg.cuhk.edu.hk/programme-information/master-science/master-science"
          },
          {
            "code": "ENGG5108",
            "name": "Big Data Analytics",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://fintech.erg.cuhk.edu.hk/programme-information/master-science/master-science"
          },
          {
            "code": "FTEC5530",
            "name": "Quantitative and Algorithmic Trading",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://fintech.erg.cuhk.edu.hk/programme-information/master-science/master-science"
          },
          {
            "code": "FTEC5580",
            "name": "Data Analytics for Financial Technology",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://fintech.erg.cuhk.edu.hk/programme-information/master-science/master-science"
          },
          {
            "code": "FTEC5610",
            "name": "Computational Finance",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://fintech.erg.cuhk.edu.hk/programme-information/master-science/master-science"
          },
          {
            "code": "FTEC5660",
            "name": "Agentic AI for Business and FinTech",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://fintech.erg.cuhk.edu.hk/programme-information/master-science/master-science"
          },
          {
            "code": "FTEC5680",
            "name": "AI Applications in FinTech",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://fintech.erg.cuhk.edu.hk/programme-information/master-science/master-science"
          },
          {
            "code": "IEMS5710",
            "name": "Cryptography, Information Security and Privacy",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://fintech.erg.cuhk.edu.hk/programme-information/master-science/master-science"
          },
          {
            "code": "IEMS5726",
            "name": "Data Science in Practice",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://fintech.erg.cuhk.edu.hk/programme-information/master-science/master-science"
          },
          {
            "code": "IEMS5730",
            "name": "Big Data Systems and Information Processing",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://fintech.erg.cuhk.edu.hk/programme-information/master-science/master-science"
          },
          {
            "code": "IERG5310",
            "name": "Security & Privacy in Cyber Systems",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://fintech.erg.cuhk.edu.hk/programme-information/master-science/master-science"
          },
          {
            "code": "IERG5320",
            "name": "Digital Forensics",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://fintech.erg.cuhk.edu.hk/programme-information/master-science/master-science"
          },
          {
            "code": "IERG5350",
            "name": "Reinforcement Learning",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://fintech.erg.cuhk.edu.hk/programme-information/master-science/master-science"
          },
          {
            "code": "SEEM5840",
            "name": "Quantitative Risk Management",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://fintech.erg.cuhk.edu.hk/programme-information/master-science/master-science"
          }
        ]
      },
      {
        "id": "business-application-electives",
        "name": "Business / Application-Oriented Electives",
        "type": "elective",
        "ruleText": "Together with the Technology-Oriented Electives, complete five courses for the Course Track, four for the Practicum Track, or three for the Industrial Project Track. Course availability is not guaranteed every term.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://fintech.erg.cuhk.edu.hk/programme-information/master-science/master-science",
        "courses": [
          {
            "code": "ACCT6141",
            "name": "Accounting Data Analytics and Business Intelligence",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://fintech.erg.cuhk.edu.hk/programme-information/master-science/master-science"
          },
          {
            "code": "CMSC5741",
            "name": "Big Data Technology and Applications",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://fintech.erg.cuhk.edu.hk/programme-information/master-science/master-science"
          },
          {
            "code": "DOTE6100",
            "name": "Managing Service Operation",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://fintech.erg.cuhk.edu.hk/programme-information/master-science/master-science"
          },
          {
            "code": "DOTE6751",
            "name": "Database and Big Data Management",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://fintech.erg.cuhk.edu.hk/programme-information/master-science/master-science"
          },
          {
            "code": "DOTE6756",
            "name": "Machine Learning for Business I",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://fintech.erg.cuhk.edu.hk/programme-information/master-science/master-science"
          },
          {
            "code": "ECLT5720",
            "name": "Electronic Payments Systems",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://fintech.erg.cuhk.edu.hk/programme-information/master-science/master-science"
          },
          {
            "code": "FINA6250",
            "name": "Fundamentals Derivatives Trading Strategies",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://fintech.erg.cuhk.edu.hk/programme-information/master-science/master-science"
          },
          {
            "code": "FTEC4006",
            "name": "Internet Finance",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://fintech.erg.cuhk.edu.hk/programme-information/master-science/master-science"
          },
          {
            "code": "FTEC5550",
            "name": "Elements of RegTech for the Financial Market",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://fintech.erg.cuhk.edu.hk/programme-information/master-science/master-science"
          },
          {
            "code": "FTEC5560",
            "name": "Topics in Financial Technology Innovations",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://fintech.erg.cuhk.edu.hk/programme-information/master-science/master-science"
          },
          {
            "code": "FTEC5570",
            "name": "Financial Technology Entrepreneurship",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://fintech.erg.cuhk.edu.hk/programme-information/master-science/master-science"
          },
          {
            "code": "FTEC5590",
            "name": "Intelligent Automation - Robotic Process Automation (RPA) & Artificial Intelligence (AI)",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://fintech.erg.cuhk.edu.hk/programme-information/master-science/master-science"
          },
          {
            "code": "FTEC5620",
            "name": "Wealth Management in Business and FinTech",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://fintech.erg.cuhk.edu.hk/programme-information/master-science/master-science"
          },
          {
            "code": "FTEC5630",
            "name": "Green FinTech",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://fintech.erg.cuhk.edu.hk/programme-information/master-science/master-science"
          },
          {
            "code": "FTEC5640",
            "name": "Decentralized Finance",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://fintech.erg.cuhk.edu.hk/programme-information/master-science/master-science"
          },
          {
            "code": "FTEC5650",
            "name": "Topics in International FinTech",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://fintech.erg.cuhk.edu.hk/programme-information/master-science/master-science"
          },
          {
            "code": "FTEC5670",
            "name": "Financial Technology Entrepreneurship Field Trip",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://fintech.erg.cuhk.edu.hk/programme-information/master-science/master-science"
          },
          {
            "code": "SEEM5730",
            "name": "Information Technology Management",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://fintech.erg.cuhk.edu.hk/programme-information/master-science/master-science"
          },
          {
            "code": "SEEM5820",
            "name": "Introduction to Financial Engineering",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://fintech.erg.cuhk.edu.hk/programme-information/master-science/master-science"
          }
        ]
      },
      {
        "id": "enrichment-training",
        "name": "Enrichment Training",
        "type": "internship_or_project",
        "ruleText": "Practicum Track students complete FTEC5540 (3 units). Industrial Project Track students complete both FTEC5910 and FTEC5920 in consecutive semesters (6 units); Project I earns credit only when Project II is subsequently completed unless the Programme Director approves otherwise.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://fintech.erg.cuhk.edu.hk/programme-information/master-science/master-science",
        "courses": [
          {
            "code": "FTEC5540",
            "name": "Financial Technology Internship",
            "credits": 3,
            "appliesToTrackIds": [
              "CUHK-TPG-013-PRACTICUM"
            ],
            "sourceUrl": "https://fintech.erg.cuhk.edu.hk/programme-information/master-science/master-science"
          },
          {
            "code": "FTEC5910",
            "name": "Financial Technology Project I",
            "credits": 3,
            "appliesToTrackIds": [
              "CUHK-TPG-013-INDUSTRIAL-PROJECT"
            ],
            "sourceUrl": "https://fintech.erg.cuhk.edu.hk/programme-information/master-science/master-science"
          },
          {
            "code": "FTEC5920",
            "name": "Financial Technology Project II",
            "credits": 3,
            "appliesToTrackIds": [
              "CUHK-TPG-013-INDUSTRIAL-PROJECT"
            ],
            "sourceUrl": "https://fintech.erg.cuhk.edu.hk/programme-information/master-science/master-science"
          }
        ]
      }
    ]
  },
  {
    "id": "CUHK-TPG-016",
    "courseGroups": [
      {
        "id": "mmat-course-pool",
        "name": "MMAT Course Pool",
        "type": "elective_with_stream_rules",
        "creditsRequired": 24,
        "coursesRequired": 8,
        "ruleText": "Complete 24 units. Mathematics Stream students complete 24 units in MMAT5xxx. Big Data Analytics and Computations Stream students complete 24 units in MMAT5xxx, including at least 18 units from MMAT5210, MMAT5230, MMAT5240, MMAT5250 and MMAT53xx. For either Stream, at most 3 units may instead be selected from MATH3xxx-4xxx or MATH5xxx-6xxx. The code-range rule and any external MATH selection require manual audit review; the listed pool contains the official MMAT courses only and does not imply that every course is offered every year.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.math.cuhk.edu.hk/postgraduates/taught-programme/msc-mathematics",
        "courses": [
          {
            "code": "MMAT5000",
            "name": "Analysis I",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-016-MATHEMATICS"
            ],
            "sourceUrl": "https://www.math.cuhk.edu.hk/postgraduates/taught-programme/msc-mathematics"
          },
          {
            "code": "MMAT5010",
            "name": "Linear Analysis",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-016-MATHEMATICS"
            ],
            "sourceUrl": "https://www.math.cuhk.edu.hk/postgraduates/taught-programme/msc-mathematics"
          },
          {
            "code": "MMAT5011",
            "name": "Analysis II",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-016-MATHEMATICS"
            ],
            "sourceUrl": "https://www.math.cuhk.edu.hk/postgraduates/taught-programme/msc-mathematics"
          },
          {
            "code": "MMAT5020",
            "name": "Algebra & Geometry",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-016-MATHEMATICS"
            ],
            "sourceUrl": "https://www.math.cuhk.edu.hk/postgraduates/taught-programme/msc-mathematics"
          },
          {
            "code": "MMAT5021",
            "name": "Differential and Algebraic Methods in Geometry",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-016-MATHEMATICS"
            ],
            "sourceUrl": "https://www.math.cuhk.edu.hk/postgraduates/taught-programme/msc-mathematics"
          },
          {
            "code": "MMAT5030",
            "name": "Fourier Analysis",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-016-MATHEMATICS"
            ],
            "sourceUrl": "https://www.math.cuhk.edu.hk/postgraduates/taught-programme/msc-mathematics"
          },
          {
            "code": "MMAT5110",
            "name": "Topics in Number Theory",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-016-MATHEMATICS"
            ],
            "sourceUrl": "https://www.math.cuhk.edu.hk/postgraduates/taught-programme/msc-mathematics"
          },
          {
            "code": "MMAT5120",
            "name": "Topics in Geometry",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-016-MATHEMATICS"
            ],
            "sourceUrl": "https://www.math.cuhk.edu.hk/postgraduates/taught-programme/msc-mathematics"
          },
          {
            "code": "MMAT5130",
            "name": "Topics in Differential Equations",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-016-MATHEMATICS"
            ],
            "sourceUrl": "https://www.math.cuhk.edu.hk/postgraduates/taught-programme/msc-mathematics"
          },
          {
            "code": "MMAT5140",
            "name": "Probability Theory",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-016-MATHEMATICS"
            ],
            "sourceUrl": "https://www.math.cuhk.edu.hk/postgraduates/taught-programme/msc-mathematics"
          },
          {
            "code": "MMAT5210",
            "name": "Discrete Mathematics",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-016-MATHEMATICS",
              "CUHK-TPG-016-BIG-DATA-ANALYTICS-COMPUTATIONS"
            ],
            "sourceUrl": "https://www.math.cuhk.edu.hk/postgraduates/taught-programme/msc-mathematics"
          },
          {
            "code": "MMAT5220",
            "name": "Complex Analysis and Its Applications",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-016-MATHEMATICS"
            ],
            "sourceUrl": "https://www.math.cuhk.edu.hk/postgraduates/taught-programme/msc-mathematics"
          },
          {
            "code": "MMAT5230",
            "name": "Mathematics for Logistics",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-016-MATHEMATICS",
              "CUHK-TPG-016-BIG-DATA-ANALYTICS-COMPUTATIONS"
            ],
            "sourceUrl": "https://www.math.cuhk.edu.hk/postgraduates/taught-programme/msc-mathematics"
          },
          {
            "code": "MMAT5240",
            "name": "Optimization and Modeling",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-016-MATHEMATICS",
              "CUHK-TPG-016-BIG-DATA-ANALYTICS-COMPUTATIONS"
            ],
            "sourceUrl": "https://www.math.cuhk.edu.hk/postgraduates/taught-programme/msc-mathematics"
          },
          {
            "code": "MMAT5250",
            "name": "Financial Mathematics",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-016-MATHEMATICS",
              "CUHK-TPG-016-BIG-DATA-ANALYTICS-COMPUTATIONS"
            ],
            "sourceUrl": "https://www.math.cuhk.edu.hk/postgraduates/taught-programme/msc-mathematics"
          },
          {
            "code": "MMAT5260",
            "name": "Calculus of Variations",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-016-MATHEMATICS"
            ],
            "sourceUrl": "https://www.math.cuhk.edu.hk/postgraduates/taught-programme/msc-mathematics"
          },
          {
            "code": "MMAT5270",
            "name": "Introduction to Inverse Problems",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-016-MATHEMATICS"
            ],
            "sourceUrl": "https://www.math.cuhk.edu.hk/postgraduates/taught-programme/msc-mathematics"
          },
          {
            "code": "MMAT5310",
            "name": "Financial Analytics",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-016-MATHEMATICS",
              "CUHK-TPG-016-BIG-DATA-ANALYTICS-COMPUTATIONS"
            ],
            "sourceUrl": "https://www.math.cuhk.edu.hk/postgraduates/taught-programme/msc-mathematics"
          },
          {
            "code": "MMAT5320",
            "name": "Computational Mathematics",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-016-MATHEMATICS",
              "CUHK-TPG-016-BIG-DATA-ANALYTICS-COMPUTATIONS"
            ],
            "sourceUrl": "https://www.math.cuhk.edu.hk/postgraduates/taught-programme/msc-mathematics"
          },
          {
            "code": "MMAT5330",
            "name": "Econometric Principles and Data Analysis",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-016-MATHEMATICS",
              "CUHK-TPG-016-BIG-DATA-ANALYTICS-COMPUTATIONS"
            ],
            "sourceUrl": "https://www.math.cuhk.edu.hk/postgraduates/taught-programme/msc-mathematics"
          },
          {
            "code": "MMAT5340",
            "name": "Probability and Stochastic Analysis",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-016-MATHEMATICS",
              "CUHK-TPG-016-BIG-DATA-ANALYTICS-COMPUTATIONS"
            ],
            "sourceUrl": "https://www.math.cuhk.edu.hk/postgraduates/taught-programme/msc-mathematics"
          },
          {
            "code": "MMAT5350",
            "name": "Coding Theory",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-016-MATHEMATICS",
              "CUHK-TPG-016-BIG-DATA-ANALYTICS-COMPUTATIONS"
            ],
            "sourceUrl": "https://www.math.cuhk.edu.hk/postgraduates/taught-programme/msc-mathematics"
          },
          {
            "code": "MMAT5360",
            "name": "Game Theory",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-016-MATHEMATICS",
              "CUHK-TPG-016-BIG-DATA-ANALYTICS-COMPUTATIONS"
            ],
            "sourceUrl": "https://www.math.cuhk.edu.hk/postgraduates/taught-programme/msc-mathematics"
          },
          {
            "code": "MMAT5370",
            "name": "Social and Economic Networks: theory, Modelling and Computations",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-016-MATHEMATICS",
              "CUHK-TPG-016-BIG-DATA-ANALYTICS-COMPUTATIONS"
            ],
            "sourceUrl": "https://www.math.cuhk.edu.hk/postgraduates/taught-programme/msc-mathematics"
          },
          {
            "code": "MMAT5380",
            "name": "Graph Theory and Networks",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-016-MATHEMATICS",
              "CUHK-TPG-016-BIG-DATA-ANALYTICS-COMPUTATIONS"
            ],
            "sourceUrl": "https://www.math.cuhk.edu.hk/postgraduates/taught-programme/msc-mathematics"
          },
          {
            "code": "MMAT5390",
            "name": "Mathematical Image Processing",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-016-MATHEMATICS",
              "CUHK-TPG-016-BIG-DATA-ANALYTICS-COMPUTATIONS"
            ],
            "sourceUrl": "https://www.math.cuhk.edu.hk/postgraduates/taught-programme/msc-mathematics"
          },
          {
            "code": "MMAT5391",
            "name": "Mathematical Theories of Machine Learning",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-016-MATHEMATICS",
              "CUHK-TPG-016-BIG-DATA-ANALYTICS-COMPUTATIONS"
            ],
            "sourceUrl": "https://www.math.cuhk.edu.hk/postgraduates/taught-programme/msc-mathematics"
          },
          {
            "code": "MMAT5392",
            "name": "Mathematical Principles of Artificial Intelligence",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-016-MATHEMATICS",
              "CUHK-TPG-016-BIG-DATA-ANALYTICS-COMPUTATIONS"
            ],
            "sourceUrl": "https://www.math.cuhk.edu.hk/postgraduates/taught-programme/msc-mathematics"
          },
          {
            "code": "MMAT5393",
            "name": "Numerical Linear Algebra and Applications",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-016-MATHEMATICS",
              "CUHK-TPG-016-BIG-DATA-ANALYTICS-COMPUTATIONS"
            ],
            "sourceUrl": "https://www.math.cuhk.edu.hk/postgraduates/taught-programme/msc-mathematics"
          },
          {
            "code": "MMAT5394",
            "name": "Markov Chains and Algorithmic Applications",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-016-MATHEMATICS",
              "CUHK-TPG-016-BIG-DATA-ANALYTICS-COMPUTATIONS"
            ],
            "sourceUrl": "https://www.math.cuhk.edu.hk/postgraduates/taught-programme/msc-mathematics"
          },
          {
            "code": "MMAT5395",
            "name": "Mathematics of Games of Chance",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-016-MATHEMATICS",
              "CUHK-TPG-016-BIG-DATA-ANALYTICS-COMPUTATIONS"
            ],
            "sourceUrl": "https://www.math.cuhk.edu.hk/postgraduates/taught-programme/msc-mathematics"
          },
          {
            "code": "MMAT5396",
            "name": "Mathematics of Multivariate Data",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-016-MATHEMATICS",
              "CUHK-TPG-016-BIG-DATA-ANALYTICS-COMPUTATIONS"
            ],
            "sourceUrl": "https://www.math.cuhk.edu.hk/postgraduates/taught-programme/msc-mathematics"
          },
          {
            "code": "MMAT5410",
            "name": "Guided Studies I",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-016-MATHEMATICS"
            ],
            "sourceUrl": "https://www.math.cuhk.edu.hk/postgraduates/taught-programme/msc-mathematics"
          },
          {
            "code": "MMAT5420",
            "name": "Guided Studies II",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-016-MATHEMATICS"
            ],
            "sourceUrl": "https://www.math.cuhk.edu.hk/postgraduates/taught-programme/msc-mathematics"
          },
          {
            "code": "MMAT5430",
            "name": "Graduate Seminar I",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-016-MATHEMATICS"
            ],
            "sourceUrl": "https://www.math.cuhk.edu.hk/postgraduates/taught-programme/msc-mathematics"
          },
          {
            "code": "MMAT5440",
            "name": "Graduate Seminar II",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-016-MATHEMATICS"
            ],
            "sourceUrl": "https://www.math.cuhk.edu.hk/postgraduates/taught-programme/msc-mathematics"
          }
        ]
      }
    ]
  },
  {
    "id": "CUHK-TPG-017",
    "courseGroups": [
      {
        "id": "core-courses",
        "name": "Core Courses",
        "type": "core",
        "creditsRequired": 9,
        "coursesRequired": 3,
        "ruleText": "Complete all three Core Courses (9 credits). The official 2026-27 full-time and part-time study plans both name STAT5101, STAT5102 and STAT5106 as the three Core Courses.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://dsbs.cuhk.edu.hk/programme-details/",
        "courses": [
          {
            "code": "STAT5101",
            "name": "Foundations of Data Science",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://dsbs.cuhk.edu.hk/programme-details/"
          },
          {
            "code": "STAT5102",
            "name": "Regression in Practice",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://dsbs.cuhk.edu.hk/programme-details/"
          },
          {
            "code": "STAT5106",
            "name": "Programming Techniques for Data Science",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://dsbs.cuhk.edu.hk/programme-details/"
          }
        ]
      },
      {
        "id": "elective-courses",
        "name": "Elective Courses",
        "type": "elective_with_optional_research_workshop",
        "creditsRequired": 15,
        "coursesRequired": 5,
        "ruleText": "Choose five Elective Courses (15 credits) from the official course pool. STAT6111 Research Workshop is listed in the full-time Elective pool and offers either an organization-assigned project or a supervised CUHK research project; it is optional and is not a compulsory Project or Dissertation. Its full-time-only placement and all course availability require manual review.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://dsbs.cuhk.edu.hk/programme-details/",
        "courses": [
          {
            "code": "STAT5103",
            "name": "High-dimensional Data Analysis",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://dsbs.cuhk.edu.hk/programme-details/"
          },
          {
            "code": "STAT5104",
            "name": "Data Mining",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://dsbs.cuhk.edu.hk/programme-details/"
          },
          {
            "code": "STAT5105",
            "name": "Applied Survival Data Analysis",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://dsbs.cuhk.edu.hk/programme-details/"
          },
          {
            "code": "STAT5107",
            "name": "Discrete Data Analytics",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://dsbs.cuhk.edu.hk/programme-details/"
          },
          {
            "code": "STAT6104",
            "name": "Financial Time Series",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://dsbs.cuhk.edu.hk/programme-details/"
          },
          {
            "code": "STAT6105",
            "name": "Basic Actuarial Principles and Their Applications",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://dsbs.cuhk.edu.hk/programme-details/"
          },
          {
            "code": "STAT6106",
            "name": "Applied Bayesian Methods",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://dsbs.cuhk.edu.hk/programme-details/"
          },
          {
            "code": "STAT6107",
            "name": "Selected Topics on Data Science and Business Statistics",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://dsbs.cuhk.edu.hk/programme-details/"
          },
          {
            "code": "STAT6108",
            "name": "Official Statistics and Structural Equation Modelling",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://dsbs.cuhk.edu.hk/programme-details/"
          },
          {
            "code": "STAT6207",
            "name": "Applied Deep Learning",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://dsbs.cuhk.edu.hk/programme-details/"
          },
          {
            "code": "STAT6111",
            "name": "Research Workshop",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://dsbs.cuhk.edu.hk/programme-details/"
          },
          {
            "code": "RMSC5101",
            "name": "Statistical Methods in Risk Management and Finance",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://dsbs.cuhk.edu.hk/programme-details/"
          },
          {
            "code": "RMSC6001",
            "name": "Interest Rate and Fixed Incomes Risk Management",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://dsbs.cuhk.edu.hk/programme-details/"
          },
          {
            "code": "RMSC6003",
            "name": "Risk Management in Financial Institutions",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://dsbs.cuhk.edu.hk/programme-details/"
          },
          {
            "code": "RMSC6004",
            "name": "Special Topics in Risk Management",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://dsbs.cuhk.edu.hk/programme-details/"
          },
          {
            "code": "RMSC6007",
            "name": "Risk and Financial Data Analytics with Python",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://dsbs.cuhk.edu.hk/programme-details/"
          }
        ]
      }
    ]
  },
  {
    "id": "CUHK-TPG-018",
    "courseGroups": [
      {
        "id": "required-courses",
        "name": "Required Courses",
        "type": "core",
        "creditsRequired": 12,
        "coursesRequired": 4,
        "ruleText": "Complete all four Required Courses (12 units).",
        "appliesToTrackIds": [],
        "sourceUrl": "https://pg.com.cuhk.edu.hk/pgp_global/pdf/StudySchemeGLCfor2026Admission.pdf",
        "courses": [
          {
            "code": "COMM5120",
            "name": "Emerging Global Media and Cultures",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://pg.com.cuhk.edu.hk/pgp_global/course-lists/"
          },
          {
            "code": "COMM5520",
            "name": "Applied Communication Research",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://pg.com.cuhk.edu.hk/pgp_global/course-lists/"
          },
          {
            "code": "COMM5710",
            "name": "Seminar in Communication Theories",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://pg.com.cuhk.edu.hk/pgp_global/course-lists/"
          },
          {
            "code": "COMM5711",
            "name": "Reframing Narratives of the Global",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://pg.com.cuhk.edu.hk/pgp_global/course-lists/"
          }
        ]
      },
      {
        "id": "elective-course-pool",
        "name": "Elective Course Pool",
        "type": "elective_with_optional_streams",
        "creditsRequired": 12,
        "coursesRequired": 4,
        "ruleText": "Without a Specialization Stream, choose any four listed Elective Courses (12 units). Challenges of Global Futures requires any two of COMM5510/COMM5590/COMM5723/COMM5725/COMM5775/COMM5992, any one of COMM5838/COMM5771/COMM5947/COMM6420, and COMM5773. Making and Measuring Impact requires any two of COMM5636/COMM5725/COMM5735/COMM5773/COMM5775/COMM5992, any one of COMM5510/COMM5530/COMM5649/COMM5772/COMM5947, and COMM5771. Approved substitutions from other COMM courses at 5000 level or above require manual review.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://pg.com.cuhk.edu.hk/pgp_global/pdf/StudySchemeGLCfor2026Admission.pdf",
        "courses": [
          {
            "code": "COMM5110",
            "name": "Topical Studies in Communication I",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://pg.com.cuhk.edu.hk/pgp_global/course-lists/"
          },
          {
            "code": "COMM5111",
            "name": "Topical Studies in Communication II",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://pg.com.cuhk.edu.hk/pgp_global/course-lists/"
          },
          {
            "code": "COMM5510",
            "name": "Media Management",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-018-CHALLENGES-OF-GLOBAL-FUTURES",
              "CUHK-TPG-018-MAKING-AND-MEASURING-IMPACT"
            ],
            "sourceUrl": "https://pg.com.cuhk.edu.hk/pgp_global/course-lists/"
          },
          {
            "code": "COMM5530",
            "name": "Crisis Management",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-018-MAKING-AND-MEASURING-IMPACT"
            ],
            "sourceUrl": "https://pg.com.cuhk.edu.hk/pgp_global/course-lists/"
          },
          {
            "code": "COMM5590",
            "name": "Culture and Communication",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-018-CHALLENGES-OF-GLOBAL-FUTURES"
            ],
            "sourceUrl": "https://pg.com.cuhk.edu.hk/pgp_global/course-lists/"
          },
          {
            "code": "COMM5636",
            "name": "Beat Reporting in Technology, Health and Environment",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-018-MAKING-AND-MEASURING-IMPACT"
            ],
            "sourceUrl": "https://pg.com.cuhk.edu.hk/pgp_global/course-lists/"
          },
          {
            "code": "COMM5649",
            "name": "Analyzing Public Affairs",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-018-MAKING-AND-MEASURING-IMPACT"
            ],
            "sourceUrl": "https://pg.com.cuhk.edu.hk/pgp_global/course-lists/"
          },
          {
            "code": "COMM5723",
            "name": "Public Relations and Globalization",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-018-CHALLENGES-OF-GLOBAL-FUTURES"
            ],
            "sourceUrl": "https://pg.com.cuhk.edu.hk/pgp_global/course-lists/"
          },
          {
            "code": "COMM5725",
            "name": "Multistakeholder Decision Making and Media Practice",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-018-CHALLENGES-OF-GLOBAL-FUTURES",
              "CUHK-TPG-018-MAKING-AND-MEASURING-IMPACT"
            ],
            "sourceUrl": "https://pg.com.cuhk.edu.hk/pgp_global/course-lists/"
          },
          {
            "code": "COMM5735",
            "name": "New Media and Society",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-018-MAKING-AND-MEASURING-IMPACT"
            ],
            "sourceUrl": "https://pg.com.cuhk.edu.hk/pgp_global/course-lists/"
          },
          {
            "code": "COMM5771",
            "name": "Topical Studies in Global Communication I",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-018-CHALLENGES-OF-GLOBAL-FUTURES",
              "CUHK-TPG-018-MAKING-AND-MEASURING-IMPACT"
            ],
            "sourceUrl": "https://pg.com.cuhk.edu.hk/pgp_global/course-lists/"
          },
          {
            "code": "COMM5772",
            "name": "Topical Studies in Global Communication II",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-018-MAKING-AND-MEASURING-IMPACT"
            ],
            "sourceUrl": "https://pg.com.cuhk.edu.hk/pgp_global/course-lists/"
          },
          {
            "code": "COMM5773",
            "name": "Topical Studies in Global Communication III",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-018-CHALLENGES-OF-GLOBAL-FUTURES",
              "CUHK-TPG-018-MAKING-AND-MEASURING-IMPACT"
            ],
            "sourceUrl": "https://pg.com.cuhk.edu.hk/pgp_global/course-lists/"
          },
          {
            "code": "COMM5775",
            "name": "Cultures in Media",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-018-CHALLENGES-OF-GLOBAL-FUTURES",
              "CUHK-TPG-018-MAKING-AND-MEASURING-IMPACT"
            ],
            "sourceUrl": "https://pg.com.cuhk.edu.hk/pgp_global/course-lists/"
          },
          {
            "code": "COMM5838",
            "name": "Mastering Digital Media Content",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-018-CHALLENGES-OF-GLOBAL-FUTURES"
            ],
            "sourceUrl": "https://pg.com.cuhk.edu.hk/pgp_global/course-lists/"
          },
          {
            "code": "COMM5947",
            "name": "Data Science and AI in New Media",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-018-CHALLENGES-OF-GLOBAL-FUTURES",
              "CUHK-TPG-018-MAKING-AND-MEASURING-IMPACT"
            ],
            "sourceUrl": "https://pg.com.cuhk.edu.hk/pgp_global/course-lists/"
          },
          {
            "code": "COMM5992",
            "name": "Critical Data Studies",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-018-CHALLENGES-OF-GLOBAL-FUTURES",
              "CUHK-TPG-018-MAKING-AND-MEASURING-IMPACT"
            ],
            "sourceUrl": "https://pg.com.cuhk.edu.hk/pgp_global/course-lists/"
          },
          {
            "code": "COMM6120",
            "name": "Topical Studies in Communication III",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://pg.com.cuhk.edu.hk/pgp_global/course-lists/"
          },
          {
            "code": "COMM6121",
            "name": "Topical Studies in Communication IV",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://pg.com.cuhk.edu.hk/pgp_global/course-lists/"
          },
          {
            "code": "COMM6420",
            "name": "Strategies for Integrated Communication Campaigns",
            "credits": 3,
            "appliesToTrackIds": [],
            "countsTowardTrackIds": [
              "CUHK-TPG-018-CHALLENGES-OF-GLOBAL-FUTURES"
            ],
            "sourceUrl": "https://pg.com.cuhk.edu.hk/pgp_global/course-lists/"
          }
        ]
      }
    ]
  }
];
