// Generated by npm run sync:ug-catalog. Do not edit manually.
const courses = require('../../ugCourseData/cityu-b');
const universityCode = "CITYU";
const packageName = "subpackages/ug-data-cityu-b";

Page({
  onLoad() {
    const app = getApp();
    if (typeof app.registerUgCourseShard === 'function') {
      app.registerUgCourseShard({ universityCode, packageName, courses });
    }
    setTimeout(() => wx.navigateBack({ delta: 1 }), 0);
  }
});
