// Generated by npm run sync:ug-catalog. Do not edit manually.
const courses = require('../../ugCourseData/cityu-b');
const universityCode = "CITYU";
const packageName = "subpackages/ug-data-cityu-b";

Page({
  onLoad() {
    const app = getApp();
    if (typeof app.registerUgCourseShard === 'function') {
      app.registerUgCourseShard({ universityCode, packageName, courses });
    }
    const completeActivation = () => {
      if (typeof app.completeUgCourseShardActivation === 'function') {
        app.completeUgCourseShardActivation(packageName);
      }
    };
    const returnToCaller = (attempt = 0) => wx.navigateBack({
      delta: 1,
      success: completeActivation,
      fail() {
        if (attempt < 4) {
          setTimeout(() => returnToCaller(attempt + 1), 100);
        }
      }
    });
    setTimeout(() => returnToCaller(), 100);
  }
});
