// Generated by npm run sync:tpg. Do not edit manually.
module.exports = [
  {
    "id": "HKBU-TPG-017",
    "courseGroups": [
      {
        "id": "bridging-courses",
        "name": "Bridging Courses",
        "type": "bridging",
        "creditsRequired": 6,
        "coursesRequired": 2,
        "ruleText": "Complete both Bridging Courses (6 units). Transfer of units or course exemption is subject to formal Programme and Academic Registry approval and requires manual review.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://comd.hkbu.edu.hk/masters/en/aidm",
        "courses": [
          {
            "code": "AIDM7320",
            "name": "Basics in Media and Communication",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://comd.hkbu.edu.hk/masters/en/aidm"
          },
          {
            "code": "AIDM7330",
            "name": "Programming for Data Science",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://comd.hkbu.edu.hk/masters/en/aidm"
          }
        ]
      },
      {
        "id": "core-courses",
        "name": "Core Courses",
        "type": "core",
        "creditsRequired": 12,
        "coursesRequired": 4,
        "ruleText": "Complete all four Core Courses (12 units).",
        "appliesToTrackIds": [],
        "sourceUrl": "https://comd.hkbu.edu.hk/masters/en/aidm",
        "courses": [
          {
            "code": "AIDM7340",
            "name": "AI for Digital Media",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://comd.hkbu.edu.hk/masters/en/aidm"
          },
          {
            "code": "AIDM7350",
            "name": "AI and Digital Media Workshop",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://comd.hkbu.edu.hk/masters/en/aidm"
          },
          {
            "code": "AIDM7360",
            "name": "Big Data Management and Analytics",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://comd.hkbu.edu.hk/masters/en/aidm"
          },
          {
            "code": "AIDM7390",
            "name": "Data Mining & Knowledge Discovery for Digital Media",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://comd.hkbu.edu.hk/masters/en/aidm"
          }
        ]
      },
      {
        "id": "elective-courses",
        "name": "Elective Courses",
        "type": "elective_with_programme_minimum",
        "creditsRequired": 12,
        "coursesRequired": 4,
        "ruleText": "Complete four 3-unit electives (12 units), including at least 9 units from AIDM-coded Programme electives. Up to 3 units may therefore come from the listed COMM or COMP electives. AIDM7460 Digital Media Research Project is optional and no dissertation is compulsory. Programme-code allocation and approved transfer or exemption require manual review.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://comd.hkbu.edu.hk/masters/en/aidm",
        "courses": [
          {
            "code": "AIDM7010",
            "name": "Media Psychology",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://comd.hkbu.edu.hk/masters/en/aidm"
          },
          {
            "code": "AIDM7020",
            "name": "AI and Big Data Applications in Financial Market Analytics",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://comd.hkbu.edu.hk/masters/en/aidm"
          },
          {
            "code": "AIDM7040",
            "name": "Generative AI for Digital Media",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://comd.hkbu.edu.hk/masters/en/aidm"
          },
          {
            "code": "AIDM7380",
            "name": "Recommender Systems for Digital Media",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://comd.hkbu.edu.hk/masters/en/aidm"
          },
          {
            "code": "AIDM7400",
            "name": "Data Analysis and Visualization Studio",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://comd.hkbu.edu.hk/masters/en/aidm"
          },
          {
            "code": "AIDM7410",
            "name": "Computational Journalism",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://comd.hkbu.edu.hk/masters/en/aidm"
          },
          {
            "code": "AIDM7420",
            "name": "News and Feature Writing for Digital Media",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://comd.hkbu.edu.hk/masters/en/aidm"
          },
          {
            "code": "AIDM7450",
            "name": "Dynamic Web & Mobile Programming for Digital Media",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://comd.hkbu.edu.hk/masters/en/aidm"
          },
          {
            "code": "AIDM7460",
            "name": "Digital Media Research Project",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://comd.hkbu.edu.hk/masters/en/aidm"
          },
          {
            "code": "AIDM7470",
            "name": "Big Data and Social Media Marketing",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://comd.hkbu.edu.hk/masters/en/aidm"
          },
          {
            "code": "AIDM7620",
            "name": "Social Media and Online Social Networks",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://comd.hkbu.edu.hk/masters/en/aidm"
          },
          {
            "code": "AIDM7840",
            "name": "Algorithmic Culture",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://comd.hkbu.edu.hk/masters/en/aidm"
          },
          {
            "code": "AIDM7860",
            "name": "Human-Computer Interaction and User Experience",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://comd.hkbu.edu.hk/masters/en/aidm"
          },
          {
            "code": "AIDM7880",
            "name": "AI for Social Good: Laws, Ethics, and Methods",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://comd.hkbu.edu.hk/masters/en/aidm"
          },
          {
            "code": "COMM7020",
            "name": "Approaches & Methods in Communication Research",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://comd.hkbu.edu.hk/masters/en/aidm"
          },
          {
            "code": "COMM7660",
            "name": "Statistical Analysis in Communication",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://comd.hkbu.edu.hk/masters/en/aidm"
          },
          {
            "code": "COMP7045",
            "name": "Natural Language Processing",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://comd.hkbu.edu.hk/masters/en/aidm"
          },
          {
            "code": "COMP7810",
            "name": "Business Intelligence",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://comd.hkbu.edu.hk/masters/en/aidm"
          },
          {
            "code": "COMP7990",
            "name": "Principles and Practices of Data Analytics",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://comd.hkbu.edu.hk/masters/en/aidm"
          }
        ]
      }
    ]
  },
  {
    "id": "HKBU-TPG-018",
    "courseGroups": [
      {
        "id": "required-courses",
        "name": "Required Courses",
        "type": "core_laboratory",
        "creditsRequired": 12,
        "coursesRequired": 4,
        "ruleText": "Complete all four Required Courses, including Green Laboratory (12 units).",
        "appliesToTrackIds": [],
        "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-physics/master-of-science-in-green-technology-energy",
        "courses": [
          {
            "code": "PHYS7320",
            "name": "Renewable Energy Technologies I",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-physics/master-of-science-in-green-technology-energy"
          },
          {
            "code": "PHYS7330",
            "name": "Renewable Energy Technologies II",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-physics/master-of-science-in-green-technology-energy"
          },
          {
            "code": "PHYS7340",
            "name": "Energy Storage and Harvesting Technology",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-physics/master-of-science-in-green-technology-energy"
          },
          {
            "code": "PHYS7360",
            "name": "Green Laboratory",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-physics/master-of-science-in-green-technology-energy"
          }
        ]
      },
      {
        "id": "project",
        "name": "Projects in Green Technology",
        "type": "project",
        "creditsRequired": 6,
        "coursesRequired": 2,
        "ruleText": "Complete both Project in Green Technology courses (6 units). Project work is required for every MSc student.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-physics/master-of-science-in-green-technology-energy",
        "courses": [
          {
            "code": "PHYS7371",
            "name": "Project in Green Technology I",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-physics/master-of-science-in-green-technology-energy"
          },
          {
            "code": "PHYS7372",
            "name": "Project in Green Technology II",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-physics/master-of-science-in-green-technology-energy"
          }
        ]
      },
      {
        "id": "elective-courses",
        "name": "Elective Courses",
        "type": "elective",
        "creditsRequired": 12,
        "coursesRequired": 4,
        "ruleText": "Choose four 3-unit Elective Courses (12 units) from the official pool. Annual offerings may vary.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-physics/master-of-science-in-green-technology-energy",
        "courses": [
          {
            "code": "ECON7450",
            "name": "Energy Economics",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-physics/master-of-science-in-green-technology-energy"
          },
          {
            "code": "PHYS7350",
            "name": "Smart and Remote Sensing",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-physics/master-of-science-in-green-technology-energy"
          },
          {
            "code": "PHYS7380",
            "name": "Advanced Topics in Physics I",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-physics/master-of-science-in-green-technology-energy"
          },
          {
            "code": "PHYS7390",
            "name": "Advanced Topics in Physics II",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-physics/master-of-science-in-green-technology-energy"
          },
          {
            "code": "PHYS7400",
            "name": "Advanced Topics in Physics III",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-physics/master-of-science-in-green-technology-energy"
          },
          {
            "code": "PHYS7410",
            "name": "Physics for Green Technology",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-physics/master-of-science-in-green-technology-energy"
          },
          {
            "code": "PHYS7420",
            "name": "Energy Usage, the Environment and Sustainability",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-physics/master-of-science-in-green-technology-energy"
          },
          {
            "code": "PHYS7430",
            "name": "Introduction to Modern Materials",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-physics/master-of-science-in-green-technology-energy"
          },
          {
            "code": "PHYS7440",
            "name": "Principles of Optoelectronics",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-physics/master-of-science-in-green-technology-energy"
          },
          {
            "code": "PHYS7450",
            "name": "Principles of Photonics Physics",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-physics/master-of-science-in-green-technology-energy"
          },
          {
            "code": "PHYS7460",
            "name": "Advances in Displays and Lighting",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-physics/master-of-science-in-green-technology-energy"
          },
          {
            "code": "PHYS7470",
            "name": "Energy Audit and Management",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-physics/master-of-science-in-green-technology-energy"
          },
          {
            "code": "PHYS7480",
            "name": "Flexible Electronics",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-physics/master-of-science-in-green-technology-energy"
          },
          {
            "code": "PHYS7540",
            "name": "Advanced Topics in Energy Studies",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-physics/master-of-science-in-green-technology-energy"
          },
          {
            "code": "PHYS7550",
            "name": "Smart Grids and Sustainable Power Systems",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-physics/master-of-science-in-green-technology-energy"
          }
        ]
      }
    ]
  },
  {
    "id": "HKBU-TPG-019",
    "courseGroups": [
      {
        "id": "core-courses",
        "name": "Core Courses",
        "type": "core_with_background_substitution",
        "creditsRequired": 14,
        "coursesRequired": 6,
        "ruleText": "Complete six Core Courses (14 units). A student with an IT or closely related Bachelor's degree, or equivalent prior courses, must substitute COMP7510 Internet Computing and Programming with one 3-unit elective course. Background-based substitution requires manual review.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf",
        "courses": [
          {
            "code": "COMP7025",
            "name": "Artificial Intelligence for Digital Transformation",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7105",
            "name": "Business Data Analytics",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7510",
            "name": "Internet Computing and Programming",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7520",
            "name": "Foundations of Management in the IT Context",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7530",
            "name": "IT Forum",
            "credits": 1,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7950",
            "name": "IT Project Skills",
            "credits": 1,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          }
        ]
      },
      {
        "id": "elective-courses",
        "name": "Elective Courses",
        "type": "elective_cross_stream_project_research",
        "creditsRequired": 15,
        "coursesRequired": 5,
        "ruleText": "Complete five 3-unit electives (15 units). Select at least three of the four official elective streams—IT Enterprise Management, Knowledge and Information Management, Internet and Web Technologies, and Business Analytics—and complete at least one course in each selected stream. MSc Project & Research courses are also in the official elective catalogue. Stream allocation, the background substitution for COMP7510, and annual offerings require manual review; these stream labels are not Programme Tracks.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf",
        "courses": [
          {
            "code": "COMP7075",
            "name": "Financial Technology Management",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7085",
            "name": "Digital Marketing and Analytics",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7115",
            "name": "Digital Experience Design",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7540",
            "name": "IT Management: Principles and Practice",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7550",
            "name": "IT Project Management",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7560",
            "name": "Information Systems Auditing",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7580",
            "name": "Electronic Transformation in Business",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7770",
            "name": "Special Topics in IT Management",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7870",
            "name": "IT Innovation Management and Entrepreneurship",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7880",
            "name": "E-Business Strategies",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7095",
            "name": "Big Data Management",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7640",
            "name": "Database Systems and Administration",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7650",
            "name": "Data Mining and Knowledge Discovery",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7780",
            "name": "Special Topics in Knowledge and Information Management",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7810",
            "name": "Business Intelligence",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7125",
            "name": "Prompt Engineering for Generative AI",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7680",
            "name": "Internet and World Wide Web",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7790",
            "name": "Special Topics in Internet and Web Technologies",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7850",
            "name": "Information Security Management",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7940",
            "name": "Cloud Computing",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7980",
            "name": "Dynamic Web and Mobile Programming",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7760",
            "name": "Special Topics in Business Analytics",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7800",
            "name": "Analytic Models in IT Management",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7820",
            "name": "Visual Analytics and Decision Support",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7730",
            "name": "MSc Project",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7960",
            "name": "MSc Research I",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7970",
            "name": "MSc Research II",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          }
        ]
      }
    ]
  },
  {
    "id": "HKBU-TPG-020",
    "courseGroups": [
      {
        "id": "required-courses",
        "name": "Required Courses",
        "type": "core",
        "creditsRequired": 25,
        "coursesRequired": 8,
        "ruleText": "Complete all eight Required Courses (25 units).",
        "appliesToTrackIds": [],
        "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-mathematics/master-of-science-in-operational-research-and-business",
        "courses": [
          {
            "code": "MATH7960",
            "name": "Applied Multivariate Analysis",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-mathematics/master-of-science-in-operational-research-and-business"
          },
          {
            "code": "MATH7790",
            "name": "Prescriptive Analytics for Decision Making",
            "credits": 4,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-mathematics/master-of-science-in-operational-research-and-business"
          },
          {
            "code": "MATH7810",
            "name": "Business Statistics with Python",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-mathematics/master-of-science-in-operational-research-and-business"
          },
          {
            "code": "MATH7820",
            "name": "Simulation Modelling",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-mathematics/master-of-science-in-operational-research-and-business"
          },
          {
            "code": "MATH7830",
            "name": "Machine Learning and Forecasting",
            "credits": 4,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-mathematics/master-of-science-in-operational-research-and-business"
          },
          {
            "code": "MATH7840",
            "name": "Advanced Spreadsheets and Decision Support Systems",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-mathematics/master-of-science-in-operational-research-and-business"
          },
          {
            "code": "MATH7970",
            "name": "Applied Time Series",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-mathematics/master-of-science-in-operational-research-and-business"
          },
          {
            "code": "MATH7990",
            "name": "Regression Analysis",
            "credits": 2,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-mathematics/master-of-science-in-operational-research-and-business"
          }
        ]
      },
      {
        "id": "dissertation",
        "name": "MSc Dissertation",
        "type": "dissertation",
        "creditsRequired": 6,
        "coursesRequired": 2,
        "ruleText": "Complete both Dissertation courses (6 units).",
        "appliesToTrackIds": [],
        "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-mathematics/master-of-science-in-operational-research-and-business",
        "courses": [
          {
            "code": "MATH7941",
            "name": "Dissertation I",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-mathematics/master-of-science-in-operational-research-and-business"
          },
          {
            "code": "MATH7942",
            "name": "Dissertation II",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-mathematics/master-of-science-in-operational-research-and-business"
          }
        ]
      },
      {
        "id": "elective-courses",
        "name": "Elective Courses",
        "type": "elective",
        "creditsRequired": 9,
        "coursesRequired": 3,
        "ruleText": "Choose three 3-unit Elective Courses (9 units) from the official pool. Annual offerings may vary.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-mathematics/master-of-science-in-operational-research-and-business",
        "courses": [
          {
            "code": "MATH7800",
            "name": "Techniques of Production Operations Management",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-mathematics/master-of-science-in-operational-research-and-business"
          },
          {
            "code": "MATH7850",
            "name": "Managing Organisational Performance",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-mathematics/master-of-science-in-operational-research-and-business"
          },
          {
            "code": "MATH7860",
            "name": "Quantitative Models for Marketing",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-mathematics/master-of-science-in-operational-research-and-business"
          },
          {
            "code": "MATH7870",
            "name": "Big Data Analytics and Visualisation",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-mathematics/master-of-science-in-operational-research-and-business"
          },
          {
            "code": "MATH7880",
            "name": "Survey Sampling and Experimental Design",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-mathematics/master-of-science-in-operational-research-and-business"
          },
          {
            "code": "MATH7890",
            "name": "Actuarial Statistics",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-mathematics/master-of-science-in-operational-research-and-business"
          },
          {
            "code": "MATH7900",
            "name": "Network and Project Management",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-mathematics/master-of-science-in-operational-research-and-business"
          },
          {
            "code": "MATH7910",
            "name": "Derivatives",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-mathematics/master-of-science-in-operational-research-and-business"
          },
          {
            "code": "MATH7920",
            "name": "Work-based Learning",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-mathematics/master-of-science-in-operational-research-and-business"
          },
          {
            "code": "MATH7930",
            "name": "Risk and Portfolio Management",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-mathematics/master-of-science-in-operational-research-and-business"
          },
          {
            "code": "MATH7980",
            "name": "Advanced Operational Research",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-mathematics/master-of-science-in-operational-research-and-business"
          },
          {
            "code": "MATH7005",
            "name": "Data Analytics with Programming",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-mathematics/master-of-science-in-operational-research-and-business"
          }
        ]
      }
    ]
  },
  {
    "id": "HKBU-TPG-021",
    "courseGroups": [
      {
        "id": "required-courses",
        "name": "Required Courses",
        "type": "core",
        "creditsRequired": 35,
        "coursesRequired": 10,
        "ruleText": "Complete all ten Required Courses (35 units) across the four-semester HKBU–University of Kent study schedule.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-mathematics/master-of-science-in-mathematical-finance",
        "courses": [
          {
            "code": "MATH7680",
            "name": "Quantitative Methods for Finance",
            "credits": 4,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-mathematics/master-of-science-in-mathematical-finance"
          },
          {
            "code": "MATH7690",
            "name": "Financial Markets and Instruments",
            "credits": 4,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-mathematics/master-of-science-in-mathematical-finance"
          },
          {
            "code": "MATH7720",
            "name": "Investments Management",
            "credits": 4,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-mathematics/master-of-science-in-mathematical-finance"
          },
          {
            "code": "MATH7760",
            "name": "Programming for Finance and Trading",
            "credits": 4,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-mathematics/master-of-science-in-mathematical-finance"
          },
          {
            "code": "MATH7700",
            "name": "Risk Management",
            "credits": 4,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-mathematics/master-of-science-in-mathematical-finance"
          },
          {
            "code": "MATH7620",
            "name": "Topics in Probability Theory & Stochastic Processes",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-mathematics/master-of-science-in-mathematical-finance"
          },
          {
            "code": "MATH7640",
            "name": "Computational Finance",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-mathematics/master-of-science-in-mathematical-finance"
          },
          {
            "code": "MATH7650",
            "name": "Time Series Analysis",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-mathematics/master-of-science-in-mathematical-finance"
          },
          {
            "code": "MATH7660",
            "name": "Mathematical Finance",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-mathematics/master-of-science-in-mathematical-finance"
          },
          {
            "code": "MATH7670",
            "name": "Derivatives II",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-mathematics/master-of-science-in-mathematical-finance"
          }
        ]
      },
      {
        "id": "elective-course",
        "name": "Elective Course",
        "type": "elective",
        "creditsRequired": 4,
        "coursesRequired": 1,
        "ruleText": "Choose one 4-unit Elective Course from the seven-course pool in Semester 3.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-mathematics/master-of-science-in-mathematical-finance",
        "courses": [
          {
            "code": "MATH7630",
            "name": "Derivatives",
            "credits": 4,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-mathematics/master-of-science-in-mathematical-finance"
          },
          {
            "code": "MATH7710",
            "name": "Financial Econometrics",
            "credits": 4,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-mathematics/master-of-science-in-mathematical-finance"
          },
          {
            "code": "MATH7730",
            "name": "Investment Analysis",
            "credits": 4,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-mathematics/master-of-science-in-mathematical-finance"
          },
          {
            "code": "MATH7740",
            "name": "Credit Risk",
            "credits": 4,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-mathematics/master-of-science-in-mathematical-finance"
          },
          {
            "code": "MATH7750",
            "name": "Corporate Governance and Ethics",
            "credits": 4,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-mathematics/master-of-science-in-mathematical-finance"
          },
          {
            "code": "MATH7770",
            "name": "Algorithmic Trading",
            "credits": 4,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-mathematics/master-of-science-in-mathematical-finance"
          },
          {
            "code": "MATH7780",
            "name": "Financial Technology",
            "credits": 4,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-mathematics/master-of-science-in-mathematical-finance"
          }
        ]
      }
    ]
  },
  {
    "id": "HKBU-TPG-022",
    "courseGroups": [
      {
        "id": "required-taught-laboratory-seminar",
        "name": "Required Taught, Laboratory and Seminar Courses",
        "type": "core_laboratory_seminar",
        "creditsRequired": 18,
        "coursesRequired": 12,
        "ruleText": "Complete all twelve Required taught, laboratory and seminar courses (18 units).",
        "appliesToTrackIds": [],
        "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-chemistry/master-of-science-in-analytical-chemistry",
        "courses": [
          {
            "code": "CHEM7210",
            "name": "Analytical Process and Applied Statistics",
            "credits": 2,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-chemistry/master-of-science-in-analytical-chemistry"
          },
          {
            "code": "CHEM7220",
            "name": "Chemical Instrumentation",
            "credits": 2,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-chemistry/master-of-science-in-analytical-chemistry"
          },
          {
            "code": "CHEM7250",
            "name": "Laboratory Management",
            "credits": 2,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-chemistry/master-of-science-in-analytical-chemistry"
          },
          {
            "code": "CHEM7401",
            "name": "Seminar I",
            "credits": 0.5,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-chemistry/master-of-science-in-analytical-chemistry"
          },
          {
            "code": "CHEM7402",
            "name": "Seminar II",
            "credits": 0.5,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-chemistry/master-of-science-in-analytical-chemistry"
          },
          {
            "code": "CHEM7403",
            "name": "Seminar III",
            "credits": 0.5,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-chemistry/master-of-science-in-analytical-chemistry"
          },
          {
            "code": "CHEM7404",
            "name": "Seminar IV",
            "credits": 0.5,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-chemistry/master-of-science-in-analytical-chemistry"
          },
          {
            "code": "CHEM7411",
            "name": "Advanced Analytical Laboratory I",
            "credits": 2,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-chemistry/master-of-science-in-analytical-chemistry"
          },
          {
            "code": "CHEM7412",
            "name": "Advanced Analytical Laboratory II",
            "credits": 2,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-chemistry/master-of-science-in-analytical-chemistry"
          },
          {
            "code": "CHEM7970",
            "name": "Applied Spectroscopy",
            "credits": 2,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-chemistry/master-of-science-in-analytical-chemistry"
          },
          {
            "code": "CHEM7980",
            "name": "Atomic Spectrometry",
            "credits": 2,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-chemistry/master-of-science-in-analytical-chemistry"
          },
          {
            "code": "CHEM7990",
            "name": "Separation Science",
            "credits": 2,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-chemistry/master-of-science-in-analytical-chemistry"
          }
        ]
      },
      {
        "id": "dissertation",
        "name": "Dissertation",
        "type": "dissertation",
        "creditsRequired": 6,
        "coursesRequired": 2,
        "ruleText": "Complete both Dissertation courses (6 units). The Dissertation is an integral MSc requirement; it may be omitted only for the separate interim Postgraduate Diploma award.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-chemistry/master-of-science-in-analytical-chemistry",
        "courses": [
          {
            "code": "CHEM7331",
            "name": "Dissertation",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-chemistry/master-of-science-in-analytical-chemistry"
          },
          {
            "code": "CHEM7332",
            "name": "Dissertation",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-chemistry/master-of-science-in-analytical-chemistry"
          }
        ]
      },
      {
        "id": "elective-courses",
        "name": "Elective Courses",
        "type": "elective",
        "creditsRequired": 3,
        "coursesRequired": 3,
        "ruleText": "Choose three 1-unit Elective Courses (3 units) from the official pool.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-chemistry/master-of-science-in-analytical-chemistry",
        "courses": [
          {
            "code": "CHEM7005",
            "name": "Food Nutrient Analysis",
            "credits": 1,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-chemistry/master-of-science-in-analytical-chemistry"
          },
          {
            "code": "CHEM7015",
            "name": "Food Safety Analysis",
            "credits": 1,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-chemistry/master-of-science-in-analytical-chemistry"
          },
          {
            "code": "CHEM7280",
            "name": "Surface Analysis",
            "credits": 1,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-chemistry/master-of-science-in-analytical-chemistry"
          },
          {
            "code": "CHEM7340",
            "name": "Environmental Analysis",
            "credits": 1,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-chemistry/master-of-science-in-analytical-chemistry"
          },
          {
            "code": "CHEM7350",
            "name": "Sample Pretreatment Methods",
            "credits": 1,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-chemistry/master-of-science-in-analytical-chemistry"
          },
          {
            "code": "CHEM7430",
            "name": "Pharmaceutical Analysis",
            "credits": 1,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-chemistry/master-of-science-in-analytical-chemistry"
          },
          {
            "code": "CHEM7440",
            "name": "Biomedical Analysis",
            "credits": 1,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-chemistry/master-of-science-in-analytical-chemistry"
          },
          {
            "code": "CHEM7460",
            "name": "Forensic Analysis",
            "credits": 1,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-chemistry/master-of-science-in-analytical-chemistry"
          },
          {
            "code": "CHEM7490",
            "name": "Nanomaterial Analysis",
            "credits": 1,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/academic-programmes/postgraduate-programmes/faculty-of-science/department-of-chemistry/master-of-science-in-analytical-chemistry"
          }
        ]
      }
    ]
  },
  {
    "id": "HKBU-TPG-023",
    "courseGroups": [
      {
        "id": "required-courses",
        "name": "Required Courses",
        "type": "core",
        "creditsRequired": 6,
        "coursesRequired": 2,
        "ruleText": "Complete both Required Courses (6 units).",
        "appliesToTrackIds": [],
        "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/postgraduate-programmes/faculty-of-science/master-of-science-in-environmental-and-public-health",
        "courses": [
          {
            "code": "EPHM7020",
            "name": "Management of Public Health Risks",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/postgraduate-programmes/faculty-of-science/master-of-science-in-environmental-and-public-health"
          },
          {
            "code": "EPHM7110",
            "name": "Principles of Environmental Management",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/postgraduate-programmes/faculty-of-science/master-of-science-in-environmental-and-public-health"
          }
        ]
      },
      {
        "id": "elective-courses",
        "name": "Elective Courses",
        "type": "elective",
        "creditsRequired": 15,
        "coursesRequired": 5,
        "ruleText": "Choose five 3-unit Elective Courses (15 units) from the seven-course official pool.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/postgraduate-programmes/faculty-of-science/master-of-science-in-environmental-and-public-health",
        "courses": [
          {
            "code": "EPHM7010",
            "name": "Sustainable Management Systems",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/postgraduate-programmes/faculty-of-science/master-of-science-in-environmental-and-public-health"
          },
          {
            "code": "EPHM7040",
            "name": "Land and Water Resources Management",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/postgraduate-programmes/faculty-of-science/master-of-science-in-environmental-and-public-health"
          },
          {
            "code": "EPHM7050",
            "name": "Integrated Waste Management",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/postgraduate-programmes/faculty-of-science/master-of-science-in-environmental-and-public-health"
          },
          {
            "code": "EPHM7070",
            "name": "Research Methodologies in Environmental Monitoring and Public Health Protection",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/postgraduate-programmes/faculty-of-science/master-of-science-in-environmental-and-public-health"
          },
          {
            "code": "EPHM7320",
            "name": "Occupational Health and Safety Management",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/postgraduate-programmes/faculty-of-science/master-of-science-in-environmental-and-public-health"
          },
          {
            "code": "EPHM7330",
            "name": "Food Quality, Law and Safety Management",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/postgraduate-programmes/faculty-of-science/master-of-science-in-environmental-and-public-health"
          },
          {
            "code": "EPHM7340",
            "name": "Carbon and Energy Management",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/postgraduate-programmes/faculty-of-science/master-of-science-in-environmental-and-public-health"
          }
        ]
      },
      {
        "id": "dissertation",
        "name": "MSc Dissertation",
        "type": "dissertation",
        "creditsRequired": 6,
        "coursesRequired": 2,
        "ruleText": "Complete both MSc Dissertation courses (6 units). The Dissertation is required for the MSc award; the separate Postgraduate Diploma exit award does not change this MSc requirement.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/postgraduate-programmes/faculty-of-science/master-of-science-in-environmental-and-public-health",
        "courses": [
          {
            "code": "EPHM7311",
            "name": "MSc Dissertation",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/postgraduate-programmes/faculty-of-science/master-of-science-in-environmental-and-public-health"
          },
          {
            "code": "EPHM7312",
            "name": "MSc Dissertation",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://handbook.ar.hkbu.edu.hk/2025-2026/postgraduate-programmes/faculty-of-science/master-of-science-in-environmental-and-public-health"
          }
        ]
      }
    ]
  },
  {
    "id": "HKBU-TPG-024",
    "courseGroups": [
      {
        "id": "core-courses",
        "name": "Core Courses",
        "type": "core",
        "creditsRequired": 14,
        "coursesRequired": 6,
        "ruleText": "Complete all six Core Courses (14 units).",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf",
        "courses": [
          {
            "code": "COMP7015",
            "name": "Artificial Intelligence",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7035",
            "name": "Python for Data Analytics and Artificial Intelligence",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7180",
            "name": "Quantitative Methods for Data Analytics and Artificial Intelligence",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7990",
            "name": "Principles and Practices of Data Analytics",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7155",
            "name": "Ethics of Data Analytics and Artificial Intelligence",
            "credits": 1,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7530",
            "name": "IT Forum",
            "credits": 1,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          }
        ]
      },
      {
        "id": "elective-courses",
        "name": "Elective Courses",
        "type": "elective_practicum_research",
        "creditsRequired": 15,
        "coursesRequired": 5,
        "ruleText": "Complete 15 units from the Data Analytics, Artificial Intelligence, and MSc Practicum & Research elective categories. Students may select freely across the categories; the category labels are not Tracks and do not create separate award requirements. Offerings may receive minor curriculum revisions.",
        "appliesToTrackIds": [],
        "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf",
        "courses": [
          {
            "code": "COMP7065",
            "name": "Innovative Laboratory",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7135",
            "name": "Audio and Speech Processing",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7170",
            "name": "Data Security and Privacy",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7200",
            "name": "Blockchain and Cryptocurrencies",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7260",
            "name": "Special Topics in Data Analytics",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7300",
            "name": "Financial Technology",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7640",
            "name": "Database Systems and Administration",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7650",
            "name": "Data Mining and Knowledge Discovery",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7810",
            "name": "Business Intelligence",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7820",
            "name": "Visual Analytics and Decision Support",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7930",
            "name": "Big Data Analytics",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7940",
            "name": "Cloud Computing",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7045",
            "name": "Natural Language Processing and Large Language Models",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7055",
            "name": "Computer Vision",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7125",
            "name": "Prompt Engineering for Generative AI",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7220",
            "name": "Special Topics in Artificial Intelligence",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7240",
            "name": "Recommender Systems",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7250",
            "name": "Machine Learning",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7630",
            "name": "Web Intelligence and Its Applications",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7145",
            "name": "Autonomous Robotics",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7280",
            "name": "MSc Practicum",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7960",
            "name": "MSc Research I",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          },
          {
            "code": "COMP7970",
            "name": "MSc Research II",
            "credits": 3,
            "appliesToTrackIds": [],
            "sourceUrl": "https://www.comp.hkbu.edu.hk/msc/msc_booklet.pdf"
          }
        ]
      }
    ]
  }
];
