const data = {
  universities: [
    { id: 1, code: 'HKU', nameEn: 'The University of Hong Kong', nameZh: '香港大学' },
    { id: 2, code: 'HKUST', nameEn: 'The Hong Kong University of Science and Technology', nameZh: '香港科技大学' }
  ],
  faculties: [
    { id: 1, universityId: 1, nameEn: 'Faculty of Engineering', nameZh: '工程学院' }
  ],
  programmes: [
    {
      id: 1,
      universityId: 1,
      facultyId: 1,
      code: 'BENG',
      nameEn: 'Bachelor of Engineering',
      nameZh: '工学学士',
      curriculumYear: '2026',
      totalCreditRequired: 240
    }
  ],
  majors: [
    { id: 1, programmeId: 1, code: 'COMP', nameEn: 'Computer Science', nameZh: '计算机科学' }
  ],
  courses: [
    {
      id: 1,
      universityId: 1,
      programmeId: 1,
      majorId: 1,
      courseCode: 'COMP1117',
      titleEn: 'Computer Programming',
      titleZh: '计算机编程',
      credits: 6,
      courseType: 'core',
      department: 'Computer Science',
      prerequisites: 'None',
      exclusions: 'May not be taken with equivalent introductory programming courses.',
      semester: 'Semester 1 / Semester 2',
      language: 'English',
      recommendedYear: 1,
      description: 'Introductory programming course covering problem solving, programming syntax, and basic software development practices.',
      officialUrl: 'https://www.cs.hku.hk/',
      lastVerifiedAt: '2026-07-04'
    },
    {
      id: 2,
      universityId: 1,
      programmeId: 1,
      majorId: 1,
      courseCode: 'COMP2113',
      titleEn: 'Programming Technologies',
      titleZh: '编程技术',
      credits: 6,
      courseType: 'core',
      department: 'Computer Science',
      prerequisites: 'COMP1117 or equivalent',
      exclusions: '',
      semester: 'Semester 2',
      language: 'English',
      recommendedYear: 2,
      description: 'Covers practical programming techniques and tools used in modern software development.',
      officialUrl: 'https://www.cs.hku.hk/',
      lastVerifiedAt: '2026-07-04'
    },
    {
      id: 3,
      universityId: 1,
      programmeId: 1,
      majorId: 1,
      courseCode: 'COMP2121',
      titleEn: 'Discrete Mathematics',
      titleZh: '离散数学',
      credits: 6,
      courseType: 'core',
      department: 'Computer Science',
      prerequisites: 'None',
      exclusions: '',
      semester: 'Semester 1',
      language: 'English',
      recommendedYear: 1,
      description: 'Mathematical foundations for computer science, including logic, proofs, sets, relations, graphs, and combinatorics.',
      officialUrl: 'https://www.cs.hku.hk/',
      lastVerifiedAt: '2026-07-04'
    },
    {
      id: 4,
      universityId: 1,
      programmeId: 1,
      majorId: 1,
      courseCode: 'COMP2396',
      titleEn: 'Object-oriented Programming and Java',
      titleZh: '面向对象编程与 Java',
      credits: 6,
      courseType: 'core',
      department: 'Computer Science',
      prerequisites: 'COMP1117',
      exclusions: '',
      semester: 'Semester 1',
      language: 'English',
      recommendedYear: 2,
      description: 'Object-oriented programming concepts and Java application development.',
      officialUrl: 'https://www.cs.hku.hk/',
      lastVerifiedAt: '2026-07-04'
    },
    {
      id: 5,
      universityId: 1,
      programmeId: 1,
      majorId: 1,
      courseCode: 'COMP3278',
      titleEn: 'Introduction to Database Management Systems',
      titleZh: '数据库管理系统导论',
      credits: 6,
      courseType: 'major_elective',
      department: 'Computer Science',
      prerequisites: 'COMP2113 or equivalent programming background',
      exclusions: '',
      semester: 'Semester 2',
      language: 'English',
      recommendedYear: 3,
      description: 'Introduction to database design, relational model, SQL, indexing, transactions, and database applications.',
      officialUrl: 'https://www.cs.hku.hk/',
      lastVerifiedAt: '2026-07-04'
    },
    {
      id: 6,
      universityId: 1,
      programmeId: 1,
      majorId: 1,
      courseCode: 'COMP4801',
      titleEn: 'Final Year Project',
      titleZh: '毕业项目',
      credits: 12,
      courseType: 'capstone',
      department: 'Computer Science',
      prerequisites: 'Final year standing and department approval',
      exclusions: '',
      semester: 'Full Year',
      language: 'English',
      recommendedYear: 4,
      description: 'A substantial project integrating knowledge and skills acquired in the programme.',
      officialUrl: 'https://www.cs.hku.hk/',
      lastVerifiedAt: '2026-07-04'
    },
    {
      id: 7,
      universityId: 1,
      programmeId: 1,
      majorId: 1,
      courseCode: 'CCST9003',
      titleEn: 'Everyday Computing and the Internet',
      titleZh: '日常计算与互联网',
      credits: 6,
      courseType: 'common_core',
      department: 'Common Core',
      prerequisites: 'None',
      exclusions: '',
      semester: 'Semester 1 / Semester 2',
      language: 'English',
      recommendedYear: 1,
      description: 'A Common Core course introducing computing ideas in society and everyday life.',
      officialUrl: 'https://commoncore.hku.hk/',
      lastVerifiedAt: '2026-07-04'
    }
  ],
  requirements: [
    { id: 1, programmeId: 1, majorId: 1, curriculumYear: '2026', type: 'core', name: 'Core Courses', requiredCredits: 24, courseIds: [1, 2, 3, 4] },
    { id: 2, programmeId: 1, majorId: 1, curriculumYear: '2026', type: 'major_elective', name: 'Major Electives', requiredCredits: 12, courseIds: [5] },
    { id: 3, programmeId: 1, majorId: 1, curriculumYear: '2026', type: 'common_core', name: 'Common Core', requiredCredits: 6, courseIds: [7] },
    { id: 4, programmeId: 1, majorId: 1, curriculumYear: '2026', type: 'capstone', name: 'Capstone', requiredCredits: 12, courseIds: [6] }
  ]
};

module.exports = data;
