// Generated by npm run sync:tpg. Do not edit manually.
const nodeLoaders = {
  "HKU": () => [].concat(getNodeRequire()("../subpackages/tpg-data-hku/tpgCourseData/hku")),
  "CUHK": () => [].concat(getNodeRequire()("../subpackages/tpg-data-cuhk/tpgCourseData/cuhk")),
  "HKUST": () => [].concat(getNodeRequire()("../subpackages/tpg-data-hkust/tpgCourseData/hkust")),
  "POLYU": () => [].concat(getNodeRequire()("../subpackages/tpg-data-polyu/tpgCourseData/polyu")),
  "CITYU": () => [].concat(getNodeRequire()("../subpackages/tpg-data-cityu/tpgCourseData/cityu")),
  "HKBU": () => [].concat(getNodeRequire()("../subpackages/tpg-data-hkbu/tpgCourseData/hkbu")),
  "EDUHK": () => [].concat(getNodeRequire()("../subpackages/tpg-data-eduhk/tpgCourseData/eduhk")),
  "LINGNAN": () => [].concat(getNodeRequire()("../subpackages/tpg-data-lingnan/tpgCourseData/lingnan"))
};
const counts = {
  "HKU": 39,
  "CUHK": 8,
  "HKUST": 52,
  "POLYU": 54,
  "CITYU": 60,
  "HKBU": 41,
  "EDUHK": 24,
  "LINGNAN": 26
};
const packageNames = {
  "HKU": [
    "subpackages/tpg-data-hku"
  ],
  "CUHK": [
    "subpackages/tpg-data-cuhk"
  ],
  "HKUST": [
    "subpackages/tpg-data-hkust"
  ],
  "POLYU": [
    "subpackages/tpg-data-polyu"
  ],
  "CITYU": [
    "subpackages/tpg-data-cityu"
  ],
  "HKBU": [
    "subpackages/tpg-data-hkbu"
  ],
  "EDUHK": [
    "subpackages/tpg-data-eduhk"
  ],
  "LINGNAN": [
    "subpackages/tpg-data-lingnan"
  ]
};
const cache = {};

function getNodeRequire() { return eval('require'); }

function getProgrammesByUniversityCode(universityCode) {
  const key = String(universityCode || '').toUpperCase();
  if (typeof getApp === 'function') {
    const app = getApp();
    if (app && app.globalData && app.globalData.tpgProgrammesByUniversity) {
      return app.globalData.tpgProgrammesByUniversity[key] || [];
    }
  }
  if (!nodeLoaders[key]) return [];
  if (!cache[key]) cache[key] = nodeLoaders[key]();
  return cache[key];
}

function getProgrammeCount(universityCode) {
  if (universityCode) return counts[String(universityCode || '').toUpperCase()] || 0;
  return Object.values(counts).reduce((sum, count) => sum + count, 0);
}

function getPackageNames(universityCode) {
  return packageNames[String(universityCode || '').toUpperCase()] || [];
}

module.exports = { getPackageNames, getProgrammeCount, getProgrammesByUniversityCode };
