// Generated by npm run sync:ug-catalog. Do not edit manually.
const nodeLoaders = {
  "CITYU": (nodeRequire) => [].concat(nodeRequire("../subpackages/ug-data-cityu-a/ugCourseData/cityu-a"), nodeRequire("../subpackages/ug-data-cityu-b/ugCourseData/cityu-b")),
  "CUHK": (nodeRequire) => [].concat(nodeRequire("../subpackages/ug-data-cuhk/ugCourseData/cuhk")),
  "HKU": (nodeRequire) => [].concat(nodeRequire("../subpackages/ug-data-hku/ugCourseData/hku")),
  "HKUST": (nodeRequire) => [].concat(nodeRequire("../subpackages/ug-data-hkust/ugCourseData/hkust")),
  "LINGNAN": (nodeRequire) => [].concat(nodeRequire("../subpackages/ug-data-lingnan/ugCourseData/lingnan")),
  "POLYU": (nodeRequire) => [].concat(nodeRequire("../subpackages/ug-data-polyu-a/ugCourseData/polyu-a"), nodeRequire("../subpackages/ug-data-polyu-b/ugCourseData/polyu-b")),
};
const counts = {
  "CITYU": 2362,
  "CUHK": 294,
  "HKU": 1842,
  "HKUST": 492,
  "LINGNAN": 721,
  "POLYU": 2472
};
const packageNames = {
  "CITYU": [
    "subpackages/ug-data-cityu-a",
    "subpackages/ug-data-cityu-b"
  ],
  "CUHK": [
    "subpackages/ug-data-cuhk"
  ],
  "HKU": [
    "subpackages/ug-data-hku"
  ],
  "HKUST": [
    "subpackages/ug-data-hkust"
  ],
  "LINGNAN": [
    "subpackages/ug-data-lingnan"
  ],
  "POLYU": [
    "subpackages/ug-data-polyu-a",
    "subpackages/ug-data-polyu-b"
  ]
};
const cache = {};

function getNodeRequire() {
  if (typeof module === 'undefined' || !module || typeof module.require !== 'function') return null;
  return module.require.bind(module);
}

function getCoursesByUniversityCode(universityCode) {
  const key = String(universityCode || '').toUpperCase();
  if (typeof getApp === 'function') {
    const app = getApp();
    if (app && app.globalData && app.globalData.ugCoursesByUniversity) {
      return app.globalData.ugCoursesByUniversity[key] || [];
    }
  }
  const nodeRequire = getNodeRequire();
  if (!nodeRequire || !nodeLoaders[key]) return [];
  if (!cache[key]) cache[key] = nodeLoaders[key](nodeRequire);
  return cache[key];
}

function listAllCourses() {
  return Object.keys(nodeLoaders).flatMap((universityCode) => getCoursesByUniversityCode(universityCode));
}

function getCourseCount(universityCode) {
  if (universityCode) return counts[String(universityCode || '').toUpperCase()] || 0;
  return Object.values(counts).reduce((sum, count) => sum + count, 0);
}

function getPackageNames(universityCode) {
  return packageNames[String(universityCode || '').toUpperCase()] || [];
}

module.exports = {
  getCourseCount,
  getPackageNames,
  getCoursesByUniversityCode,
  listAllCourses
};
