// Generated by npm run sync:ug-catalog. Do not edit manually.
const loaders = {
  "CITYU": () => require('../subpackages/ug-data/ugCourseData/cityu'),
  "CUHK": () => require('../subpackages/ug-data/ugCourseData/cuhk'),
  "HKU": () => require('../subpackages/ug-data/ugCourseData/hku'),
  "HKUST": () => require('../subpackages/ug-data/ugCourseData/hkust'),
  "LINGNAN": () => require('../subpackages/ug-data/ugCourseData/lingnan'),
  "POLYU": () => require('../subpackages/ug-data/ugCourseData/polyu'),
};
const counts = {
  "CITYU": 1966,
  "CUHK": 131,
  "HKU": 1842,
  "HKUST": 121,
  "LINGNAN": 721,
  "POLYU": 2472
};
const cache = {};

function getCoursesByUniversityCode(universityCode) {
  const key = String(universityCode || '').toUpperCase();
  if (!loaders[key]) return [];
  if (!cache[key]) cache[key] = loaders[key]();
  return cache[key];
}

function listAllCourses() {
  return Object.keys(loaders).flatMap((universityCode) => getCoursesByUniversityCode(universityCode));
}

function getCourseCount(universityCode) {
  if (universityCode) return counts[String(universityCode || '').toUpperCase()] || 0;
  return Object.values(counts).reduce((sum, count) => sum + count, 0);
}

module.exports = {
  getCourseCount,
  getCoursesByUniversityCode,
  listAllCourses
};
